
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum A {
  A250MmStrikeCannons,
  A250MmStrikeCannonsCancel,
  A330MmBarrageCannons,
  A330MmBarrageCannonsCancel,
  AdeptPhaseShift,
  AdeptPhaseShiftCancel,
  AdeptShadePhaseShiftCancel,
  AdvancedConstructionCancel,
  AggressiveMutation,
  AiurLightBridgeAbandonedNe10,
  AiurLightBridgeAbandonedNe10BridgeRetract,
  AiurLightBridgeAbandonedNe10Out,
  AiurLightBridgeAbandonedNe10OutBridgeExtend,
  AiurLightBridgeAbandonedNe12,
  AiurLightBridgeAbandonedNe12BridgeRetract,
  AiurLightBridgeAbandonedNe12Out,
  AiurLightBridgeAbandonedNe12OutBridgeExtend,
  AiurLightBridgeAbandonedNe8,
  AiurLightBridgeAbandonedNe8BridgeRetract,
  AiurLightBridgeAbandonedNe8Out,
  AiurLightBridgeAbandonedNe8OutBridgeExtend,
  AiurLightBridgeAbandonedNw10,
  AiurLightBridgeAbandonedNw10BridgeRetract,
  AiurLightBridgeAbandonedNw10Out,
  AiurLightBridgeAbandonedNw10OutBridgeExtend,
  AiurLightBridgeAbandonedNw12,
  AiurLightBridgeAbandonedNw12BridgeRetract,
  AiurLightBridgeAbandonedNw12Out,
  AiurLightBridgeAbandonedNw12OutBridgeExtend,
  AiurLightBridgeAbandonedNw8,
  AiurLightBridgeAbandonedNw8BridgeRetract,
  AiurLightBridgeAbandonedNw8Out,
  AiurLightBridgeAbandonedNw8OutBridgeExtend,
  AiurLightBridgeNe10,
  AiurLightBridgeNe10BridgeRetract,
  AiurLightBridgeNe10Out,
  AiurLightBridgeNe10OutBridgeExtend,
  AiurLightBridgeNe12,
  AiurLightBridgeNe12BridgeRetract,
  AiurLightBridgeNe12Out,
  AiurLightBridgeNe12OutBridgeExtend,
  AiurLightBridgeNe8,
  AiurLightBridgeNe8BridgeRetract,
  AiurLightBridgeNe8Out,
  AiurLightBridgeNe8OutBridgeExtend,
  AiurLightBridgeNw10,
  AiurLightBridgeNw10BridgeRetract,
  AiurLightBridgeNw10Out,
  AiurLightBridgeNw10OutBridgeExtend,
  AiurLightBridgeNw12,
  AiurLightBridgeNw12BridgeRetract,
  AiurLightBridgeNw12Out,
  AiurLightBridgeNw12OutBridgeExtend,
  AiurLightBridgeNw8,
  AiurLightBridgeNw8BridgeRetract,
  AiurLightBridgeNw8Out,
  AiurLightBridgeNw8OutBridgeExtend,
  AiurTempleBridgeNe10,
  AiurTempleBridgeNe10BridgeRetract,
  AiurTempleBridgeNe10Out,
  AiurTempleBridgeNe10OutBridgeExtend,
  AiurTempleBridgeNe12,
  AiurTempleBridgeNe12BridgeRetract,
  AiurTempleBridgeNe12Out,
  AiurTempleBridgeNe12OutBridgeExtend,
  AiurTempleBridgeNe8,
  AiurTempleBridgeNe8BridgeRetract,
  AiurTempleBridgeNe8Out,
  AiurTempleBridgeNe8OutBridgeExtend,
  AiurTempleBridgeNw10,
  AiurTempleBridgeNw10BridgeRetract,
  AiurTempleBridgeNw10Out,
  AiurTempleBridgeNw10OutBridgeExtend,
  AiurTempleBridgeNw12,
  AiurTempleBridgeNw12BridgeRetract,
  AiurTempleBridgeNw12Out,
  AiurTempleBridgeNw12OutBridgeExtend,
  AiurTempleBridgeNw8,
  AiurTempleBridgeNw8BridgeRetract,
  AiurTempleBridgeNw8Out,
  AiurTempleBridgeNw8OutBridgeExtend,
  ArbiterMpRecall,
  ArbiterMpStasisField,
  ArchiveSeal,
  ArchonWarpAWrp,
  ArchonWarpArchonWarpTarget,
  ArmSiloWithNuke,
  ArmSiloWithNukeNukeArm,
  ArmoryResearch,
  ArmoryResearchSwarm,
  ArmoryResearchSwarmTerranVehicleAndShipPlatingLevel1,
  ArmoryResearchSwarmTerranVehicleAndShipPlatingLevel2,
  ArmoryResearchSwarmTerranVehicleAndShipPlatingLevel3,
  ArmoryResearchSwarmTerranVehicleAndShipWeaponsLevel1,
  ArmoryResearchSwarmTerranVehicleAndShipWeaponsLevel2,
  ArmoryResearchSwarmTerranVehicleAndShipWeaponsLevel3,
  ArmoryResearchTerranShipPlatingLevel1,
  ArmoryResearchTerranShipPlatingLevel2,
  ArmoryResearchTerranShipPlatingLevel3,
  ArmoryResearchTerranShipWeaponsLevel1,
  ArmoryResearchTerranShipWeaponsLevel2,
  ArmoryResearchTerranShipWeaponsLevel3,
  ArmoryResearchTerranVehicleAndShipPlatingLevel1,
  ArmoryResearchTerranVehicleAndShipPlatingLevel2,
  ArmoryResearchTerranVehicleAndShipPlatingLevel3,
  ArmoryResearchTerranVehiclePlatingLevel1,
  ArmoryResearchTerranVehiclePlatingLevel2,
  ArmoryResearchTerranVehiclePlatingLevel3,
  ArmoryResearchTerranVehicleWeaponsLevel1,
  ArmoryResearchTerranVehicleWeaponsLevel2,
  ArmoryResearchTerranVehicleWeaponsLevel3,
  ArtanisVortex,
  ArtanisWormholeTransit,
  AssaultMode,
  Attack,
  AttackAllowsInvulnerable,
  AttackAllowsInvulnerableAttackBarrage,
  AttackAllowsInvulnerableAttackTowards,
  AttackAttackBarrage,
  AttackAttackTowards,
  AttackProtossBuildingAttackBarrage,
  AttackProtossBuildingAttackBuilding,
  AttackProtossBuildingAttackTowards,
  AttackRedirect,
  AttackWarpPrism,
  AttackWarpPrismAttackBarrage,
  AttackWarpPrismAttackTowards,
}
impl A {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      257 => Some(Self::A250MmStrikeCannons),
      258 => Some(Self::A250MmStrikeCannonsCancel),
      3320 => Some(Self::A330MmBarrageCannons),
      3321 => Some(Self::A330MmBarrageCannonsCancel),
      2544 => Some(Self::AdeptPhaseShift),
      2545 => Some(Self::AdeptPhaseShift),
      2594 => Some(Self::AdeptPhaseShiftCancel),
      2595 => Some(Self::AdeptPhaseShiftCancel),
      2596 => Some(Self::AdeptShadePhaseShiftCancel),
      2597 => Some(Self::AdeptShadePhaseShiftCancel),
      2840 => Some(Self::AdvancedConstructionCancel),
      2841 => Some(Self::AdvancedConstructionCancel),
      2540 => Some(Self::AggressiveMutation),
      2541 => Some(Self::AggressiveMutation),
      2571 => Some(Self::AiurLightBridgeAbandonedNe10),
      2570 => Some(Self::AiurLightBridgeAbandonedNe10BridgeRetract),
      2569 => Some(Self::AiurLightBridgeAbandonedNe10Out),
      2568 => Some(Self::AiurLightBridgeAbandonedNe10OutBridgeExtend),
      2575 => Some(Self::AiurLightBridgeAbandonedNe12),
      2574 => Some(Self::AiurLightBridgeAbandonedNe12BridgeRetract),
      2573 => Some(Self::AiurLightBridgeAbandonedNe12Out),
      2572 => Some(Self::AiurLightBridgeAbandonedNe12OutBridgeExtend),
      2567 => Some(Self::AiurLightBridgeAbandonedNe8),
      2566 => Some(Self::AiurLightBridgeAbandonedNe8BridgeRetract),
      2565 => Some(Self::AiurLightBridgeAbandonedNe8Out),
      2564 => Some(Self::AiurLightBridgeAbandonedNe8OutBridgeExtend),
      2583 => Some(Self::AiurLightBridgeAbandonedNw10),
      2582 => Some(Self::AiurLightBridgeAbandonedNw10BridgeRetract),
      2581 => Some(Self::AiurLightBridgeAbandonedNw10Out),
      2580 => Some(Self::AiurLightBridgeAbandonedNw10OutBridgeExtend),
      2587 => Some(Self::AiurLightBridgeAbandonedNw12),
      2586 => Some(Self::AiurLightBridgeAbandonedNw12BridgeRetract),
      2585 => Some(Self::AiurLightBridgeAbandonedNw12Out),
      2584 => Some(Self::AiurLightBridgeAbandonedNw12OutBridgeExtend),
      2579 => Some(Self::AiurLightBridgeAbandonedNw8),
      2578 => Some(Self::AiurLightBridgeAbandonedNw8BridgeRetract),
      2577 => Some(Self::AiurLightBridgeAbandonedNw8Out),
      2576 => Some(Self::AiurLightBridgeAbandonedNw8OutBridgeExtend),
      2404 => Some(Self::AiurLightBridgeNe10),
      2403 => Some(Self::AiurLightBridgeNe10BridgeRetract),
      2402 => Some(Self::AiurLightBridgeNe10Out),
      2401 => Some(Self::AiurLightBridgeNe10OutBridgeExtend),
      2408 => Some(Self::AiurLightBridgeNe12),
      2407 => Some(Self::AiurLightBridgeNe12BridgeRetract),
      2406 => Some(Self::AiurLightBridgeNe12Out),
      2405 => Some(Self::AiurLightBridgeNe12OutBridgeExtend),
      2400 => Some(Self::AiurLightBridgeNe8),
      2399 => Some(Self::AiurLightBridgeNe8BridgeRetract),
      2398 => Some(Self::AiurLightBridgeNe8Out),
      2397 => Some(Self::AiurLightBridgeNe8OutBridgeExtend),
      2416 => Some(Self::AiurLightBridgeNw10),
      2415 => Some(Self::AiurLightBridgeNw10BridgeRetract),
      2414 => Some(Self::AiurLightBridgeNw10Out),
      2413 => Some(Self::AiurLightBridgeNw10OutBridgeExtend),
      2420 => Some(Self::AiurLightBridgeNw12),
      2419 => Some(Self::AiurLightBridgeNw12BridgeRetract),
      2418 => Some(Self::AiurLightBridgeNw12Out),
      2417 => Some(Self::AiurLightBridgeNw12OutBridgeExtend),
      2412 => Some(Self::AiurLightBridgeNw8),
      2411 => Some(Self::AiurLightBridgeNw8BridgeRetract),
      2410 => Some(Self::AiurLightBridgeNw8Out),
      2409 => Some(Self::AiurLightBridgeNw8OutBridgeExtend),
      2428 => Some(Self::AiurTempleBridgeNe10),
      2427 => Some(Self::AiurTempleBridgeNe10BridgeRetract),
      2426 => Some(Self::AiurTempleBridgeNe10Out),
      2425 => Some(Self::AiurTempleBridgeNe10OutBridgeExtend),
      2432 => Some(Self::AiurTempleBridgeNe12),
      2431 => Some(Self::AiurTempleBridgeNe12BridgeRetract),
      2430 => Some(Self::AiurTempleBridgeNe12Out),
      2429 => Some(Self::AiurTempleBridgeNe12OutBridgeExtend),
      2424 => Some(Self::AiurTempleBridgeNe8),
      2423 => Some(Self::AiurTempleBridgeNe8BridgeRetract),
      2422 => Some(Self::AiurTempleBridgeNe8Out),
      2421 => Some(Self::AiurTempleBridgeNe8OutBridgeExtend),
      2440 => Some(Self::AiurTempleBridgeNw10),
      2439 => Some(Self::AiurTempleBridgeNw10BridgeRetract),
      2438 => Some(Self::AiurTempleBridgeNw10Out),
      2437 => Some(Self::AiurTempleBridgeNw10OutBridgeExtend),
      2444 => Some(Self::AiurTempleBridgeNw12),
      2443 => Some(Self::AiurTempleBridgeNw12BridgeRetract),
      2442 => Some(Self::AiurTempleBridgeNw12Out),
      2441 => Some(Self::AiurTempleBridgeNw12OutBridgeExtend),
      2436 => Some(Self::AiurTempleBridgeNw8),
      2435 => Some(Self::AiurTempleBridgeNw8BridgeRetract),
      2434 => Some(Self::AiurTempleBridgeNw8Out),
      2433 => Some(Self::AiurTempleBridgeNw8OutBridgeExtend),
      2475 => Some(Self::ArbiterMpRecall),
      2476 => Some(Self::ArbiterMpRecall),
      2473 => Some(Self::ArbiterMpStasisField),
      2474 => Some(Self::ArbiterMpStasisField),
      2884 => Some(Self::ArchiveSeal),
      2885 => Some(Self::ArchiveSeal),
      1766 => Some(Self::ArchonWarpAWrp),
      1767 => Some(Self::ArchonWarpArchonWarpTarget),
      711 => Some(Self::ArmSiloWithNuke),
      712 => Some(Self::ArmSiloWithNuke),
      713 => Some(Self::ArmSiloWithNuke),
      714 => Some(Self::ArmSiloWithNuke),
      715 => Some(Self::ArmSiloWithNuke),
      716 => Some(Self::ArmSiloWithNuke),
      717 => Some(Self::ArmSiloWithNuke),
      718 => Some(Self::ArmSiloWithNuke),
      719 => Some(Self::ArmSiloWithNuke),
      720 => Some(Self::ArmSiloWithNuke),
      721 => Some(Self::ArmSiloWithNuke),
      722 => Some(Self::ArmSiloWithNuke),
      723 => Some(Self::ArmSiloWithNuke),
      724 => Some(Self::ArmSiloWithNuke),
      725 => Some(Self::ArmSiloWithNuke),
      726 => Some(Self::ArmSiloWithNuke),
      727 => Some(Self::ArmSiloWithNuke),
      728 => Some(Self::ArmSiloWithNuke),
      729 => Some(Self::ArmSiloWithNuke),
      710 => Some(Self::ArmSiloWithNukeNukeArm),
      850 => Some(Self::ArmoryResearch),
      851 => Some(Self::ArmoryResearch),
      867 => Some(Self::ArmoryResearch),
      868 => Some(Self::ArmoryResearch),
      869 => Some(Self::ArmoryResearch),
      870 => Some(Self::ArmoryResearch),
      871 => Some(Self::ArmoryResearch),
      872 => Some(Self::ArmoryResearch),
      873 => Some(Self::ArmoryResearch),
      874 => Some(Self::ArmoryResearch),
      875 => Some(Self::ArmoryResearch),
      876 => Some(Self::ArmoryResearch),
      877 => Some(Self::ArmoryResearch),
      878 => Some(Self::ArmoryResearch),
      879 => Some(Self::ArmoryResearch),
      2300 => Some(Self::ArmoryResearchSwarm),
      2301 => Some(Self::ArmoryResearchSwarm),
      2302 => Some(Self::ArmoryResearchSwarm),
      2303 => Some(Self::ArmoryResearchSwarm),
      2304 => Some(Self::ArmoryResearchSwarm),
      2305 => Some(Self::ArmoryResearchSwarm),
      2306 => Some(Self::ArmoryResearchSwarm),
      2307 => Some(Self::ArmoryResearchSwarm),
      2308 => Some(Self::ArmoryResearchSwarm),
      2309 => Some(Self::ArmoryResearchSwarm),
      2310 => Some(Self::ArmoryResearchSwarm),
      2311 => Some(Self::ArmoryResearchSwarm),
      2312 => Some(Self::ArmoryResearchSwarm),
      2313 => Some(Self::ArmoryResearchSwarm),
      2314 => Some(Self::ArmoryResearchSwarm),
      2315 => Some(Self::ArmoryResearchSwarm),
      2316 => Some(Self::ArmoryResearchSwarm),
      2317 => Some(Self::ArmoryResearchSwarm),
      2318 => Some(Self::ArmoryResearchSwarm),
      2319 => Some(Self::ArmoryResearchSwarm),
      2320 => Some(Self::ArmoryResearchSwarm),
      2321 => Some(Self::ArmoryResearchSwarm),
      2322 => Some(Self::ArmoryResearchSwarm),
      2323 => Some(Self::ArmoryResearchSwarm),
      2297 => Some(Self::ArmoryResearchSwarmTerranVehicleAndShipPlatingLevel1),
      2298 => Some(Self::ArmoryResearchSwarmTerranVehicleAndShipPlatingLevel2),
      2299 => Some(Self::ArmoryResearchSwarmTerranVehicleAndShipPlatingLevel3),
      2294 => Some(Self::ArmoryResearchSwarmTerranVehicleAndShipWeaponsLevel1),
      2295 => Some(Self::ArmoryResearchSwarmTerranVehicleAndShipWeaponsLevel2),
      2296 => Some(Self::ArmoryResearchSwarmTerranVehicleAndShipWeaponsLevel3),
      858 => Some(Self::ArmoryResearchTerranShipPlatingLevel1),
      859 => Some(Self::ArmoryResearchTerranShipPlatingLevel2),
      860 => Some(Self::ArmoryResearchTerranShipPlatingLevel3),
      861 => Some(Self::ArmoryResearchTerranShipWeaponsLevel1),
      862 => Some(Self::ArmoryResearchTerranShipWeaponsLevel2),
      863 => Some(Self::ArmoryResearchTerranShipWeaponsLevel3),
      864 => Some(Self::ArmoryResearchTerranVehicleAndShipPlatingLevel1),
      865 => Some(Self::ArmoryResearchTerranVehicleAndShipPlatingLevel2),
      866 => Some(Self::ArmoryResearchTerranVehicleAndShipPlatingLevel3),
      852 => Some(Self::ArmoryResearchTerranVehiclePlatingLevel1),
      853 => Some(Self::ArmoryResearchTerranVehiclePlatingLevel2),
      854 => Some(Self::ArmoryResearchTerranVehiclePlatingLevel3),
      855 => Some(Self::ArmoryResearchTerranVehicleWeaponsLevel1),
      856 => Some(Self::ArmoryResearchTerranVehicleWeaponsLevel2),
      857 => Some(Self::ArmoryResearchTerranVehicleWeaponsLevel3),
      2886 => Some(Self::ArtanisVortex),
      2887 => Some(Self::ArtanisVortex),
      2888 => Some(Self::ArtanisWormholeTransit),
      2889 => Some(Self::ArtanisWormholeTransit),
      403 => Some(Self::AssaultMode),
      404 => Some(Self::AssaultMode),
      23 => Some(Self::Attack),
      3295 => Some(Self::AttackAllowsInvulnerable),
      3297 => Some(Self::AttackAllowsInvulnerableAttackBarrage),
      3296 => Some(Self::AttackAllowsInvulnerableAttackTowards),
      25 => Some(Self::AttackAttackBarrage),
      24 => Some(Self::AttackAttackTowards),
      2050 => Some(Self::AttackProtossBuildingAttackBarrage),
      2048 => Some(Self::AttackProtossBuildingAttackBuilding),
      2049 => Some(Self::AttackProtossBuildingAttackTowards),
      1682 => Some(Self::AttackRedirect),
      301 => Some(Self::AttackWarpPrism),
      303 => Some(Self::AttackWarpPrismAttackBarrage),
      302 => Some(Self::AttackWarpPrismAttackTowards),
      _ => None,
    }
  }
}
