
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum B {
  BanelingNestResearch,
  BanelingNestResearchEvolveCentrificalHooks,
  BansheeCloakCloakOff,
  BansheeCloakCloakOnBanshee,
  BarracksAddOns,
  BarracksAddOnsBuildTechLabBarracks,
  BarracksAddOnsCancel,
  BarracksAddOnsReactor,
  BarracksLand,
  BarracksLiftOff,
  BarracksReactorMorph,
  BarracksTechLabMorph,
  BarracksTechLabMorphTechLabBarracks,
  BarracksTechLabResearch,
  BarracksTechLabResearchResearchPunisherGrenades,
  BarracksTechLabResearchResearchShieldWall,
  BarracksTechLabResearchStimpack,
  BarracksTechReactorMorph,
  BarracksTechReactorMorphTechLabBarracks,
  BarracksTrain,
  BarracksTrainGhost,
  BarracksTrainMarauder,
  BarracksTrainMarine,
  BarracksTrainReaper,
  BattlecruiserAttack,
  BattlecruiserAttackAttackBarrage,
  BattlecruiserAttackAttackTowards,
  BattlecruiserAttackEvaluator,
  BattlecruiserAttackEvaluatorMothershipCoreAttack,
  BattlecruiserMove,
  BattlecruiserMoveAcquireMove,
  BattlecruiserMoveMoveHoldPosition,
  BattlecruiserMoveMovePatrol,
  BattlecruiserMoveTurn,
  BattlecruiserStop,
  BattlecruiserStopCheer,
  BattlecruiserStopDance,
  BattlecruiserStopEvaluator,
  BattlecruiserStopHoldFire,
  BeaconBeaconMove,
  BeaconCancel,
  BioDomeCommandLand,
  BioDomeCommandLiftOff,
  BioPlasmidDischarge,
  BioStasis,
  BiodomeTransport,
  BiodomeTransportBiodomeLoad,
  BiodomeTransportBiodomeUnloadAll,
  BlindingCloud,
  Blink,
  BonesHeal,
  BonesTossGrenade,
  BonesTossGrenadeTossGrenadeTychus,
  BroodLordHangar,
  BroodLordQueue2Cancel,
  BroodLordQueue2CancelSlot,
  BuildAutoTurret,
  BuildInProgressCancel,
  BuildNydusCanal,
  BuildNydusCanalCancel,
  BuildNydusCanalSummonNydusCanalAttacker,
  BuildTechLab,
  BuildTechReactor,
  BuildinProgressNonCancellable,
  BuildinProgressNydusCanalCancel,
  BuildingShield,
  BuildingStasis,
  BunkerAttack,
  BunkerAttackAttackBarrage,
  BunkerAttackAttackTowards,
  BunkerStop,
  BunkerStopHoldFireSpecial,
  BunkerStopStopBunker,
  BunkerTransport,
  BunkerTransportBunkerLoad,
  BunkerTransportBunkerUnloadAll,
  BurrowBanelingDownBurrowDown,
  BurrowBanelingDownCancel,
  BurrowBanelingUp,
  BurrowBanelingUpBurrowUp,
  BurrowChargeMp,
  BurrowChargeRevD,
  BurrowChargeTrial,
  BurrowCreepTumorDown,
  BurrowCreepTumorDownBurrowDown,
  BurrowDown,
  BurrowDroneDownBurrowDown,
  BurrowDroneDownCancel,
  BurrowDroneUp,
  BurrowDroneUpBurrowUp,
  BurrowHunterKillerDownBurrowDown,
  BurrowHunterKillerDownCancel,
  BurrowHunterKillerUp,
  BurrowHunterKillerUpBurrowUp,
  BurrowHydraliskDownBurrowDown,
  BurrowHydraliskDownCancel,
  BurrowHydraliskUp,
  BurrowHydraliskUpBurrowUp,
  BurrowInfestedAbominationDown,
  BurrowInfestedAbominationDownBurrowDown,
  BurrowInfestedAbominationUp,
  BurrowInfestedAbominationUpBurrowUp,
  BurrowInfestedCivilianDown,
  BurrowInfestedCivilianDownBurrowDown,
  BurrowInfestedCivilianUp,
  BurrowInfestedCivilianUpBurrowUp,
  BurrowInfestedTerranCampaignDown,
  BurrowInfestedTerranCampaignDownBurrowDown,
  BurrowInfestedTerranCampaignUp,
  BurrowInfestedTerranCampaignUpBurrowUp,
  BurrowInfestorDownBurrowDown,
  BurrowInfestorDownCancel,
  BurrowInfestorTerranDown,
  BurrowInfestorTerranDownBurrowDown,
  BurrowInfestorTerranUp,
  BurrowInfestorTerranUpBurrowUp,
  BurrowInfestorUp,
  BurrowInfestorUpBurrowUp,
  BurrowLurkerDownBurrowDown,
  BurrowLurkerDownCancel,
  BurrowLurkerMpDownBurrowDown,
  BurrowLurkerMpDownCancel,
  BurrowLurkerMpUp,
  BurrowLurkerMpUpBurrowUp,
  BurrowLurkerUp,
  BurrowLurkerUpBurrowUp,
  BurrowOmegaliskDown,
  BurrowOmegaliskDownBurrowDown,
  BurrowOmegaliskUp,
  BurrowOmegaliskUpBurrowUp,
  BurrowQueenDownBurrowDown,
  BurrowQueenDownCancel,
  BurrowQueenUp,
  BurrowQueenUpBurrowUp,
  BurrowRavagerDownBurrowDown,
  BurrowRavagerDownCancel,
  BurrowRavagerUp,
  BurrowRavagerUpBurrowUp,
  BurrowRoachDownBurrowDown,
  BurrowRoachDownCancel,
  BurrowRoachUp,
  BurrowRoachUpBurrowUp,
  BurrowUltraliskDown,
  BurrowUltraliskDownBurrowDown,
  BurrowUltraliskUp,
  BurrowUltraliskUpBurrowUp,
  BurrowUp,
  BurrowZerglingDownBurrowDown,
  BurrowZerglingDownCancel,
  BurrowZerglingUp,
  BurrowZerglingUpBurrowUp,
  BurrowedBanelingStop,
  BurrowedBanelingStopHoldFireSpecial,
  BurrowedBanelingStopStopRoachBurrowed,
  BurrowedStop,
  BurrowedStopHoldFireSpecial,
  BurrowedStopStopRoachBurrowed,
  BypassArmor,
  BypassArmorDroneCu,
}
impl B {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      1483 => Some(Self::BanelingNestResearch),
      1484 => Some(Self::BanelingNestResearch),
      1485 => Some(Self::BanelingNestResearch),
      1486 => Some(Self::BanelingNestResearch),
      1487 => Some(Self::BanelingNestResearch),
      1488 => Some(Self::BanelingNestResearch),
      1489 => Some(Self::BanelingNestResearch),
      1490 => Some(Self::BanelingNestResearch),
      1491 => Some(Self::BanelingNestResearch),
      1492 => Some(Self::BanelingNestResearch),
      1493 => Some(Self::BanelingNestResearch),
      1494 => Some(Self::BanelingNestResearch),
      1495 => Some(Self::BanelingNestResearch),
      1496 => Some(Self::BanelingNestResearch),
      1497 => Some(Self::BanelingNestResearch),
      1498 => Some(Self::BanelingNestResearch),
      1499 => Some(Self::BanelingNestResearch),
      1500 => Some(Self::BanelingNestResearch),
      1501 => Some(Self::BanelingNestResearch),
      1502 => Some(Self::BanelingNestResearch),
      1503 => Some(Self::BanelingNestResearch),
      1504 => Some(Self::BanelingNestResearch),
      1505 => Some(Self::BanelingNestResearch),
      1506 => Some(Self::BanelingNestResearch),
      1507 => Some(Self::BanelingNestResearch),
      1508 => Some(Self::BanelingNestResearch),
      1509 => Some(Self::BanelingNestResearch),
      1510 => Some(Self::BanelingNestResearch),
      1511 => Some(Self::BanelingNestResearch),
      1482 => Some(Self::BanelingNestResearchEvolveCentrificalHooks),
      393 => Some(Self::BansheeCloakCloakOff),
      392 => Some(Self::BansheeCloakCloakOnBanshee),
      423 => Some(Self::BarracksAddOns),
      424 => Some(Self::BarracksAddOns),
      425 => Some(Self::BarracksAddOns),
      426 => Some(Self::BarracksAddOns),
      427 => Some(Self::BarracksAddOns),
      428 => Some(Self::BarracksAddOns),
      429 => Some(Self::BarracksAddOns),
      430 => Some(Self::BarracksAddOns),
      431 => Some(Self::BarracksAddOns),
      432 => Some(Self::BarracksAddOns),
      433 => Some(Self::BarracksAddOns),
      434 => Some(Self::BarracksAddOns),
      435 => Some(Self::BarracksAddOns),
      436 => Some(Self::BarracksAddOns),
      437 => Some(Self::BarracksAddOns),
      438 => Some(Self::BarracksAddOns),
      439 => Some(Self::BarracksAddOns),
      440 => Some(Self::BarracksAddOns),
      441 => Some(Self::BarracksAddOns),
      442 => Some(Self::BarracksAddOns),
      443 => Some(Self::BarracksAddOns),
      444 => Some(Self::BarracksAddOns),
      445 => Some(Self::BarracksAddOns),
      446 => Some(Self::BarracksAddOns),
      447 => Some(Self::BarracksAddOns),
      448 => Some(Self::BarracksAddOns),
      449 => Some(Self::BarracksAddOns),
      450 => Some(Self::BarracksAddOns),
      421 => Some(Self::BarracksAddOnsBuildTechLabBarracks),
      451 => Some(Self::BarracksAddOnsCancel),
      422 => Some(Self::BarracksAddOnsReactor),
      554 => Some(Self::BarracksLand),
      555 => Some(Self::BarracksLand),
      452 => Some(Self::BarracksLiftOff),
      453 => Some(Self::BarracksLiftOff),
      1676 => Some(Self::BarracksReactorMorph),
      1677 => Some(Self::BarracksReactorMorph),
      1669 => Some(Self::BarracksTechLabMorph),
      1668 => Some(Self::BarracksTechLabMorphTechLabBarracks),
      733 => Some(Self::BarracksTechLabResearch),
      734 => Some(Self::BarracksTechLabResearch),
      735 => Some(Self::BarracksTechLabResearch),
      736 => Some(Self::BarracksTechLabResearch),
      737 => Some(Self::BarracksTechLabResearch),
      738 => Some(Self::BarracksTechLabResearch),
      739 => Some(Self::BarracksTechLabResearch),
      740 => Some(Self::BarracksTechLabResearch),
      741 => Some(Self::BarracksTechLabResearch),
      742 => Some(Self::BarracksTechLabResearch),
      743 => Some(Self::BarracksTechLabResearch),
      744 => Some(Self::BarracksTechLabResearch),
      745 => Some(Self::BarracksTechLabResearch),
      746 => Some(Self::BarracksTechLabResearch),
      747 => Some(Self::BarracksTechLabResearch),
      748 => Some(Self::BarracksTechLabResearch),
      749 => Some(Self::BarracksTechLabResearch),
      750 => Some(Self::BarracksTechLabResearch),
      751 => Some(Self::BarracksTechLabResearch),
      752 => Some(Self::BarracksTechLabResearch),
      753 => Some(Self::BarracksTechLabResearch),
      754 => Some(Self::BarracksTechLabResearch),
      755 => Some(Self::BarracksTechLabResearch),
      756 => Some(Self::BarracksTechLabResearch),
      757 => Some(Self::BarracksTechLabResearch),
      758 => Some(Self::BarracksTechLabResearch),
      759 => Some(Self::BarracksTechLabResearch),
      732 => Some(Self::BarracksTechLabResearchResearchPunisherGrenades),
      731 => Some(Self::BarracksTechLabResearchResearchShieldWall),
      730 => Some(Self::BarracksTechLabResearchStimpack),
      3305 => Some(Self::BarracksTechReactorMorph),
      3304 => Some(Self::BarracksTechReactorMorphTechLabBarracks),
      564 => Some(Self::BarracksTrain),
      565 => Some(Self::BarracksTrain),
      566 => Some(Self::BarracksTrain),
      567 => Some(Self::BarracksTrain),
      568 => Some(Self::BarracksTrain),
      569 => Some(Self::BarracksTrain),
      570 => Some(Self::BarracksTrain),
      571 => Some(Self::BarracksTrain),
      572 => Some(Self::BarracksTrain),
      573 => Some(Self::BarracksTrain),
      574 => Some(Self::BarracksTrain),
      575 => Some(Self::BarracksTrain),
      576 => Some(Self::BarracksTrain),
      577 => Some(Self::BarracksTrain),
      578 => Some(Self::BarracksTrain),
      579 => Some(Self::BarracksTrain),
      580 => Some(Self::BarracksTrain),
      581 => Some(Self::BarracksTrain),
      582 => Some(Self::BarracksTrain),
      583 => Some(Self::BarracksTrain),
      584 => Some(Self::BarracksTrain),
      585 => Some(Self::BarracksTrain),
      586 => Some(Self::BarracksTrain),
      587 => Some(Self::BarracksTrain),
      588 => Some(Self::BarracksTrain),
      589 => Some(Self::BarracksTrain),
      562 => Some(Self::BarracksTrainGhost),
      563 => Some(Self::BarracksTrainMarauder),
      560 => Some(Self::BarracksTrainMarine),
      561 => Some(Self::BarracksTrainReaper),
      3771 => Some(Self::BattlecruiserAttack),
      3773 => Some(Self::BattlecruiserAttackAttackBarrage),
      3772 => Some(Self::BattlecruiserAttackAttackTowards),
      3775 => Some(Self::BattlecruiserAttackEvaluator),
      3774 => Some(Self::BattlecruiserAttackEvaluatorMothershipCoreAttack),
      3776 => Some(Self::BattlecruiserMove),
      3779 => Some(Self::BattlecruiserMoveAcquireMove),
      3778 => Some(Self::BattlecruiserMoveMoveHoldPosition),
      3777 => Some(Self::BattlecruiserMoveMovePatrol),
      3780 => Some(Self::BattlecruiserMoveTurn),
      3783 => Some(Self::BattlecruiserStop),
      3787 => Some(Self::BattlecruiserStop),
      3788 => Some(Self::BattlecruiserStop),
      3785 => Some(Self::BattlecruiserStopCheer),
      3786 => Some(Self::BattlecruiserStopDance),
      3781 => Some(Self::BattlecruiserStopEvaluator),
      3782 => Some(Self::BattlecruiserStopEvaluator),
      3784 => Some(Self::BattlecruiserStopHoldFire),
      22 => Some(Self::BeaconBeaconMove),
      21 => Some(Self::BeaconCancel),
      3352 => Some(Self::BioDomeCommandLand),
      3353 => Some(Self::BioDomeCommandLand),
      3350 => Some(Self::BioDomeCommandLiftOff),
      3351 => Some(Self::BioDomeCommandLiftOff),
      3378 => Some(Self::BioPlasmidDischarge),
      3379 => Some(Self::BioPlasmidDischarge),
      3384 => Some(Self::BioStasis),
      3385 => Some(Self::BioStasis),
      3276 => Some(Self::BiodomeTransport),
      3277 => Some(Self::BiodomeTransport),
      3278 => Some(Self::BiodomeTransport),
      3274 => Some(Self::BiodomeTransportBiodomeLoad),
      3275 => Some(Self::BiodomeTransportBiodomeUnloadAll),
      2063 => Some(Self::BlindingCloud),
      2064 => Some(Self::BlindingCloud),
      1442 => Some(Self::Blink),
      1443 => Some(Self::Blink),
      2938 => Some(Self::BonesHeal),
      2939 => Some(Self::BonesHeal),
      2941 => Some(Self::BonesTossGrenade),
      2940 => Some(Self::BonesTossGrenadeTossGrenadeTychus),
      1799 => Some(Self::BroodLordHangar),
      1800 => Some(Self::BroodLordHangar),
      1801 => Some(Self::BroodLordHangar),
      1802 => Some(Self::BroodLordHangar),
      1803 => Some(Self::BroodLordHangar),
      1804 => Some(Self::BroodLordHangar),
      1805 => Some(Self::BroodLordHangar),
      1806 => Some(Self::BroodLordHangar),
      1807 => Some(Self::BroodLordHangar),
      1808 => Some(Self::BroodLordHangar),
      1809 => Some(Self::BroodLordHangar),
      1810 => Some(Self::BroodLordHangar),
      1811 => Some(Self::BroodLordHangar),
      1812 => Some(Self::BroodLordHangar),
      1813 => Some(Self::BroodLordHangar),
      1814 => Some(Self::BroodLordHangar),
      1815 => Some(Self::BroodLordHangar),
      1816 => Some(Self::BroodLordHangar),
      1817 => Some(Self::BroodLordHangar),
      1818 => Some(Self::BroodLordHangar),
      1040 => Some(Self::BroodLordQueue2Cancel),
      1041 => Some(Self::BroodLordQueue2CancelSlot),
      1764 => Some(Self::BuildAutoTurret),
      1765 => Some(Self::BuildAutoTurret),
      314 => Some(Self::BuildInProgressCancel),
      315 => Some(Self::BuildInProgressCancel),
      1768 => Some(Self::BuildNydusCanal),
      1770 => Some(Self::BuildNydusCanal),
      1771 => Some(Self::BuildNydusCanal),
      1772 => Some(Self::BuildNydusCanal),
      1773 => Some(Self::BuildNydusCanal),
      1774 => Some(Self::BuildNydusCanal),
      1775 => Some(Self::BuildNydusCanal),
      1776 => Some(Self::BuildNydusCanal),
      1777 => Some(Self::BuildNydusCanal),
      1778 => Some(Self::BuildNydusCanal),
      1779 => Some(Self::BuildNydusCanal),
      1780 => Some(Self::BuildNydusCanal),
      1781 => Some(Self::BuildNydusCanal),
      1782 => Some(Self::BuildNydusCanal),
      1783 => Some(Self::BuildNydusCanal),
      1784 => Some(Self::BuildNydusCanal),
      1785 => Some(Self::BuildNydusCanal),
      1786 => Some(Self::BuildNydusCanal),
      1787 => Some(Self::BuildNydusCanal),
      1788 => Some(Self::BuildNydusCanal),
      1789 => Some(Self::BuildNydusCanal),
      1790 => Some(Self::BuildNydusCanal),
      1791 => Some(Self::BuildNydusCanal),
      1792 => Some(Self::BuildNydusCanal),
      1793 => Some(Self::BuildNydusCanal),
      1794 => Some(Self::BuildNydusCanal),
      1795 => Some(Self::BuildNydusCanal),
      1796 => Some(Self::BuildNydusCanal),
      1797 => Some(Self::BuildNydusCanal),
      1798 => Some(Self::BuildNydusCanalCancel),
      1769 => Some(Self::BuildNydusCanalSummonNydusCanalAttacker),
      3682 => Some(Self::BuildTechLab),
      3683 => Some(Self::BuildTechReactor),
      2842 => Some(Self::BuildinProgressNonCancellable),
      2843 => Some(Self::BuildinProgressNonCancellable),
      175 => Some(Self::BuildinProgressNydusCanalCancel),
      176 => Some(Self::BuildinProgressNydusCanalCancel),
      1994 => Some(Self::BuildingShield),
      1995 => Some(Self::BuildingShield),
      2000 => Some(Self::BuildingStasis),
      2001 => Some(Self::BuildingStasis),
      2890 => Some(Self::BunkerAttack),
      2892 => Some(Self::BunkerAttackAttackBarrage),
      2891 => Some(Self::BunkerAttackAttackTowards),
      2895 => Some(Self::BunkerStop),
      2896 => Some(Self::BunkerStop),
      2897 => Some(Self::BunkerStop),
      2898 => Some(Self::BunkerStop),
      2894 => Some(Self::BunkerStopHoldFireSpecial),
      2893 => Some(Self::BunkerStopStopBunker),
      409 => Some(Self::BunkerTransport),
      410 => Some(Self::BunkerTransport),
      411 => Some(Self::BunkerTransport),
      407 => Some(Self::BunkerTransportBunkerLoad),
      408 => Some(Self::BunkerTransportBunkerUnloadAll),
      1374 => Some(Self::BurrowBanelingDownBurrowDown),
      1375 => Some(Self::BurrowBanelingDownCancel),
      1377 => Some(Self::BurrowBanelingUp),
      1376 => Some(Self::BurrowBanelingUpBurrowUp),
      2010 => Some(Self::BurrowChargeMp),
      2011 => Some(Self::BurrowChargeMp),
      2012 => Some(Self::BurrowChargeRevD),
      2013 => Some(Self::BurrowChargeRevD),
      1984 => Some(Self::BurrowChargeTrial),
      1985 => Some(Self::BurrowChargeTrial),
      1663 => Some(Self::BurrowCreepTumorDown),
      1662 => Some(Self::BurrowCreepTumorDownBurrowDown),
      3661 => Some(Self::BurrowDown),
      1378 => Some(Self::BurrowDroneDownBurrowDown),
      1379 => Some(Self::BurrowDroneDownCancel),
      1381 => Some(Self::BurrowDroneUp),
      1380 => Some(Self::BurrowDroneUpBurrowUp),
      3228 => Some(Self::BurrowHunterKillerDownBurrowDown),
      3229 => Some(Self::BurrowHunterKillerDownCancel),
      3231 => Some(Self::BurrowHunterKillerUp),
      3230 => Some(Self::BurrowHunterKillerUpBurrowUp),
      1382 => Some(Self::BurrowHydraliskDownBurrowDown),
      1383 => Some(Self::BurrowHydraliskDownCancel),
      1385 => Some(Self::BurrowHydraliskUp),
      1384 => Some(Self::BurrowHydraliskUpBurrowUp),
      3225 => Some(Self::BurrowInfestedAbominationDown),
      3224 => Some(Self::BurrowInfestedAbominationDownBurrowDown),
      3227 => Some(Self::BurrowInfestedAbominationUp),
      3226 => Some(Self::BurrowInfestedAbominationUpBurrowUp),
      2964 => Some(Self::BurrowInfestedCivilianDown),
      2963 => Some(Self::BurrowInfestedCivilianDownBurrowDown),
      2966 => Some(Self::BurrowInfestedCivilianUp),
      2965 => Some(Self::BurrowInfestedCivilianUpBurrowUp),
      3241 => Some(Self::BurrowInfestedTerranCampaignDown),
      3240 => Some(Self::BurrowInfestedTerranCampaignDownBurrowDown),
      3243 => Some(Self::BurrowInfestedTerranCampaignUp),
      3242 => Some(Self::BurrowInfestedTerranCampaignUpBurrowUp),
      1444 => Some(Self::BurrowInfestorDownBurrowDown),
      1445 => Some(Self::BurrowInfestorDownCancel),
      1395 => Some(Self::BurrowInfestorTerranDown),
      1394 => Some(Self::BurrowInfestorTerranDownBurrowDown),
      1397 => Some(Self::BurrowInfestorTerranUp),
      1396 => Some(Self::BurrowInfestorTerranUpBurrowUp),
      1447 => Some(Self::BurrowInfestorUp),
      1446 => Some(Self::BurrowInfestorUpBurrowUp),
      2754 => Some(Self::BurrowLurkerDownBurrowDown),
      2755 => Some(Self::BurrowLurkerDownCancel),
      2108 => Some(Self::BurrowLurkerMpDownBurrowDown),
      2109 => Some(Self::BurrowLurkerMpDownCancel),
      2111 => Some(Self::BurrowLurkerMpUp),
      2110 => Some(Self::BurrowLurkerMpUpBurrowUp),
      2757 => Some(Self::BurrowLurkerUp),
      2756 => Some(Self::BurrowLurkerUpBurrowUp),
      3221 => Some(Self::BurrowOmegaliskDown),
      3220 => Some(Self::BurrowOmegaliskDownBurrowDown),
      3223 => Some(Self::BurrowOmegaliskUp),
      3222 => Some(Self::BurrowOmegaliskUpBurrowUp),
      1433 => Some(Self::BurrowQueenDownBurrowDown),
      1434 => Some(Self::BurrowQueenDownCancel),
      1436 => Some(Self::BurrowQueenUp),
      1435 => Some(Self::BurrowQueenUpBurrowUp),
      2340 => Some(Self::BurrowRavagerDownBurrowDown),
      2341 => Some(Self::BurrowRavagerDownCancel),
      2343 => Some(Self::BurrowRavagerUp),
      2342 => Some(Self::BurrowRavagerUpBurrowUp),
      1386 => Some(Self::BurrowRoachDownBurrowDown),
      1387 => Some(Self::BurrowRoachDownCancel),
      1389 => Some(Self::BurrowRoachUp),
      1388 => Some(Self::BurrowRoachUpBurrowUp),
      1513 => Some(Self::BurrowUltraliskDown),
      1512 => Some(Self::BurrowUltraliskDownBurrowDown),
      1515 => Some(Self::BurrowUltraliskUp),
      1514 => Some(Self::BurrowUltraliskUpBurrowUp),
      3662 => Some(Self::BurrowUp),
      1390 => Some(Self::BurrowZerglingDownBurrowDown),
      1391 => Some(Self::BurrowZerglingDownCancel),
      1393 => Some(Self::BurrowZerglingUp),
      1392 => Some(Self::BurrowZerglingUpBurrowUp),
      2053 => Some(Self::BurrowedBanelingStop),
      2054 => Some(Self::BurrowedBanelingStop),
      2055 => Some(Self::BurrowedBanelingStop),
      2056 => Some(Self::BurrowedBanelingStop),
      2052 => Some(Self::BurrowedBanelingStopHoldFireSpecial),
      2051 => Some(Self::BurrowedBanelingStopStopRoachBurrowed),
      1687 => Some(Self::BurrowedStop),
      1688 => Some(Self::BurrowedStop),
      1689 => Some(Self::BurrowedStop),
      1690 => Some(Self::BurrowedStop),
      1686 => Some(Self::BurrowedStopHoldFireSpecial),
      1685 => Some(Self::BurrowedStopStopRoachBurrowed),
      2710 => Some(Self::BypassArmor),
      2711 => Some(Self::BypassArmor),
      2712 => Some(Self::BypassArmorDroneCu),
      2713 => Some(Self::BypassArmorDroneCu),
      _ => None,
    }
  }
}
