
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum C {
  CalldownMule,
  Cancel,
  CancelLast,
  CancelSlot,
  CancelTerrazineHarvest,
  CarrierHangar,
  CarrierHangarInterceptor,
  CausticSpray,
  ChangeShrineProtoss,
  ChangeShrineTerran,
  ChannelSnipe,
  Charge,
  CheckStation,
  CheckStationDiagonalBlur,
  CheckStationDiagonalBlurOpened,
  CheckStationDiagonalUlbr,
  CheckStationDiagonalUlbrOpened,
  CheckStationOpened,
  CheckStationVertical,
  CheckStationVerticalOpened,
  ChronoBoostEnergyCost,
  CliffDoorClose0,
  CliffDoorClose0SpacePlatformDoorClose,
  CliffDoorClose1,
  CliffDoorClose1SpacePlatformDoorClose,
  CliffDoorOpen0,
  CliffDoorOpen0SpacePlatformDoorOpen,
  CliffDoorOpen1,
  CliffDoorOpen1SpacePlatformDoorOpen,
  CloakingDrone,
  Clone,
  ColonistShipLand,
  ColonistShipLiftOff,
  ColonistTransportTransport,
  ColonistTransportTransportColonistTransportLoad,
  ColonistTransportTransportColonistTransportUnloadAll,
  ColonyInfestation,
  ColonyShipTransport,
  ColonyShipTransportMedivacLoad,
  ColonyShipTransportMedivacUnloadAll,
  CommandCenterLand,
  CommandCenterLiftOff,
  CommandCenterTrain,
  CommandCenterTrainScv,
  CommandCenterTransport,
  CommandCenterTransportCommandCenterLoad,
  CommandCenterTransportCommandCenterUnloadAll,
  CompoundMansionDoorE,
  CompoundMansionDoorELowered,
  CompoundMansionDoorN,
  CompoundMansionDoorNLowered,
  CompoundMansionDoorNe,
  CompoundMansionDoorNeLowered,
  CompoundMansionDoorNw,
  CompoundMansionDoorNwLowered,
  ConsumeDna,
  Consumption,
  Contaminate,
  CorruptionBomb,
  CorruptionBombCancel,
  CorruptionCancel,
  CorruptionCorruptionAbility,
  CorsairMpDisruptionWeb,
  CreepTumorBuild,
  CreepTumorBuildCancel,
  CritterFlee,
  CyberneticsCoreResearch,
  CyberneticsCoreResearchProtossAirArmorLevel1,
  CyberneticsCoreResearchProtossAirArmorLevel2,
  CyberneticsCoreResearchProtossAirArmorLevel3,
  CyberneticsCoreResearchProtossAirWeaponsLevel1,
  CyberneticsCoreResearchProtossAirWeaponsLevel2,
  CyberneticsCoreResearchProtossAirWeaponsLevel3,
  CyberneticsCoreResearchResearchHallucination,
  CyberneticsCoreResearchResearchWarpGate,
}
impl C {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      171 => Some(Self::CalldownMule),
      172 => Some(Self::CalldownMule),
      3659 => Some(Self::Cancel),
      3671 => Some(Self::CancelLast),
      3672 => Some(Self::CancelSlot),
      2899 => Some(Self::CancelTerrazineHarvest),
      2900 => Some(Self::CancelTerrazineHarvest),
      1043 => Some(Self::CarrierHangar),
      1044 => Some(Self::CarrierHangar),
      1045 => Some(Self::CarrierHangar),
      1046 => Some(Self::CarrierHangar),
      1047 => Some(Self::CarrierHangar),
      1048 => Some(Self::CarrierHangar),
      1049 => Some(Self::CarrierHangar),
      1050 => Some(Self::CarrierHangar),
      1051 => Some(Self::CarrierHangar),
      1052 => Some(Self::CarrierHangar),
      1053 => Some(Self::CarrierHangar),
      1054 => Some(Self::CarrierHangar),
      1055 => Some(Self::CarrierHangar),
      1056 => Some(Self::CarrierHangar),
      1057 => Some(Self::CarrierHangar),
      1058 => Some(Self::CarrierHangar),
      1059 => Some(Self::CarrierHangar),
      1060 => Some(Self::CarrierHangar),
      1061 => Some(Self::CarrierHangar),
      1042 => Some(Self::CarrierHangarInterceptor),
      2324 => Some(Self::CausticSpray),
      2325 => Some(Self::CausticSpray),
      3619 => Some(Self::ChangeShrineProtoss),
      3620 => Some(Self::ChangeShrineProtoss),
      3617 => Some(Self::ChangeShrineTerran),
      3618 => Some(Self::ChangeShrineTerran),
      2714 => Some(Self::ChannelSnipe),
      2715 => Some(Self::ChannelSnipe),
      1819 => Some(Self::Charge),
      3279 => Some(Self::CheckStation),
      3280 => Some(Self::CheckStation),
      3281 => Some(Self::CheckStationDiagonalBlur),
      3282 => Some(Self::CheckStationDiagonalBlur),
      3289 => Some(Self::CheckStationDiagonalBlurOpened),
      3290 => Some(Self::CheckStationDiagonalBlurOpened),
      3283 => Some(Self::CheckStationDiagonalUlbr),
      3284 => Some(Self::CheckStationDiagonalUlbr),
      3291 => Some(Self::CheckStationDiagonalUlbrOpened),
      3292 => Some(Self::CheckStationDiagonalUlbrOpened),
      3287 => Some(Self::CheckStationOpened),
      3288 => Some(Self::CheckStationOpened),
      3285 => Some(Self::CheckStationVertical),
      3286 => Some(Self::CheckStationVertical),
      3293 => Some(Self::CheckStationVerticalOpened),
      3294 => Some(Self::CheckStationVerticalOpened),
      3755 => Some(Self::ChronoBoostEnergyCost),
      3756 => Some(Self::ChronoBoostEnergyCost),
      3518 => Some(Self::CliffDoorClose0),
      3517 => Some(Self::CliffDoorClose0SpacePlatformDoorClose),
      3522 => Some(Self::CliffDoorClose1),
      3521 => Some(Self::CliffDoorClose1SpacePlatformDoorClose),
      3516 => Some(Self::CliffDoorOpen0),
      3515 => Some(Self::CliffDoorOpen0SpacePlatformDoorOpen),
      3520 => Some(Self::CliffDoorOpen1),
      3519 => Some(Self::CliffDoorOpen1SpacePlatformDoorOpen),
      2592 => Some(Self::CloakingDrone),
      2593 => Some(Self::CloakingDrone),
      1992 => Some(Self::Clone),
      1993 => Some(Self::Clone),
      3348 => Some(Self::ColonistShipLand),
      3349 => Some(Self::ColonistShipLand),
      3346 => Some(Self::ColonistShipLiftOff),
      3347 => Some(Self::ColonistShipLiftOff),
      3388 => Some(Self::ColonistTransportTransport),
      3389 => Some(Self::ColonistTransportTransport),
      3390 => Some(Self::ColonistTransportTransport),
      3386 => Some(Self::ColonistTransportTransportColonistTransportLoad),
      3387 => Some(Self::ColonistTransportTransportColonistTransportUnloadAll),
      3131 => Some(Self::ColonyInfestation),
      3132 => Some(Self::ColonyInfestation),
      3127 => Some(Self::ColonyShipTransport),
      3129 => Some(Self::ColonyShipTransport),
      3130 => Some(Self::ColonyShipTransport),
      3126 => Some(Self::ColonyShipTransportMedivacLoad),
      3128 => Some(Self::ColonyShipTransportMedivacUnloadAll),
      419 => Some(Self::CommandCenterLand),
      420 => Some(Self::CommandCenterLand),
      417 => Some(Self::CommandCenterLiftOff),
      418 => Some(Self::CommandCenterLiftOff),
      525 => Some(Self::CommandCenterTrain),
      526 => Some(Self::CommandCenterTrain),
      527 => Some(Self::CommandCenterTrain),
      528 => Some(Self::CommandCenterTrain),
      529 => Some(Self::CommandCenterTrain),
      530 => Some(Self::CommandCenterTrain),
      531 => Some(Self::CommandCenterTrain),
      532 => Some(Self::CommandCenterTrain),
      533 => Some(Self::CommandCenterTrain),
      534 => Some(Self::CommandCenterTrain),
      535 => Some(Self::CommandCenterTrain),
      536 => Some(Self::CommandCenterTrain),
      537 => Some(Self::CommandCenterTrain),
      538 => Some(Self::CommandCenterTrain),
      539 => Some(Self::CommandCenterTrain),
      540 => Some(Self::CommandCenterTrain),
      541 => Some(Self::CommandCenterTrain),
      542 => Some(Self::CommandCenterTrain),
      543 => Some(Self::CommandCenterTrain),
      544 => Some(Self::CommandCenterTrain),
      545 => Some(Self::CommandCenterTrain),
      546 => Some(Self::CommandCenterTrain),
      547 => Some(Self::CommandCenterTrain),
      548 => Some(Self::CommandCenterTrain),
      549 => Some(Self::CommandCenterTrain),
      550 => Some(Self::CommandCenterTrain),
      551 => Some(Self::CommandCenterTrain),
      552 => Some(Self::CommandCenterTrain),
      553 => Some(Self::CommandCenterTrain),
      524 => Some(Self::CommandCenterTrainScv),
      412 => Some(Self::CommandCenterTransport),
      414 => Some(Self::CommandCenterTransport),
      415 => Some(Self::CommandCenterTransport),
      416 => Some(Self::CommandCenterTransportCommandCenterLoad),
      413 => Some(Self::CommandCenterTransportCommandCenterUnloadAll),
      2286 => Some(Self::CompoundMansionDoorE),
      2287 => Some(Self::CompoundMansionDoorE),
      2288 => Some(Self::CompoundMansionDoorELowered),
      2289 => Some(Self::CompoundMansionDoorELowered),
      2278 => Some(Self::CompoundMansionDoorN),
      2279 => Some(Self::CompoundMansionDoorN),
      2280 => Some(Self::CompoundMansionDoorNLowered),
      2281 => Some(Self::CompoundMansionDoorNLowered),
      2282 => Some(Self::CompoundMansionDoorNe),
      2283 => Some(Self::CompoundMansionDoorNe),
      2284 => Some(Self::CompoundMansionDoorNeLowered),
      2285 => Some(Self::CompoundMansionDoorNeLowered),
      2290 => Some(Self::CompoundMansionDoorNw),
      2291 => Some(Self::CompoundMansionDoorNw),
      2292 => Some(Self::CompoundMansionDoorNwLowered),
      2293 => Some(Self::CompoundMansionDoorNwLowered),
      2909 => Some(Self::ConsumeDna),
      2910 => Some(Self::ConsumeDna),
      2907 => Some(Self::Consumption),
      2908 => Some(Self::Consumption),
      1825 => Some(Self::Contaminate),
      1826 => Some(Self::Contaminate),
      2356 => Some(Self::CorruptionBomb),
      2357 => Some(Self::CorruptionBombCancel),
      35 => Some(Self::CorruptionCancel),
      34 => Some(Self::CorruptionCorruptionAbility),
      2477 => Some(Self::CorsairMpDisruptionWeb),
      2478 => Some(Self::CorsairMpDisruptionWeb),
      1733 => Some(Self::CreepTumorBuild),
      1734 => Some(Self::CreepTumorBuild),
      1735 => Some(Self::CreepTumorBuild),
      1736 => Some(Self::CreepTumorBuild),
      1737 => Some(Self::CreepTumorBuild),
      1738 => Some(Self::CreepTumorBuild),
      1739 => Some(Self::CreepTumorBuild),
      1740 => Some(Self::CreepTumorBuild),
      1741 => Some(Self::CreepTumorBuild),
      1742 => Some(Self::CreepTumorBuild),
      1743 => Some(Self::CreepTumorBuild),
      1744 => Some(Self::CreepTumorBuild),
      1745 => Some(Self::CreepTumorBuild),
      1746 => Some(Self::CreepTumorBuild),
      1747 => Some(Self::CreepTumorBuild),
      1748 => Some(Self::CreepTumorBuild),
      1749 => Some(Self::CreepTumorBuild),
      1750 => Some(Self::CreepTumorBuild),
      1751 => Some(Self::CreepTumorBuild),
      1752 => Some(Self::CreepTumorBuild),
      1753 => Some(Self::CreepTumorBuild),
      1754 => Some(Self::CreepTumorBuild),
      1755 => Some(Self::CreepTumorBuild),
      1756 => Some(Self::CreepTumorBuild),
      1757 => Some(Self::CreepTumorBuild),
      1758 => Some(Self::CreepTumorBuild),
      1759 => Some(Self::CreepTumorBuild),
      1760 => Some(Self::CreepTumorBuild),
      1761 => Some(Self::CreepTumorBuild),
      1762 => Some(Self::CreepTumorBuild),
      1763 => Some(Self::CreepTumorBuildCancel),
      2144 => Some(Self::CritterFlee),
      2145 => Some(Self::CritterFlee),
      1569 => Some(Self::CyberneticsCoreResearch),
      1570 => Some(Self::CyberneticsCoreResearch),
      1572 => Some(Self::CyberneticsCoreResearch),
      1573 => Some(Self::CyberneticsCoreResearch),
      1574 => Some(Self::CyberneticsCoreResearch),
      1575 => Some(Self::CyberneticsCoreResearch),
      1576 => Some(Self::CyberneticsCoreResearch),
      1577 => Some(Self::CyberneticsCoreResearch),
      1578 => Some(Self::CyberneticsCoreResearch),
      1579 => Some(Self::CyberneticsCoreResearch),
      1580 => Some(Self::CyberneticsCoreResearch),
      1581 => Some(Self::CyberneticsCoreResearch),
      1582 => Some(Self::CyberneticsCoreResearch),
      1583 => Some(Self::CyberneticsCoreResearch),
      1584 => Some(Self::CyberneticsCoreResearch),
      1585 => Some(Self::CyberneticsCoreResearch),
      1586 => Some(Self::CyberneticsCoreResearch),
      1587 => Some(Self::CyberneticsCoreResearch),
      1588 => Some(Self::CyberneticsCoreResearch),
      1589 => Some(Self::CyberneticsCoreResearch),
      1590 => Some(Self::CyberneticsCoreResearch),
      1591 => Some(Self::CyberneticsCoreResearch),
      1565 => Some(Self::CyberneticsCoreResearchProtossAirArmorLevel1),
      1566 => Some(Self::CyberneticsCoreResearchProtossAirArmorLevel2),
      1567 => Some(Self::CyberneticsCoreResearchProtossAirArmorLevel3),
      1562 => Some(Self::CyberneticsCoreResearchProtossAirWeaponsLevel1),
      1563 => Some(Self::CyberneticsCoreResearchProtossAirWeaponsLevel2),
      1564 => Some(Self::CyberneticsCoreResearchProtossAirWeaponsLevel3),
      1571 => Some(Self::CyberneticsCoreResearchResearchHallucination),
      1568 => Some(Self::CyberneticsCoreResearchResearchWarpGate),
      _ => None,
    }
  }
}
