
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum D {
  D8Charge,
  DarkShrineResearch,
  DarkShrineResearchResearchDarkTemplarBlink,
  DarkTemplarBlink,
  DefensiveMatrix,
  DefilerMpBurrowBurrowDown,
  DefilerMpBurrowCancel,
  DefilerMpConsume,
  DefilerMpDarkSwarm,
  DefilerMpPlague,
  DefilerMpUnburrow,
  DefilerMpUnburrowBurrowUp,
  DestructibleGateDiagonalBlur,
  DestructibleGateDiagonalBlurGateClose,
  DestructibleGateDiagonalBlurLowered,
  DestructibleGateDiagonalBlurLoweredGateOpen,
  DestructibleGateDiagonalUlbr,
  DestructibleGateDiagonalUlbrGateClose,
  DestructibleGateDiagonalUlbrLowered,
  DestructibleGateDiagonalUlbrLoweredGateOpen,
  DestructibleGateStraightHorizontal,
  DestructibleGateStraightHorizontalBf,
  DestructibleGateStraightHorizontalBfGateClose,
  DestructibleGateStraightHorizontalBfLowered,
  DestructibleGateStraightHorizontalBfLoweredGateOpen,
  DestructibleGateStraightHorizontalGateClose,
  DestructibleGateStraightHorizontalLowered,
  DestructibleGateStraightHorizontalLoweredGateOpen,
  DestructibleGateStraightVertical,
  DestructibleGateStraightVerticalGateClose,
  DestructibleGateStraightVerticalLf,
  DestructibleGateStraightVerticalLfGateClose,
  DestructibleGateStraightVerticalLfLowered,
  DestructibleGateStraightVerticalLfLoweredGateOpen,
  DestructibleGateStraightVerticalLowered,
  DestructibleGateStraightVerticalLoweredGateOpen,
  DigesterCreepSpray,
  DigesterTransport,
  DigesterTransportLoadDigester,
  DisguiseAsMarineWithShield,
  DisguiseAsMarineWithoutShield,
  DisguiseAsZealot,
  DisguiseAsZerglingWithWings,
  DisguiseAsZerglingWithoutWings,
  Domination,
  DominationCancel,
  DroneHarvest,
  DroneHarvestGather,
  DroneHarvestReturnCargo,
  DropToSupplyDepot,
  DropToSupplyDepotRaise,
  DukesRevengeDefensiveMatrix,
  DukesRevengeMissilePods,
  DukesRevengeYamato,
  DukesRevengeYamatoYamatoGun,
  DuskWingBansheeCloakingFieldCloakOff,
  DuskWingBansheeCloakingFieldCloakOnBanshee,
  DutchPlaceTurret,
}
impl D {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2758 => Some(Self::D8Charge),
      2759 => Some(Self::D8Charge),
      2721 => Some(Self::DarkShrineResearch),
      2722 => Some(Self::DarkShrineResearch),
      2723 => Some(Self::DarkShrineResearch),
      2724 => Some(Self::DarkShrineResearch),
      2725 => Some(Self::DarkShrineResearch),
      2726 => Some(Self::DarkShrineResearch),
      2727 => Some(Self::DarkShrineResearch),
      2728 => Some(Self::DarkShrineResearch),
      2729 => Some(Self::DarkShrineResearch),
      2730 => Some(Self::DarkShrineResearch),
      2731 => Some(Self::DarkShrineResearch),
      2732 => Some(Self::DarkShrineResearch),
      2733 => Some(Self::DarkShrineResearch),
      2734 => Some(Self::DarkShrineResearch),
      2735 => Some(Self::DarkShrineResearch),
      2736 => Some(Self::DarkShrineResearch),
      2737 => Some(Self::DarkShrineResearch),
      2738 => Some(Self::DarkShrineResearch),
      2739 => Some(Self::DarkShrineResearch),
      2740 => Some(Self::DarkShrineResearch),
      2741 => Some(Self::DarkShrineResearch),
      2742 => Some(Self::DarkShrineResearch),
      2743 => Some(Self::DarkShrineResearch),
      2744 => Some(Self::DarkShrineResearch),
      2745 => Some(Self::DarkShrineResearch),
      2746 => Some(Self::DarkShrineResearch),
      2747 => Some(Self::DarkShrineResearch),
      2748 => Some(Self::DarkShrineResearch),
      2749 => Some(Self::DarkShrineResearch),
      2720 => Some(Self::DarkShrineResearchResearchDarkTemplarBlink),
      2700 => Some(Self::DarkTemplarBlink),
      2701 => Some(Self::DarkTemplarBlink),
      2760 => Some(Self::DefensiveMatrix),
      2761 => Some(Self::DefensiveMatrix),
      2489 => Some(Self::DefilerMpBurrowBurrowDown),
      2490 => Some(Self::DefilerMpBurrowCancel),
      2483 => Some(Self::DefilerMpConsume),
      2484 => Some(Self::DefilerMpConsume),
      2485 => Some(Self::DefilerMpDarkSwarm),
      2486 => Some(Self::DefilerMpDarkSwarm),
      2487 => Some(Self::DefilerMpPlague),
      2488 => Some(Self::DefilerMpPlague),
      2492 => Some(Self::DefilerMpUnburrow),
      2491 => Some(Self::DefilerMpUnburrowBurrowUp),
      3536 => Some(Self::DestructibleGateDiagonalBlur),
      3535 => Some(Self::DestructibleGateDiagonalBlurGateClose),
      3524 => Some(Self::DestructibleGateDiagonalBlurLowered),
      3523 => Some(Self::DestructibleGateDiagonalBlurLoweredGateOpen),
      3538 => Some(Self::DestructibleGateDiagonalUlbr),
      3537 => Some(Self::DestructibleGateDiagonalUlbrGateClose),
      3526 => Some(Self::DestructibleGateDiagonalUlbrLowered),
      3525 => Some(Self::DestructibleGateDiagonalUlbrLoweredGateOpen),
      3542 => Some(Self::DestructibleGateStraightHorizontal),
      3540 => Some(Self::DestructibleGateStraightHorizontalBf),
      3539 => Some(Self::DestructibleGateStraightHorizontalBfGateClose),
      3528 => Some(Self::DestructibleGateStraightHorizontalBfLowered),
      3527 => Some(Self::DestructibleGateStraightHorizontalBfLoweredGateOpen),
      3541 => Some(Self::DestructibleGateStraightHorizontalGateClose),
      3530 => Some(Self::DestructibleGateStraightHorizontalLowered),
      3529 => Some(Self::DestructibleGateStraightHorizontalLoweredGateOpen),
      3546 => Some(Self::DestructibleGateStraightVertical),
      3545 => Some(Self::DestructibleGateStraightVerticalGateClose),
      3544 => Some(Self::DestructibleGateStraightVerticalLf),
      3543 => Some(Self::DestructibleGateStraightVerticalLfGateClose),
      3532 => Some(Self::DestructibleGateStraightVerticalLfLowered),
      3531 => Some(Self::DestructibleGateStraightVerticalLfLoweredGateOpen),
      3534 => Some(Self::DestructibleGateStraightVerticalLowered),
      3533 => Some(Self::DestructibleGateStraightVerticalLoweredGateOpen),
      1839 => Some(Self::DigesterCreepSpray),
      1840 => Some(Self::DigesterCreepSpray),
      1922 => Some(Self::DigesterTransport),
      1923 => Some(Self::DigesterTransport),
      1924 => Some(Self::DigesterTransport),
      1925 => Some(Self::DigesterTransport),
      1921 => Some(Self::DigesterTransportLoadDigester),
      185 => Some(Self::DisguiseAsMarineWithShield),
      186 => Some(Self::DisguiseAsMarineWithShield),
      187 => Some(Self::DisguiseAsMarineWithoutShield),
      188 => Some(Self::DisguiseAsMarineWithoutShield),
      183 => Some(Self::DisguiseAsZealot),
      184 => Some(Self::DisguiseAsZealot),
      189 => Some(Self::DisguiseAsZerglingWithWings),
      190 => Some(Self::DisguiseAsZerglingWithWings),
      191 => Some(Self::DisguiseAsZerglingWithoutWings),
      192 => Some(Self::DisguiseAsZerglingWithoutWings),
      3133 => Some(Self::Domination),
      3134 => Some(Self::DominationCancel),
      1185 => Some(Self::DroneHarvest),
      1183 => Some(Self::DroneHarvestGather),
      1184 => Some(Self::DroneHarvestReturnCargo),
      3392 => Some(Self::DropToSupplyDepot),
      3391 => Some(Self::DropToSupplyDepotRaise),
      3314 => Some(Self::DukesRevengeDefensiveMatrix),
      3315 => Some(Self::DukesRevengeDefensiveMatrix),
      3316 => Some(Self::DukesRevengeMissilePods),
      3317 => Some(Self::DukesRevengeMissilePods),
      3191 => Some(Self::DukesRevengeYamato),
      3190 => Some(Self::DukesRevengeYamatoYamatoGun),
      2953 => Some(Self::DuskWingBansheeCloakingFieldCloakOff),
      2952 => Some(Self::DuskWingBansheeCloakingFieldCloakOnBanshee),
      2961 => Some(Self::DutchPlaceTurret),
      2962 => Some(Self::DutchPlaceTurret),
      _ => None,
    }
  }
}
