
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum E {
  EffectBlink,
  EffectMassRecall,
  EggPop,
  Emp,
  EnergyNova,
  EngineeringBayResearch,
  EngineeringBayResearchResearchHiSecAutoTracking,
  EngineeringBayResearchResearchNeosteelFrame,
  EngineeringBayResearchTerranInfantryArmorLevel1,
  EngineeringBayResearchTerranInfantryArmorLevel2,
  EngineeringBayResearchTerranInfantryArmorLevel3,
  EngineeringBayResearchTerranInfantryWeaponsLevel1,
  EngineeringBayResearchTerranInfantryWeaponsLevel2,
  EngineeringBayResearchTerranInfantryWeaponsLevel3,
  EngineeringBayResearchUpgradeBuildingArmorLevel1,
  Evolutionchamberresearch,
  EvolutionchamberresearchZerggroundarmor1,
  EvolutionchamberresearchZerggroundarmor2,
  EvolutionchamberresearchZerggroundarmor3,
  EvolutionchamberresearchZergmeleeweapons1,
  EvolutionchamberresearchZergmeleeweapons2,
  EvolutionchamberresearchZergmeleeweapons3,
  EvolutionchamberresearchZergmissileweapons1,
  EvolutionchamberresearchZergmissileweapons2,
  EvolutionchamberresearchZergmissileweapons3,
  ExperimentalPlasmaGun,
  Explode,
  ExtendingBridgeNeWide10,
  ExtendingBridgeNeWide10BridgeRetract,
  ExtendingBridgeNeWide10Out,
  ExtendingBridgeNeWide10OutBridgeExtend,
  ExtendingBridgeNeWide12,
  ExtendingBridgeNeWide12BridgeRetract,
  ExtendingBridgeNeWide12Out,
  ExtendingBridgeNeWide12OutBridgeExtend,
  ExtendingBridgeNeWide8,
  ExtendingBridgeNeWide8BridgeRetract,
  ExtendingBridgeNeWide8Out,
  ExtendingBridgeNeWide8OutBridgeExtend,
  ExtendingBridgeNwWide10,
  ExtendingBridgeNwWide10BridgeRetract,
  ExtendingBridgeNwWide10Out,
  ExtendingBridgeNwWide10OutBridgeExtend,
  ExtendingBridgeNwWide12,
  ExtendingBridgeNwWide12BridgeRetract,
  ExtendingBridgeNwWide12Out,
  ExtendingBridgeNwWide12OutBridgeExtend,
  ExtendingBridgeNwWide8,
  ExtendingBridgeNwWide8BridgeRetract,
  ExtendingBridgeNwWide8Out,
  ExtendingBridgeNwWide8OutBridgeExtend,
  EyeStalk,
  EyeStalkCancel,
}
impl E {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      3687 => Some(Self::EffectBlink),
      3686 => Some(Self::EffectMassRecall),
      2911 => Some(Self::EggPop),
      2912 => Some(Self::EggPop),
      1628 => Some(Self::Emp),
      1629 => Some(Self::Emp),
      3075 => Some(Self::EnergyNova),
      3076 => Some(Self::EnergyNova),
      659 => Some(Self::EngineeringBayResearch),
      660 => Some(Self::EngineeringBayResearch),
      661 => Some(Self::EngineeringBayResearch),
      662 => Some(Self::EngineeringBayResearch),
      663 => Some(Self::EngineeringBayResearch),
      664 => Some(Self::EngineeringBayResearch),
      665 => Some(Self::EngineeringBayResearch),
      666 => Some(Self::EngineeringBayResearch),
      667 => Some(Self::EngineeringBayResearch),
      668 => Some(Self::EngineeringBayResearch),
      669 => Some(Self::EngineeringBayResearch),
      670 => Some(Self::EngineeringBayResearch),
      671 => Some(Self::EngineeringBayResearch),
      672 => Some(Self::EngineeringBayResearch),
      673 => Some(Self::EngineeringBayResearch),
      674 => Some(Self::EngineeringBayResearch),
      675 => Some(Self::EngineeringBayResearch),
      676 => Some(Self::EngineeringBayResearch),
      677 => Some(Self::EngineeringBayResearch),
      678 => Some(Self::EngineeringBayResearch),
      679 => Some(Self::EngineeringBayResearch),
      650 => Some(Self::EngineeringBayResearchResearchHiSecAutoTracking),
      655 => Some(Self::EngineeringBayResearchResearchNeosteelFrame),
      656 => Some(Self::EngineeringBayResearchTerranInfantryArmorLevel1),
      657 => Some(Self::EngineeringBayResearchTerranInfantryArmorLevel2),
      658 => Some(Self::EngineeringBayResearchTerranInfantryArmorLevel3),
      652 => Some(Self::EngineeringBayResearchTerranInfantryWeaponsLevel1),
      653 => Some(Self::EngineeringBayResearchTerranInfantryWeaponsLevel2),
      654 => Some(Self::EngineeringBayResearchTerranInfantryWeaponsLevel3),
      651 => Some(Self::EngineeringBayResearchUpgradeBuildingArmorLevel1),
      1195 => Some(Self::Evolutionchamberresearch),
      1196 => Some(Self::Evolutionchamberresearch),
      1197 => Some(Self::Evolutionchamberresearch),
      1198 => Some(Self::Evolutionchamberresearch),
      1199 => Some(Self::Evolutionchamberresearch),
      1200 => Some(Self::Evolutionchamberresearch),
      1201 => Some(Self::Evolutionchamberresearch),
      1202 => Some(Self::Evolutionchamberresearch),
      1203 => Some(Self::Evolutionchamberresearch),
      1204 => Some(Self::Evolutionchamberresearch),
      1205 => Some(Self::Evolutionchamberresearch),
      1206 => Some(Self::Evolutionchamberresearch),
      1207 => Some(Self::Evolutionchamberresearch),
      1208 => Some(Self::Evolutionchamberresearch),
      1209 => Some(Self::Evolutionchamberresearch),
      1210 => Some(Self::Evolutionchamberresearch),
      1211 => Some(Self::Evolutionchamberresearch),
      1212 => Some(Self::Evolutionchamberresearch),
      1213 => Some(Self::Evolutionchamberresearch),
      1214 => Some(Self::Evolutionchamberresearch),
      1215 => Some(Self::Evolutionchamberresearch),
      1189 => Some(Self::EvolutionchamberresearchZerggroundarmor1),
      1190 => Some(Self::EvolutionchamberresearchZerggroundarmor2),
      1191 => Some(Self::EvolutionchamberresearchZerggroundarmor3),
      1186 => Some(Self::EvolutionchamberresearchZergmeleeweapons1),
      1187 => Some(Self::EvolutionchamberresearchZergmeleeweapons2),
      1188 => Some(Self::EvolutionchamberresearchZergmeleeweapons3),
      1192 => Some(Self::EvolutionchamberresearchZergmissileweapons1),
      1193 => Some(Self::EvolutionchamberresearchZergmissileweapons2),
      1194 => Some(Self::EvolutionchamberresearchZergmissileweapons3),
      2913 => Some(Self::ExperimentalPlasmaGun),
      2914 => Some(Self::ExperimentalPlasmaGun),
      42 => Some(Self::Explode),
      43 => Some(Self::Explode),
      2129 => Some(Self::ExtendingBridgeNeWide10),
      2128 => Some(Self::ExtendingBridgeNeWide10BridgeRetract),
      2127 => Some(Self::ExtendingBridgeNeWide10Out),
      2126 => Some(Self::ExtendingBridgeNeWide10OutBridgeExtend),
      2137 => Some(Self::ExtendingBridgeNeWide12),
      2136 => Some(Self::ExtendingBridgeNeWide12BridgeRetract),
      2135 => Some(Self::ExtendingBridgeNeWide12Out),
      2134 => Some(Self::ExtendingBridgeNeWide12OutBridgeExtend),
      2121 => Some(Self::ExtendingBridgeNeWide8),
      2120 => Some(Self::ExtendingBridgeNeWide8BridgeRetract),
      2119 => Some(Self::ExtendingBridgeNeWide8Out),
      2118 => Some(Self::ExtendingBridgeNeWide8OutBridgeExtend),
      2133 => Some(Self::ExtendingBridgeNwWide10),
      2132 => Some(Self::ExtendingBridgeNwWide10BridgeRetract),
      2131 => Some(Self::ExtendingBridgeNwWide10Out),
      2130 => Some(Self::ExtendingBridgeNwWide10OutBridgeExtend),
      2141 => Some(Self::ExtendingBridgeNwWide12),
      2140 => Some(Self::ExtendingBridgeNwWide12BridgeRetract),
      2139 => Some(Self::ExtendingBridgeNwWide12Out),
      2138 => Some(Self::ExtendingBridgeNwWide12OutBridgeExtend),
      2125 => Some(Self::ExtendingBridgeNwWide8),
      2124 => Some(Self::ExtendingBridgeNwWide8BridgeRetract),
      2123 => Some(Self::ExtendingBridgeNwWide8Out),
      2122 => Some(Self::ExtendingBridgeNwWide8OutBridgeExtend),
      2065 => Some(Self::EyeStalk),
      2066 => Some(Self::EyeStalkCancel),
      _ => None,
    }
  }
}
