
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum F {
  FactoryAddOns,
  FactoryAddOnsBuildTechLabFactory,
  FactoryAddOnsCancel,
  FactoryAddOnsReactor,
  FactoryLand,
  FactoryLiftOff,
  FactoryReactorMorph,
  FactoryTechLabMorph,
  FactoryTechLabMorphTechLabFactory,
  FactoryTechLabResearch,
  FactoryTechLabResearchCycloneResearchLockOnDamageUpgrade,
  FactoryTechLabResearchResearchArmorPiercingRockets,
  FactoryTechLabResearchResearchCycloneRapidFireLaunchers,
  FactoryTechLabResearchResearchDrillClaws,
  FactoryTechLabResearchResearchHighCapacityBarrels,
  FactoryTechLabResearchResearchLockOnRangeUpgrade,
  FactoryTechLabResearchResearchSmartServos,
  FactoryTechLabResearchResearchTransformationServos,
  FactoryTechReactorMorph,
  FactoryTechReactorMorphTechLabFactory,
  FactoryTrain,
  FactoryTrainBuildCyclone,
  FactoryTrainHellion,
  FactoryTrainHellionTank,
  FactoryTrainSiegeTank,
  FactoryTrainThor,
  FactoryTrainWidowMine,
  Feedback,
  FighterMode,
  FleetBeaconResearch,
  FleetBeaconResearchPhoenixRangeUpgrade,
  FleetBeaconResearchResearchInterceptorLaunchSpeedUpgrade,
  FleetBeaconResearchTempestRangeUpgrade,
  FlyerShield,
  ForceField,
  ForceFieldBeam,
  ForceFieldCancel,
  ForgeResearch,
  ForgeResearchProtossGroundArmorLevel1,
  ForgeResearchProtossGroundArmorLevel2,
  ForgeResearchProtossGroundArmorLevel3,
  ForgeResearchProtossGroundWeaponsLevel1,
  ForgeResearchProtossGroundWeaponsLevel2,
  ForgeResearchProtossGroundWeaponsLevel3,
  ForgeResearchProtossShieldsLevel1,
  ForgeResearchProtossShieldsLevel2,
  ForgeResearchProtossShieldsLevel3,
  Frenzy,
  FungalGrowth,
  FusionCoreResearch,
  FusionCoreResearchResearchBattlecruiserSpecializations,
}
impl F {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      456 => Some(Self::FactoryAddOns),
      457 => Some(Self::FactoryAddOns),
      458 => Some(Self::FactoryAddOns),
      459 => Some(Self::FactoryAddOns),
      460 => Some(Self::FactoryAddOns),
      461 => Some(Self::FactoryAddOns),
      462 => Some(Self::FactoryAddOns),
      463 => Some(Self::FactoryAddOns),
      464 => Some(Self::FactoryAddOns),
      465 => Some(Self::FactoryAddOns),
      466 => Some(Self::FactoryAddOns),
      467 => Some(Self::FactoryAddOns),
      468 => Some(Self::FactoryAddOns),
      469 => Some(Self::FactoryAddOns),
      470 => Some(Self::FactoryAddOns),
      471 => Some(Self::FactoryAddOns),
      472 => Some(Self::FactoryAddOns),
      473 => Some(Self::FactoryAddOns),
      474 => Some(Self::FactoryAddOns),
      475 => Some(Self::FactoryAddOns),
      476 => Some(Self::FactoryAddOns),
      477 => Some(Self::FactoryAddOns),
      478 => Some(Self::FactoryAddOns),
      479 => Some(Self::FactoryAddOns),
      480 => Some(Self::FactoryAddOns),
      481 => Some(Self::FactoryAddOns),
      482 => Some(Self::FactoryAddOns),
      483 => Some(Self::FactoryAddOns),
      454 => Some(Self::FactoryAddOnsBuildTechLabFactory),
      484 => Some(Self::FactoryAddOnsCancel),
      455 => Some(Self::FactoryAddOnsReactor),
      520 => Some(Self::FactoryLand),
      521 => Some(Self::FactoryLand),
      485 => Some(Self::FactoryLiftOff),
      486 => Some(Self::FactoryLiftOff),
      1678 => Some(Self::FactoryReactorMorph),
      1679 => Some(Self::FactoryReactorMorph),
      1671 => Some(Self::FactoryTechLabMorph),
      1670 => Some(Self::FactoryTechLabMorphTechLabFactory),
      760 => Some(Self::FactoryTechLabResearch),
      762 => Some(Self::FactoryTechLabResearch),
      770 => Some(Self::FactoryTechLabResearch),
      771 => Some(Self::FactoryTechLabResearch),
      772 => Some(Self::FactoryTechLabResearch),
      773 => Some(Self::FactoryTechLabResearch),
      774 => Some(Self::FactoryTechLabResearch),
      775 => Some(Self::FactoryTechLabResearch),
      776 => Some(Self::FactoryTechLabResearch),
      777 => Some(Self::FactoryTechLabResearch),
      778 => Some(Self::FactoryTechLabResearch),
      779 => Some(Self::FactoryTechLabResearch),
      780 => Some(Self::FactoryTechLabResearch),
      781 => Some(Self::FactoryTechLabResearch),
      782 => Some(Self::FactoryTechLabResearch),
      783 => Some(Self::FactoryTechLabResearch),
      784 => Some(Self::FactoryTechLabResearch),
      785 => Some(Self::FactoryTechLabResearch),
      786 => Some(Self::FactoryTechLabResearch),
      787 => Some(Self::FactoryTechLabResearch),
      788 => Some(Self::FactoryTechLabResearch),
      789 => Some(Self::FactoryTechLabResearch),
      769 => Some(Self::FactoryTechLabResearchCycloneResearchLockOnDamageUpgrade),
      767 => Some(Self::FactoryTechLabResearchResearchArmorPiercingRockets),
      768 => Some(Self::FactoryTechLabResearchResearchCycloneRapidFireLaunchers),
      764 => Some(Self::FactoryTechLabResearchResearchDrillClaws),
      761 => Some(Self::FactoryTechLabResearchResearchHighCapacityBarrels),
      765 => Some(Self::FactoryTechLabResearchResearchLockOnRangeUpgrade),
      766 => Some(Self::FactoryTechLabResearchResearchSmartServos),
      763 => Some(Self::FactoryTechLabResearchResearchTransformationServos),
      3307 => Some(Self::FactoryTechReactorMorph),
      3306 => Some(Self::FactoryTechReactorMorphTechLabFactory),
      590 => Some(Self::FactoryTrain),
      592 => Some(Self::FactoryTrain),
      593 => Some(Self::FactoryTrain),
      598 => Some(Self::FactoryTrain),
      599 => Some(Self::FactoryTrain),
      600 => Some(Self::FactoryTrain),
      601 => Some(Self::FactoryTrain),
      602 => Some(Self::FactoryTrain),
      603 => Some(Self::FactoryTrain),
      604 => Some(Self::FactoryTrain),
      605 => Some(Self::FactoryTrain),
      606 => Some(Self::FactoryTrain),
      607 => Some(Self::FactoryTrain),
      608 => Some(Self::FactoryTrain),
      609 => Some(Self::FactoryTrain),
      610 => Some(Self::FactoryTrain),
      611 => Some(Self::FactoryTrain),
      612 => Some(Self::FactoryTrain),
      613 => Some(Self::FactoryTrain),
      615 => Some(Self::FactoryTrain),
      616 => Some(Self::FactoryTrain),
      617 => Some(Self::FactoryTrain),
      618 => Some(Self::FactoryTrain),
      619 => Some(Self::FactoryTrain),
      597 => Some(Self::FactoryTrainBuildCyclone),
      595 => Some(Self::FactoryTrainHellion),
      596 => Some(Self::FactoryTrainHellionTank),
      591 => Some(Self::FactoryTrainSiegeTank),
      594 => Some(Self::FactoryTrainThor),
      614 => Some(Self::FactoryTrainWidowMine),
      140 => Some(Self::Feedback),
      141 => Some(Self::Feedback),
      405 => Some(Self::FighterMode),
      406 => Some(Self::FighterMode),
      48 => Some(Self::FleetBeaconResearch),
      49 => Some(Self::FleetBeaconResearch),
      50 => Some(Self::FleetBeaconResearch),
      51 => Some(Self::FleetBeaconResearch),
      52 => Some(Self::FleetBeaconResearch),
      53 => Some(Self::FleetBeaconResearch),
      54 => Some(Self::FleetBeaconResearch),
      55 => Some(Self::FleetBeaconResearch),
      56 => Some(Self::FleetBeaconResearch),
      57 => Some(Self::FleetBeaconResearch),
      58 => Some(Self::FleetBeaconResearch),
      59 => Some(Self::FleetBeaconResearch),
      60 => Some(Self::FleetBeaconResearch),
      61 => Some(Self::FleetBeaconResearch),
      62 => Some(Self::FleetBeaconResearch),
      63 => Some(Self::FleetBeaconResearch),
      64 => Some(Self::FleetBeaconResearch),
      65 => Some(Self::FleetBeaconResearch),
      66 => Some(Self::FleetBeaconResearch),
      67 => Some(Self::FleetBeaconResearch),
      68 => Some(Self::FleetBeaconResearch),
      69 => Some(Self::FleetBeaconResearch),
      70 => Some(Self::FleetBeaconResearch),
      71 => Some(Self::FleetBeaconResearch),
      72 => Some(Self::FleetBeaconResearch),
      73 => Some(Self::FleetBeaconResearch),
      46 => Some(Self::FleetBeaconResearchPhoenixRangeUpgrade),
      44 => Some(Self::FleetBeaconResearchResearchInterceptorLaunchSpeedUpgrade),
      45 => Some(Self::FleetBeaconResearchResearchInterceptorLaunchSpeedUpgrade),
      47 => Some(Self::FleetBeaconResearchTempestRangeUpgrade),
      1942 => Some(Self::FlyerShield),
      1943 => Some(Self::FlyerShield),
      1526 => Some(Self::ForceField),
      2987 => Some(Self::ForceFieldBeam),
      2988 => Some(Self::ForceFieldBeam),
      1527 => Some(Self::ForceFieldCancel),
      1071 => Some(Self::ForgeResearch),
      1072 => Some(Self::ForgeResearch),
      1073 => Some(Self::ForgeResearch),
      1074 => Some(Self::ForgeResearch),
      1075 => Some(Self::ForgeResearch),
      1076 => Some(Self::ForgeResearch),
      1077 => Some(Self::ForgeResearch),
      1078 => Some(Self::ForgeResearch),
      1079 => Some(Self::ForgeResearch),
      1080 => Some(Self::ForgeResearch),
      1081 => Some(Self::ForgeResearch),
      1082 => Some(Self::ForgeResearch),
      1083 => Some(Self::ForgeResearch),
      1084 => Some(Self::ForgeResearch),
      1085 => Some(Self::ForgeResearch),
      1086 => Some(Self::ForgeResearch),
      1087 => Some(Self::ForgeResearch),
      1088 => Some(Self::ForgeResearch),
      1089 => Some(Self::ForgeResearch),
      1090 => Some(Self::ForgeResearch),
      1091 => Some(Self::ForgeResearch),
      1065 => Some(Self::ForgeResearchProtossGroundArmorLevel1),
      1066 => Some(Self::ForgeResearchProtossGroundArmorLevel2),
      1067 => Some(Self::ForgeResearchProtossGroundArmorLevel3),
      1062 => Some(Self::ForgeResearchProtossGroundWeaponsLevel1),
      1063 => Some(Self::ForgeResearchProtossGroundWeaponsLevel2),
      1064 => Some(Self::ForgeResearchProtossGroundWeaponsLevel3),
      1068 => Some(Self::ForgeResearchProtossShieldsLevel1),
      1069 => Some(Self::ForgeResearchProtossShieldsLevel2),
      1070 => Some(Self::ForgeResearchProtossShieldsLevel3),
      1823 => Some(Self::Frenzy),
      1824 => Some(Self::Frenzy),
      74 => Some(Self::FungalGrowth),
      75 => Some(Self::FungalGrowth),
      1533 => Some(Self::FusionCoreResearch),
      1534 => Some(Self::FusionCoreResearch),
      1535 => Some(Self::FusionCoreResearch),
      1536 => Some(Self::FusionCoreResearch),
      1537 => Some(Self::FusionCoreResearch),
      1538 => Some(Self::FusionCoreResearch),
      1539 => Some(Self::FusionCoreResearch),
      1540 => Some(Self::FusionCoreResearch),
      1541 => Some(Self::FusionCoreResearch),
      1542 => Some(Self::FusionCoreResearch),
      1543 => Some(Self::FusionCoreResearch),
      1544 => Some(Self::FusionCoreResearch),
      1545 => Some(Self::FusionCoreResearch),
      1546 => Some(Self::FusionCoreResearch),
      1547 => Some(Self::FusionCoreResearch),
      1548 => Some(Self::FusionCoreResearch),
      1549 => Some(Self::FusionCoreResearch),
      1550 => Some(Self::FusionCoreResearch),
      1551 => Some(Self::FusionCoreResearch),
      1552 => Some(Self::FusionCoreResearch),
      1553 => Some(Self::FusionCoreResearch),
      1554 => Some(Self::FusionCoreResearch),
      1555 => Some(Self::FusionCoreResearch),
      1556 => Some(Self::FusionCoreResearch),
      1557 => Some(Self::FusionCoreResearch),
      1558 => Some(Self::FusionCoreResearch),
      1559 => Some(Self::FusionCoreResearch),
      1560 => Some(Self::FusionCoreResearch),
      1561 => Some(Self::FusionCoreResearch),
      1532 => Some(Self::FusionCoreResearchResearchBattlecruiserSpecializations),
      _ => None,
    }
  }
}
