
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum G {
  GatewayTrain,
  GatewayTrainDarkTemplar,
  GatewayTrainHighTemplar,
  GatewayTrainSentry,
  GatewayTrainStalker,
  GatewayTrainWarpInAdept,
  GatewayTrainZealot,
  GatherSpecialObject,
  GeneralAttack,
  GeneralBuildCreepTumor,
  GeneralCancelHoldFire,
  GeneralCloakOff,
  GeneralCloakOn,
  GeneralHoldFire,
  GeneralHoldPosition,
  GeneralMove,
  GeneralPatrol,
  GeneralRallyUnits,
  GeneralRallyWorkers,
  GeneralStimpack,
  GeneralUnloadUnit,
  GenerateCreep,
  GenerateCreepStopGenerateCreep,
  GhostAcademyResearch,
  GhostAcademyResearchResearchGhostEnergyUpgrade,
  GhostAcademyResearchResearchPersonalCloaking,
  GhostCloakCloakOff,
  GhostCloakCloakOnGhost,
  GhostHoldFire,
  GhostWeaponsFree,
  Grapple,
  GravitonBeam,
  GravitonBeamCancel,
  GravitonPrison,
  GuardianShield,
  GwaLearn,
  GwaLearnTestLearn,
}
impl G {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      918 => Some(Self::GatewayTrain),
      923 => Some(Self::GatewayTrain),
      924 => Some(Self::GatewayTrain),
      925 => Some(Self::GatewayTrain),
      926 => Some(Self::GatewayTrain),
      927 => Some(Self::GatewayTrain),
      928 => Some(Self::GatewayTrain),
      929 => Some(Self::GatewayTrain),
      930 => Some(Self::GatewayTrain),
      931 => Some(Self::GatewayTrain),
      932 => Some(Self::GatewayTrain),
      933 => Some(Self::GatewayTrain),
      934 => Some(Self::GatewayTrain),
      935 => Some(Self::GatewayTrain),
      936 => Some(Self::GatewayTrain),
      937 => Some(Self::GatewayTrain),
      938 => Some(Self::GatewayTrain),
      939 => Some(Self::GatewayTrain),
      940 => Some(Self::GatewayTrain),
      941 => Some(Self::GatewayTrain),
      942 => Some(Self::GatewayTrain),
      943 => Some(Self::GatewayTrain),
      944 => Some(Self::GatewayTrain),
      945 => Some(Self::GatewayTrain),
      920 => Some(Self::GatewayTrainDarkTemplar),
      919 => Some(Self::GatewayTrainHighTemplar),
      921 => Some(Self::GatewayTrainSentry),
      917 => Some(Self::GatewayTrainStalker),
      922 => Some(Self::GatewayTrainWarpInAdept),
      916 => Some(Self::GatewayTrainZealot),
      2915 => Some(Self::GatherSpecialObject),
      2916 => Some(Self::GatherSpecialObject),
      3674 => Some(Self::GeneralAttack),
      3691 => Some(Self::GeneralBuildCreepTumor),
      3689 => Some(Self::GeneralCancelHoldFire),
      3677 => Some(Self::GeneralCloakOff),
      3676 => Some(Self::GeneralCloakOn),
      3688 => Some(Self::GeneralHoldFire),
      3793 => Some(Self::GeneralHoldPosition),
      3794 => Some(Self::GeneralMove),
      3795 => Some(Self::GeneralPatrol),
      3673 => Some(Self::GeneralRallyUnits),
      3690 => Some(Self::GeneralRallyWorkers),
      3675 => Some(Self::GeneralStimpack),
      3796 => Some(Self::GeneralUnloadUnit),
      1692 => Some(Self::GenerateCreep),
      1693 => Some(Self::GenerateCreepStopGenerateCreep),
      822 => Some(Self::GhostAcademyResearch),
      823 => Some(Self::GhostAcademyResearch),
      824 => Some(Self::GhostAcademyResearch),
      825 => Some(Self::GhostAcademyResearch),
      826 => Some(Self::GhostAcademyResearch),
      827 => Some(Self::GhostAcademyResearch),
      828 => Some(Self::GhostAcademyResearch),
      829 => Some(Self::GhostAcademyResearch),
      830 => Some(Self::GhostAcademyResearch),
      831 => Some(Self::GhostAcademyResearch),
      832 => Some(Self::GhostAcademyResearch),
      833 => Some(Self::GhostAcademyResearch),
      834 => Some(Self::GhostAcademyResearch),
      835 => Some(Self::GhostAcademyResearch),
      836 => Some(Self::GhostAcademyResearch),
      837 => Some(Self::GhostAcademyResearch),
      838 => Some(Self::GhostAcademyResearch),
      839 => Some(Self::GhostAcademyResearch),
      840 => Some(Self::GhostAcademyResearch),
      841 => Some(Self::GhostAcademyResearch),
      842 => Some(Self::GhostAcademyResearch),
      843 => Some(Self::GhostAcademyResearch),
      844 => Some(Self::GhostAcademyResearch),
      845 => Some(Self::GhostAcademyResearch),
      846 => Some(Self::GhostAcademyResearch),
      847 => Some(Self::GhostAcademyResearch),
      848 => Some(Self::GhostAcademyResearch),
      849 => Some(Self::GhostAcademyResearch),
      821 => Some(Self::GhostAcademyResearchResearchGhostEnergyUpgrade),
      820 => Some(Self::GhostAcademyResearchResearchPersonalCloaking),
      383 => Some(Self::GhostCloakCloakOff),
      382 => Some(Self::GhostCloakCloakOnGhost),
      36 => Some(Self::GhostHoldFire),
      37 => Some(Self::GhostHoldFire),
      38 => Some(Self::GhostWeaponsFree),
      39 => Some(Self::GhostWeaponsFree),
      2501 => Some(Self::Grapple),
      2502 => Some(Self::Grapple),
      173 => Some(Self::GravitonBeam),
      174 => Some(Self::GravitonBeamCancel),
      3005 => Some(Self::GravitonPrison),
      3006 => Some(Self::GravitonPrison),
      76 => Some(Self::GuardianShield),
      77 => Some(Self::GuardianShield),
      3627 => Some(Self::GwaLearn),
      3628 => Some(Self::GwaLearn),
      3629 => Some(Self::GwaLearn),
      3630 => Some(Self::GwaLearn),
      3631 => Some(Self::GwaLearn),
      3632 => Some(Self::GwaLearn),
      3633 => Some(Self::GwaLearn),
      3634 => Some(Self::GwaLearn),
      3635 => Some(Self::GwaLearn),
      3636 => Some(Self::GwaLearn),
      3637 => Some(Self::GwaLearn),
      3638 => Some(Self::GwaLearn),
      3639 => Some(Self::GwaLearn),
      3640 => Some(Self::GwaLearn),
      3641 => Some(Self::GwaLearn),
      3642 => Some(Self::GwaLearn),
      3643 => Some(Self::GwaLearn),
      3644 => Some(Self::GwaLearn),
      3625 => Some(Self::GwaLearnTestLearn),
      3626 => Some(Self::GwaLearnTestLearn),
      _ => None,
    }
  }
}
