
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum H {
  HallucinationAdept,
  HallucinationAdeptWarpInAdept,
  HallucinationArchon,
  HallucinationColossus,
  HallucinationDisruptor,
  HallucinationDisruptorWarpinDisruptor,
  HallucinationHighTemplar,
  HallucinationImmortal,
  HallucinationOracle,
  HallucinationPhoenix,
  HallucinationProbe,
  HallucinationStalker,
  HallucinationVoidRay,
  HallucinationWarpPrism,
  HallucinationZealot,
  Halt,
  HangarQueue5Cancel,
  HangarQueue5CancelSlot,
  HarvestGather,
  HarvestReturn,
  Heal,
  HealMedicHeal,
  HealRedirect,
  HeliosCrashMorph,
  HerculesLand,
  HerculesLiftOff,
  HerculesTransport,
  HerculesTransportMedivacLoad,
  HerculesTransportMedivacUnloadAll,
  HerdInteract,
  HeroArmNuke,
  HeroArmNukeNukeArm,
  HeroNuclearStrikeCancel,
  HeroNuclearStrikeNukeCalldown,
  HoldFire,
  HoldFireStopSpecial,
  HutTransport,
  HutTransportHutLoad,
  HutTransportHutUnloadAll,
  HybridBlink,
  HybridBlinkZeratulBlink,
  HybridCPlasmaBlast,
  HybridFAoEStun,
  HydraliskDenResearch,
  HydraliskDenResearchEvolveGroovedSpines,
  HydraliskDenResearchEvolveMuscularAugments,
  HydraliskDenResearchResearchLurkerRange,
  HyperionYamatoSpecial,
  HyperionYamatoSpecialHyperionYamatoGun,
  Hyperjump,
}
impl H {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2392 => Some(Self::HallucinationAdept),
      2391 => Some(Self::HallucinationAdeptWarpInAdept),
      146 => Some(Self::HallucinationArchon),
      147 => Some(Self::HallucinationArchon),
      148 => Some(Self::HallucinationColossus),
      149 => Some(Self::HallucinationColossus),
      2390 => Some(Self::HallucinationDisruptor),
      2389 => Some(Self::HallucinationDisruptorWarpinDisruptor),
      150 => Some(Self::HallucinationHighTemplar),
      151 => Some(Self::HallucinationHighTemplar),
      152 => Some(Self::HallucinationImmortal),
      153 => Some(Self::HallucinationImmortal),
      2114 => Some(Self::HallucinationOracle),
      2115 => Some(Self::HallucinationOracle),
      154 => Some(Self::HallucinationPhoenix),
      155 => Some(Self::HallucinationPhoenix),
      156 => Some(Self::HallucinationProbe),
      157 => Some(Self::HallucinationProbe),
      158 => Some(Self::HallucinationStalker),
      159 => Some(Self::HallucinationStalker),
      160 => Some(Self::HallucinationVoidRay),
      161 => Some(Self::HallucinationVoidRay),
      162 => Some(Self::HallucinationWarpPrism),
      163 => Some(Self::HallucinationWarpPrism),
      164 => Some(Self::HallucinationZealot),
      165 => Some(Self::HallucinationZealot),
      3660 => Some(Self::Halt),
      1038 => Some(Self::HangarQueue5Cancel),
      1039 => Some(Self::HangarQueue5CancelSlot),
      3666 => Some(Self::HarvestGather),
      3667 => Some(Self::HarvestReturn),
      2751 => Some(Self::Heal),
      2750 => Some(Self::HealMedicHeal),
      2835 => Some(Self::HealRedirect),
      3395 => Some(Self::HeliosCrashMorph),
      3396 => Some(Self::HeliosCrashMorph),
      3356 => Some(Self::HerculesLand),
      3357 => Some(Self::HerculesLand),
      3354 => Some(Self::HerculesLiftOff),
      3355 => Some(Self::HerculesLiftOff),
      2943 => Some(Self::HerculesTransport),
      2945 => Some(Self::HerculesTransport),
      2946 => Some(Self::HerculesTransport),
      2942 => Some(Self::HerculesTransportMedivacLoad),
      2944 => Some(Self::HerculesTransportMedivacUnloadAll),
      1821 => Some(Self::HerdInteract),
      1822 => Some(Self::HerdInteract),
      3144 => Some(Self::HeroArmNuke),
      3145 => Some(Self::HeroArmNuke),
      3146 => Some(Self::HeroArmNuke),
      3147 => Some(Self::HeroArmNuke),
      3148 => Some(Self::HeroArmNuke),
      3149 => Some(Self::HeroArmNuke),
      3150 => Some(Self::HeroArmNuke),
      3151 => Some(Self::HeroArmNuke),
      3152 => Some(Self::HeroArmNuke),
      3153 => Some(Self::HeroArmNuke),
      3154 => Some(Self::HeroArmNuke),
      3155 => Some(Self::HeroArmNuke),
      3156 => Some(Self::HeroArmNuke),
      3157 => Some(Self::HeroArmNuke),
      3158 => Some(Self::HeroArmNuke),
      3159 => Some(Self::HeroArmNuke),
      3160 => Some(Self::HeroArmNuke),
      3161 => Some(Self::HeroArmNuke),
      3162 => Some(Self::HeroArmNuke),
      3143 => Some(Self::HeroArmNukeNukeArm),
      3164 => Some(Self::HeroNuclearStrikeCancel),
      3163 => Some(Self::HeroNuclearStrikeNukeCalldown),
      11 => Some(Self::HoldFire),
      12 => Some(Self::HoldFire),
      13 => Some(Self::HoldFire),
      14 => Some(Self::HoldFire),
      15 => Some(Self::HoldFire),
      10 => Some(Self::HoldFireStopSpecial),
      2768 => Some(Self::HutTransport),
      2769 => Some(Self::HutTransport),
      2770 => Some(Self::HutTransport),
      2766 => Some(Self::HutTransportHutLoad),
      2767 => Some(Self::HutTransportHutUnloadAll),
      3140 => Some(Self::HybridBlink),
      3139 => Some(Self::HybridBlinkZeratulBlink),
      3141 => Some(Self::HybridCPlasmaBlast),
      3142 => Some(Self::HybridCPlasmaBlast),
      3013 => Some(Self::HybridFAoEStun),
      3014 => Some(Self::HybridFAoEStun),
      1284 => Some(Self::HydraliskDenResearch),
      1285 => Some(Self::HydraliskDenResearch),
      1287 => Some(Self::HydraliskDenResearch),
      1288 => Some(Self::HydraliskDenResearch),
      1289 => Some(Self::HydraliskDenResearch),
      1290 => Some(Self::HydraliskDenResearch),
      1291 => Some(Self::HydraliskDenResearch),
      1292 => Some(Self::HydraliskDenResearch),
      1293 => Some(Self::HydraliskDenResearch),
      1294 => Some(Self::HydraliskDenResearch),
      1295 => Some(Self::HydraliskDenResearch),
      1296 => Some(Self::HydraliskDenResearch),
      1297 => Some(Self::HydraliskDenResearch),
      1298 => Some(Self::HydraliskDenResearch),
      1299 => Some(Self::HydraliskDenResearch),
      1300 => Some(Self::HydraliskDenResearch),
      1301 => Some(Self::HydraliskDenResearch),
      1302 => Some(Self::HydraliskDenResearch),
      1303 => Some(Self::HydraliskDenResearch),
      1304 => Some(Self::HydraliskDenResearch),
      1305 => Some(Self::HydraliskDenResearch),
      1306 => Some(Self::HydraliskDenResearch),
      1307 => Some(Self::HydraliskDenResearch),
      1308 => Some(Self::HydraliskDenResearch),
      1309 => Some(Self::HydraliskDenResearch),
      1310 => Some(Self::HydraliskDenResearch),
      1311 => Some(Self::HydraliskDenResearch),
      1282 => Some(Self::HydraliskDenResearchEvolveGroovedSpines),
      1283 => Some(Self::HydraliskDenResearchEvolveMuscularAugments),
      1286 => Some(Self::HydraliskDenResearchResearchLurkerRange),
      2955 => Some(Self::HyperionYamatoSpecial),
      2954 => Some(Self::HyperionYamatoSpecialHyperionYamatoGun),
      2358 => Some(Self::Hyperjump),
      2359 => Some(Self::Hyperjump),
      _ => None,
    }
  }
}
