
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum I {
  ImmortalOverload,
  Impale,
  Implosion,
  InfestableHutTransport,
  InfestableHutTransportHutLoad,
  InfestableHutTransportHutUnloadAll,
  InfestationPitResearch,
  InfestationPitResearchEvolveInfestorEnergyUpgrade,
  InfestationPitResearchResearchLocustLifetimeIncrease,
  InfestationPitResearchResearchNeuralParasite,
  InfestedMonsterTrain,
  InfestedMonsterTrainInfestedAbomination,
  InfestedMonsterTrainInfestedCivilian,
  InfestedMonsterTrainInfestedTerranCampaign,
  InfestedTerrans,
  InfestedTerransLayEgg,
  InfestedVentSpawnBroodLord,
  InfestedVentSpawnCorruptor,
  InfestedVentSpawnMutalisk,
  InfestedVentSpawnMutaliskLeviathanSpawnMutalisk,
  InfestorEnsnare,
  InvulnerabilityShield,
  Irradiate,
  IrradiateCancel,
}
impl I {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2328 => Some(Self::ImmortalOverload),
      2329 => Some(Self::ImmortalOverload),
      2348 => Some(Self::Impale),
      2349 => Some(Self::Impale),
      3007 => Some(Self::Implosion),
      3008 => Some(Self::Implosion),
      2958 => Some(Self::InfestableHutTransport),
      2959 => Some(Self::InfestableHutTransport),
      2960 => Some(Self::InfestableHutTransport),
      2956 => Some(Self::InfestableHutTransportHutLoad),
      2957 => Some(Self::InfestableHutTransportHutUnloadAll),
      1452 => Some(Self::InfestationPitResearch),
      1453 => Some(Self::InfestationPitResearch),
      1457 => Some(Self::InfestationPitResearch),
      1458 => Some(Self::InfestationPitResearch),
      1459 => Some(Self::InfestationPitResearch),
      1460 => Some(Self::InfestationPitResearch),
      1461 => Some(Self::InfestationPitResearch),
      1462 => Some(Self::InfestationPitResearch),
      1463 => Some(Self::InfestationPitResearch),
      1464 => Some(Self::InfestationPitResearch),
      1465 => Some(Self::InfestationPitResearch),
      1466 => Some(Self::InfestationPitResearch),
      1467 => Some(Self::InfestationPitResearch),
      1468 => Some(Self::InfestationPitResearch),
      1469 => Some(Self::InfestationPitResearch),
      1470 => Some(Self::InfestationPitResearch),
      1471 => Some(Self::InfestationPitResearch),
      1472 => Some(Self::InfestationPitResearch),
      1473 => Some(Self::InfestationPitResearch),
      1474 => Some(Self::InfestationPitResearch),
      1475 => Some(Self::InfestationPitResearch),
      1476 => Some(Self::InfestationPitResearch),
      1477 => Some(Self::InfestationPitResearch),
      1478 => Some(Self::InfestationPitResearch),
      1479 => Some(Self::InfestationPitResearch),
      1480 => Some(Self::InfestationPitResearch),
      1481 => Some(Self::InfestationPitResearch),
      1454 => Some(Self::InfestationPitResearchEvolveInfestorEnergyUpgrade),
      1456 => Some(Self::InfestationPitResearchResearchLocustLifetimeIncrease),
      1455 => Some(Self::InfestationPitResearchResearchNeuralParasite),
      3247 => Some(Self::InfestedMonsterTrain),
      3248 => Some(Self::InfestedMonsterTrain),
      3249 => Some(Self::InfestedMonsterTrain),
      3250 => Some(Self::InfestedMonsterTrain),
      3251 => Some(Self::InfestedMonsterTrain),
      3252 => Some(Self::InfestedMonsterTrain),
      3253 => Some(Self::InfestedMonsterTrain),
      3254 => Some(Self::InfestedMonsterTrain),
      3255 => Some(Self::InfestedMonsterTrain),
      3256 => Some(Self::InfestedMonsterTrain),
      3257 => Some(Self::InfestedMonsterTrain),
      3258 => Some(Self::InfestedMonsterTrain),
      3259 => Some(Self::InfestedMonsterTrain),
      3260 => Some(Self::InfestedMonsterTrain),
      3261 => Some(Self::InfestedMonsterTrain),
      3262 => Some(Self::InfestedMonsterTrain),
      3263 => Some(Self::InfestedMonsterTrain),
      3264 => Some(Self::InfestedMonsterTrain),
      3265 => Some(Self::InfestedMonsterTrain),
      3266 => Some(Self::InfestedMonsterTrain),
      3267 => Some(Self::InfestedMonsterTrain),
      3268 => Some(Self::InfestedMonsterTrain),
      3269 => Some(Self::InfestedMonsterTrain),
      3270 => Some(Self::InfestedMonsterTrain),
      3271 => Some(Self::InfestedMonsterTrain),
      3272 => Some(Self::InfestedMonsterTrain),
      3273 => Some(Self::InfestedMonsterTrain),
      3246 => Some(Self::InfestedMonsterTrainInfestedAbomination),
      3244 => Some(Self::InfestedMonsterTrainInfestedCivilian),
      3245 => Some(Self::InfestedMonsterTrainInfestedTerranCampaign),
      247 => Some(Self::InfestedTerrans),
      248 => Some(Self::InfestedTerrans),
      1829 => Some(Self::InfestedTerransLayEgg),
      1830 => Some(Self::InfestedTerransLayEgg),
      2846 => Some(Self::InfestedVentSpawnBroodLord),
      2847 => Some(Self::InfestedVentSpawnBroodLord),
      2844 => Some(Self::InfestedVentSpawnCorruptor),
      2845 => Some(Self::InfestedVentSpawnCorruptor),
      2851 => Some(Self::InfestedVentSpawnMutalisk),
      2850 => Some(Self::InfestedVentSpawnMutaliskLeviathanSpawnMutalisk),
      3763 => Some(Self::InfestorEnsnare),
      3764 => Some(Self::InfestorEnsnare),
      2142 => Some(Self::InvulnerabilityShield),
      2143 => Some(Self::InvulnerabilityShield),
      2848 => Some(Self::Irradiate),
      2849 => Some(Self::IrradiateCancel),
      _ => None,
    }
  }
}
