
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum L {
  LairResearch,
  LairResearchEvolveVentralSacks,
  LairResearchOverlordspeed,
  LairResearchResearchBurrow,
  Land,
  LarvaTrain,
  LarvaTrainCorruptor,
  LarvaTrainDrone,
  LarvaTrainHydralisk,
  LarvaTrainInfestor,
  LarvaTrainMutalisk,
  LarvaTrainOverlord,
  LarvaTrainRoach,
  LarvaTrainSwarmHostMp,
  LarvaTrainUltralisk,
  LarvaTrainViper,
  LarvaTrainZergling,
  LaunchInterceptors,
  Leech,
  LeechResources,
  LeechResourcesCancel,
  LeviathanSpawnBroodLord,
  LeviathanSpawnMutalisk,
  LiberatorAaTarget,
  LiberatorAaTargetLiberatorAaMode,
  LiberatorAgTarget,
  LiberatorAgTargetLiberatorAgMode,
  LiberatorMorphtoAa,
  LiberatorMorphtoAaLiberatorAaMode,
  LiberatorMorphtoAg,
  LiberatorMorphtoAgLiberatorAgMode,
  LibraryDown,
  LibraryUp,
  Lift,
  LightBridgeOff,
  LightBridgeOffTopRight,
  LightBridgeOn,
  LightBridgeOnTopRight,
  LightningBomb,
  LightofAiur,
  LockOn,
  LockOnAir,
  LockOnCancel,
  LocustMpFlyingMorphToGround,
  LocustMpFlyingMorphToGroundLocustMpFlyingSwoop,
  LocustMpFlyingSwoop,
  LocustMpFlyingSwoopAttack,
  LocustMpMorphToAir,
  LocustMpMorphToAirLocustMpFlyingSwoop,
  LocustTrain,
  LocustTrainSwarmHost,
  LokiMissilePods,
  LokiUndock,
  LokiUndockLift,
  LokiYamato,
  LokiYamatoLokiYamatoGun,
  LurkerAspect,
  LurkerAspectCancel,
  LurkerAspectFromHydraliskBurrowedCancel,
  LurkerAspectFromHydraliskBurrowedLurkerFromHydraliskBurrowed,
  LurkerAspectMpCancel,
  LurkerAspectMpFromHydraliskBurrowedCancel,
  LurkerAspectMpFromHydraliskBurrowedLurkerMpFromHydraliskBurrowed,
  LurkerAspectMpLurkerMp,
  LurkerDenResearch,
  LurkerDenResearchEvolveDiggingClaws,
  LurkerHoldFire,
  LurkerRemoveHoldFire,
  LurkerRemoveHoldFireLurkerCancelHoldFire,
}
impl L {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      1222 => Some(Self::LairResearch),
      1226 => Some(Self::LairResearch),
      1227 => Some(Self::LairResearch),
      1228 => Some(Self::LairResearch),
      1229 => Some(Self::LairResearch),
      1230 => Some(Self::LairResearch),
      1231 => Some(Self::LairResearch),
      1232 => Some(Self::LairResearch),
      1233 => Some(Self::LairResearch),
      1234 => Some(Self::LairResearch),
      1235 => Some(Self::LairResearch),
      1236 => Some(Self::LairResearch),
      1237 => Some(Self::LairResearch),
      1238 => Some(Self::LairResearch),
      1239 => Some(Self::LairResearch),
      1240 => Some(Self::LairResearch),
      1241 => Some(Self::LairResearch),
      1242 => Some(Self::LairResearch),
      1243 => Some(Self::LairResearch),
      1244 => Some(Self::LairResearch),
      1245 => Some(Self::LairResearch),
      1246 => Some(Self::LairResearch),
      1247 => Some(Self::LairResearch),
      1248 => Some(Self::LairResearch),
      1249 => Some(Self::LairResearch),
      1250 => Some(Self::LairResearch),
      1251 => Some(Self::LairResearch),
      1224 => Some(Self::LairResearchEvolveVentralSacks),
      1223 => Some(Self::LairResearchOverlordspeed),
      1225 => Some(Self::LairResearchResearchBurrow),
      3678 => Some(Self::Land),
      1347 => Some(Self::LarvaTrain),
      1349 => Some(Self::LarvaTrain),
      1350 => Some(Self::LarvaTrain),
      1355 => Some(Self::LarvaTrain),
      1357 => Some(Self::LarvaTrain),
      1358 => Some(Self::LarvaTrain),
      1359 => Some(Self::LarvaTrain),
      1360 => Some(Self::LarvaTrain),
      1361 => Some(Self::LarvaTrain),
      1362 => Some(Self::LarvaTrain),
      1363 => Some(Self::LarvaTrain),
      1364 => Some(Self::LarvaTrain),
      1365 => Some(Self::LarvaTrain),
      1366 => Some(Self::LarvaTrain),
      1367 => Some(Self::LarvaTrain),
      1368 => Some(Self::LarvaTrain),
      1369 => Some(Self::LarvaTrain),
      1370 => Some(Self::LarvaTrain),
      1371 => Some(Self::LarvaTrain),
      1353 => Some(Self::LarvaTrainCorruptor),
      1342 => Some(Self::LarvaTrainDrone),
      1345 => Some(Self::LarvaTrainHydralisk),
      1352 => Some(Self::LarvaTrainInfestor),
      1346 => Some(Self::LarvaTrainMutalisk),
      1344 => Some(Self::LarvaTrainOverlord),
      1351 => Some(Self::LarvaTrainRoach),
      1356 => Some(Self::LarvaTrainSwarmHostMp),
      1348 => Some(Self::LarvaTrainUltralisk),
      1354 => Some(Self::LarvaTrainViper),
      1343 => Some(Self::LarvaTrainZergling),
      2702 => Some(Self::LaunchInterceptors),
      2703 => Some(Self::LaunchInterceptors),
      179 => Some(Self::Leech),
      180 => Some(Self::Leech),
      1986 => Some(Self::LeechResources),
      1987 => Some(Self::LeechResourcesCancel),
      2773 => Some(Self::LeviathanSpawnBroodLord),
      2774 => Some(Self::LeviathanSpawnBroodLord),
      2901 => Some(Self::LeviathanSpawnMutalisk),
      2902 => Some(Self::LeviathanSpawnMutalisk),
      2561 => Some(Self::LiberatorAaTarget),
      2560 => Some(Self::LiberatorAaTargetLiberatorAaMode),
      2559 => Some(Self::LiberatorAgTarget),
      2558 => Some(Self::LiberatorAgTargetLiberatorAgMode),
      2557 => Some(Self::LiberatorMorphtoAa),
      2556 => Some(Self::LiberatorMorphtoAaLiberatorAaMode),
      2555 => Some(Self::LiberatorMorphtoAg),
      2554 => Some(Self::LiberatorMorphtoAgLiberatorAgMode),
      3362 => Some(Self::LibraryDown),
      3363 => Some(Self::LibraryDown),
      3364 => Some(Self::LibraryUp),
      3365 => Some(Self::LibraryUp),
      3679 => Some(Self::Lift),
      3358 => Some(Self::LightBridgeOff),
      3359 => Some(Self::LightBridgeOff),
      3647 => Some(Self::LightBridgeOffTopRight),
      3648 => Some(Self::LightBridgeOffTopRight),
      3360 => Some(Self::LightBridgeOn),
      3361 => Some(Self::LightBridgeOn),
      3649 => Some(Self::LightBridgeOnTopRight),
      3650 => Some(Self::LightBridgeOnTopRight),
      2499 => Some(Self::LightningBomb),
      2500 => Some(Self::LightningBomb),
      2366 => Some(Self::LightofAiur),
      2367 => Some(Self::LightofAiur),
      2350 => Some(Self::LockOn),
      2351 => Some(Self::LockOn),
      2352 => Some(Self::LockOnAir),
      2353 => Some(Self::LockOnAir),
      2354 => Some(Self::LockOnCancel),
      2355 => Some(Self::LockOnCancel),
      2384 => Some(Self::LocustMpFlyingMorphToGround),
      2383 => Some(Self::LocustMpFlyingMorphToGroundLocustMpFlyingSwoop),
      2387 => Some(Self::LocustMpFlyingSwoop),
      2388 => Some(Self::LocustMpFlyingSwoop),
      2706 => Some(Self::LocustMpFlyingSwoopAttack),
      2707 => Some(Self::LocustMpFlyingSwoopAttack),
      2386 => Some(Self::LocustMpMorphToAir),
      2385 => Some(Self::LocustMpMorphToAirLocustMpFlyingSwoop),
      1945 => Some(Self::LocustTrain),
      1946 => Some(Self::LocustTrain),
      1947 => Some(Self::LocustTrain),
      1948 => Some(Self::LocustTrain),
      1949 => Some(Self::LocustTrain),
      1950 => Some(Self::LocustTrain),
      1951 => Some(Self::LocustTrain),
      1952 => Some(Self::LocustTrain),
      1953 => Some(Self::LocustTrain),
      1954 => Some(Self::LocustTrain),
      1955 => Some(Self::LocustTrain),
      1956 => Some(Self::LocustTrain),
      1957 => Some(Self::LocustTrain),
      1958 => Some(Self::LocustTrain),
      1959 => Some(Self::LocustTrain),
      1960 => Some(Self::LocustTrain),
      1961 => Some(Self::LocustTrain),
      1962 => Some(Self::LocustTrain),
      1963 => Some(Self::LocustTrain),
      1964 => Some(Self::LocustTrain),
      1965 => Some(Self::LocustTrain),
      1966 => Some(Self::LocustTrain),
      1967 => Some(Self::LocustTrain),
      1968 => Some(Self::LocustTrain),
      1969 => Some(Self::LocustTrain),
      1970 => Some(Self::LocustTrain),
      1971 => Some(Self::LocustTrain),
      1972 => Some(Self::LocustTrain),
      1973 => Some(Self::LocustTrain),
      1944 => Some(Self::LocustTrainSwarmHost),
      2764 => Some(Self::LokiMissilePods),
      2765 => Some(Self::LokiMissilePods),
      2920 => Some(Self::LokiUndock),
      2919 => Some(Self::LokiUndockLift),
      3189 => Some(Self::LokiYamato),
      3188 => Some(Self::LokiYamatoLokiYamatoGun),
      2752 => Some(Self::LurkerAspect),
      2753 => Some(Self::LurkerAspectCancel),
      2837 => Some(Self::LurkerAspectFromHydraliskBurrowedCancel),
      2836 => Some(Self::LurkerAspectFromHydraliskBurrowedLurkerFromHydraliskBurrowed),
      2107 => Some(Self::LurkerAspectMpCancel),
      2105 => Some(Self::LurkerAspectMpFromHydraliskBurrowedCancel),
      2104 => Some(Self::LurkerAspectMpFromHydraliskBurrowedLurkerMpFromHydraliskBurrowed),
      2106 => Some(Self::LurkerAspectMpLurkerMp),
      3710 => Some(Self::LurkerDenResearch),
      3711 => Some(Self::LurkerDenResearch),
      3712 => Some(Self::LurkerDenResearch),
      3713 => Some(Self::LurkerDenResearch),
      3714 => Some(Self::LurkerDenResearch),
      3715 => Some(Self::LurkerDenResearch),
      3716 => Some(Self::LurkerDenResearch),
      3717 => Some(Self::LurkerDenResearch),
      3718 => Some(Self::LurkerDenResearch),
      3719 => Some(Self::LurkerDenResearch),
      3720 => Some(Self::LurkerDenResearch),
      3721 => Some(Self::LurkerDenResearch),
      3722 => Some(Self::LurkerDenResearch),
      3723 => Some(Self::LurkerDenResearch),
      3724 => Some(Self::LurkerDenResearch),
      3725 => Some(Self::LurkerDenResearch),
      3726 => Some(Self::LurkerDenResearch),
      3727 => Some(Self::LurkerDenResearch),
      3728 => Some(Self::LurkerDenResearch),
      3729 => Some(Self::LurkerDenResearch),
      3730 => Some(Self::LurkerDenResearch),
      3731 => Some(Self::LurkerDenResearch),
      3732 => Some(Self::LurkerDenResearch),
      3733 => Some(Self::LurkerDenResearch),
      3734 => Some(Self::LurkerDenResearch),
      3735 => Some(Self::LurkerDenResearch),
      3736 => Some(Self::LurkerDenResearch),
      3737 => Some(Self::LurkerDenResearch),
      3738 => Some(Self::LurkerDenResearch),
      3709 => Some(Self::LurkerDenResearchEvolveDiggingClaws),
      2550 => Some(Self::LurkerHoldFire),
      2551 => Some(Self::LurkerHoldFire),
      2553 => Some(Self::LurkerRemoveHoldFire),
      2552 => Some(Self::LurkerRemoveHoldFireLurkerCancelHoldFire),
      _ => None,
    }
  }
}
