
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum M {
  MakeVultureSpiderMines,
  MakeVultureSpiderMinesSpiderMineReplenish,
  MassRecall,
  MassiveKnockover,
  MaxiumThrust,
  MaxiumThrustMaximumThrust,
  MedivacDoubleBeamHeal,
  MedivacHeal,
  MedivacSpeedBoost,
  MedivacTransport,
  MedivacTransportMedivacLoad,
  MedivacTransportMedivacUnloadAll,
  MercCompoundResearch,
  MercCompoundResearchReaperSpeed,
  MergeableCancel,
  MetalGateDiagonalBlur,
  MetalGateDiagonalBlurGateClose,
  MetalGateDiagonalBlurLowered,
  MetalGateDiagonalBlurLoweredGateOpen,
  MetalGateDiagonalUlbr,
  MetalGateDiagonalUlbrGateClose,
  MetalGateDiagonalUlbrLowered,
  MetalGateDiagonalUlbrLoweredGateOpen,
  MetalGateStraightHorizontal,
  MetalGateStraightHorizontalBf,
  MetalGateStraightHorizontalBfGateClose,
  MetalGateStraightHorizontalBfLowered,
  MetalGateStraightHorizontalBfLoweredGateOpen,
  MetalGateStraightHorizontalGateClose,
  MetalGateStraightHorizontalLowered,
  MetalGateStraightHorizontalLoweredGateOpen,
  MetalGateStraightVertical,
  MetalGateStraightVerticalGateClose,
  MetalGateStraightVerticalLf,
  MetalGateStraightVerticalLfGateClose,
  MetalGateStraightVerticalLfLowered,
  MetalGateStraightVerticalLfLoweredGateOpen,
  MetalGateStraightVerticalLowered,
  MetalGateStraightVerticalLoweredGateOpen,
  MindBlast,
  MindControl,
  MissilePods,
  MorphBackToGateway,
  MorphBackToGatewayCancel,
  MorphToBroodLord,
  MorphToBroodLordCancel,
  MorphToCollapsiblePurifierTowerDebris,
  MorphToCollapsiblePurifierTowerDebrisCancel,
  MorphToCollapsibleRockTowerDebris,
  MorphToCollapsibleRockTowerDebrisCancel,
  MorphToCollapsibleRockTowerDebrisRampLeft,
  MorphToCollapsibleRockTowerDebrisRampLeftCancel,
  MorphToCollapsibleRockTowerDebrisRampRight,
  MorphToCollapsibleRockTowerDebrisRampRightCancel,
  MorphToCollapsibleTerranTowerDebris,
  MorphToCollapsibleTerranTowerDebrisCancel,
  MorphToCollapsibleTerranTowerDebrisRampLeft,
  MorphToCollapsibleTerranTowerDebrisRampLeftCancel,
  MorphToCollapsibleTerranTowerDebrisRampRight,
  MorphToCollapsibleTerranTowerDebrisRampRightCancel,
  MorphToDevourerMp,
  MorphToDevourerMpCancel,
  MorphToGhostAlternate,
  MorphToGhostAlternateMove,
  MorphToGhostNova,
  MorphToGhostNovaMove,
  MorphToGuardianMp,
  MorphToGuardianMpCancel,
  MorphToHellion,
  MorphToHellionTank,
  MorphToInfestedCivilian,
  MorphToInfestedTerran,
  MorphToInfestedTerranInfestedTerrans,
  MorphToLurkerCancel,
  MorphToLurkerLurkerMp,
  MorphToMothership,
  MorphToMothershipCancelMothershipMorph,
  MorphToOverseer,
  MorphToOverseerCancel,
  MorphToRavager,
  MorphToRavagerCancel,
  MorphToSwarmHostBurrowedMp,
  MorphToSwarmHostBurrowedMpCancel,
  MorphToSwarmHostMp,
  MorphToTechReactor,
  MorphToTransportOverlordCancel,
  MorphToTransportOverlordMorphtoOverlordTransport,
  MorphZerglingToBaneling,
  MothershipCoreEnergize,
  MothershipCoreEnergizeCancel,
  MothershipCoreMassRecall,
  MothershipCorePurifyNexus,
  MothershipCorePurifyNexusCancel,
  MothershipCorePurifyNexusMothershipCoreWeapon,
  MothershipCoreTeleport,
  MothershipCoreWeapon,
  MothershipCoreWeaponMothershipStasis,
  MothershipMassRecall,
  MothershipStasis,
  MothershipStasisCancel,
  Move,
  MoveAcquireMove,
  MoveMoveHoldPosition,
  MoveMovePatrol,
  MoveTurn,
  MuleGather,
  MuleGatherGatherMule,
  MuleGatherReturnCargo,
  MuleRepair,
}
impl M {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2853 => Some(Self::MakeVultureSpiderMines),
      2854 => Some(Self::MakeVultureSpiderMines),
      2855 => Some(Self::MakeVultureSpiderMines),
      2856 => Some(Self::MakeVultureSpiderMines),
      2857 => Some(Self::MakeVultureSpiderMines),
      2858 => Some(Self::MakeVultureSpiderMines),
      2859 => Some(Self::MakeVultureSpiderMines),
      2860 => Some(Self::MakeVultureSpiderMines),
      2861 => Some(Self::MakeVultureSpiderMines),
      2862 => Some(Self::MakeVultureSpiderMines),
      2863 => Some(Self::MakeVultureSpiderMines),
      2864 => Some(Self::MakeVultureSpiderMines),
      2865 => Some(Self::MakeVultureSpiderMines),
      2866 => Some(Self::MakeVultureSpiderMines),
      2867 => Some(Self::MakeVultureSpiderMines),
      2868 => Some(Self::MakeVultureSpiderMines),
      2869 => Some(Self::MakeVultureSpiderMines),
      2870 => Some(Self::MakeVultureSpiderMines),
      2871 => Some(Self::MakeVultureSpiderMines),
      2852 => Some(Self::MakeVultureSpiderMinesSpiderMineReplenish),
      142 => Some(Self::MassRecall),
      143 => Some(Self::MassRecall),
      2093 => Some(Self::MassiveKnockover),
      2094 => Some(Self::MassiveKnockover),
      2007 => Some(Self::MaxiumThrust),
      2006 => Some(Self::MaxiumThrustMaximumThrust),
      2872 => Some(Self::MedivacDoubleBeamHeal),
      2873 => Some(Self::MedivacDoubleBeamHeal),
      386 => Some(Self::MedivacHeal),
      387 => Some(Self::MedivacHeal),
      2116 => Some(Self::MedivacSpeedBoost),
      2117 => Some(Self::MedivacSpeedBoost),
      395 => Some(Self::MedivacTransport),
      397 => Some(Self::MedivacTransport),
      398 => Some(Self::MedivacTransport),
      394 => Some(Self::MedivacTransportMedivacLoad),
      396 => Some(Self::MedivacTransportMedivacUnloadAll),
      680 => Some(Self::MercCompoundResearch),
      681 => Some(Self::MercCompoundResearch),
      682 => Some(Self::MercCompoundResearch),
      684 => Some(Self::MercCompoundResearch),
      685 => Some(Self::MercCompoundResearch),
      686 => Some(Self::MercCompoundResearch),
      687 => Some(Self::MercCompoundResearch),
      688 => Some(Self::MercCompoundResearch),
      689 => Some(Self::MercCompoundResearch),
      690 => Some(Self::MercCompoundResearch),
      691 => Some(Self::MercCompoundResearch),
      692 => Some(Self::MercCompoundResearch),
      693 => Some(Self::MercCompoundResearch),
      694 => Some(Self::MercCompoundResearch),
      695 => Some(Self::MercCompoundResearch),
      696 => Some(Self::MercCompoundResearch),
      697 => Some(Self::MercCompoundResearch),
      698 => Some(Self::MercCompoundResearch),
      699 => Some(Self::MercCompoundResearch),
      700 => Some(Self::MercCompoundResearch),
      701 => Some(Self::MercCompoundResearch),
      702 => Some(Self::MercCompoundResearch),
      703 => Some(Self::MercCompoundResearch),
      704 => Some(Self::MercCompoundResearch),
      705 => Some(Self::MercCompoundResearch),
      706 => Some(Self::MercCompoundResearch),
      707 => Some(Self::MercCompoundResearch),
      708 => Some(Self::MercCompoundResearch),
      709 => Some(Self::MercCompoundResearch),
      683 => Some(Self::MercCompoundResearchReaperSpeed),
      1411 => Some(Self::MergeableCancel),
      3582 => Some(Self::MetalGateDiagonalBlur),
      3581 => Some(Self::MetalGateDiagonalBlurGateClose),
      3570 => Some(Self::MetalGateDiagonalBlurLowered),
      3569 => Some(Self::MetalGateDiagonalBlurLoweredGateOpen),
      3584 => Some(Self::MetalGateDiagonalUlbr),
      3583 => Some(Self::MetalGateDiagonalUlbrGateClose),
      3572 => Some(Self::MetalGateDiagonalUlbrLowered),
      3571 => Some(Self::MetalGateDiagonalUlbrLoweredGateOpen),
      3588 => Some(Self::MetalGateStraightHorizontal),
      3586 => Some(Self::MetalGateStraightHorizontalBf),
      3585 => Some(Self::MetalGateStraightHorizontalBfGateClose),
      3574 => Some(Self::MetalGateStraightHorizontalBfLowered),
      3573 => Some(Self::MetalGateStraightHorizontalBfLoweredGateOpen),
      3587 => Some(Self::MetalGateStraightHorizontalGateClose),
      3576 => Some(Self::MetalGateStraightHorizontalLowered),
      3575 => Some(Self::MetalGateStraightHorizontalLoweredGateOpen),
      3592 => Some(Self::MetalGateStraightVertical),
      3591 => Some(Self::MetalGateStraightVerticalGateClose),
      3590 => Some(Self::MetalGateStraightVerticalLf),
      3589 => Some(Self::MetalGateStraightVerticalLfGateClose),
      3578 => Some(Self::MetalGateStraightVerticalLfLowered),
      3577 => Some(Self::MetalGateStraightVerticalLfLoweredGateOpen),
      3580 => Some(Self::MetalGateStraightVerticalLowered),
      3579 => Some(Self::MetalGateStraightVerticalLoweredGateOpen),
      2921 => Some(Self::MindBlast),
      2922 => Some(Self::MindBlast),
      2874 => Some(Self::MindControl),
      2875 => Some(Self::MindControl),
      2762 => Some(Self::MissilePods),
      2763 => Some(Self::MissilePods),
      1520 => Some(Self::MorphBackToGateway),
      1521 => Some(Self::MorphBackToGatewayCancel),
      1372 => Some(Self::MorphToBroodLord),
      1373 => Some(Self::MorphToBroodLordCancel),
      2600 => Some(Self::MorphToCollapsiblePurifierTowerDebris),
      2601 => Some(Self::MorphToCollapsiblePurifierTowerDebrisCancel),
      1996 => Some(Self::MorphToCollapsibleRockTowerDebris),
      1997 => Some(Self::MorphToCollapsibleRockTowerDebrisCancel),
      2154 => Some(Self::MorphToCollapsibleRockTowerDebrisRampLeft),
      2155 => Some(Self::MorphToCollapsibleRockTowerDebrisRampLeftCancel),
      2152 => Some(Self::MorphToCollapsibleRockTowerDebrisRampRight),
      2153 => Some(Self::MorphToCollapsibleRockTowerDebrisRampRightCancel),
      1841 => Some(Self::MorphToCollapsibleTerranTowerDebris),
      1842 => Some(Self::MorphToCollapsibleTerranTowerDebrisCancel),
      1843 => Some(Self::MorphToCollapsibleTerranTowerDebrisRampLeft),
      1844 => Some(Self::MorphToCollapsibleTerranTowerDebrisRampLeftCancel),
      1845 => Some(Self::MorphToCollapsibleTerranTowerDebrisRampRight),
      1846 => Some(Self::MorphToCollapsibleTerranTowerDebrisRampRightCancel),
      2481 => Some(Self::MorphToDevourerMp),
      2482 => Some(Self::MorphToDevourerMpCancel),
      1836 => Some(Self::MorphToGhostAlternate),
      1835 => Some(Self::MorphToGhostAlternateMove),
      1838 => Some(Self::MorphToGhostNova),
      1837 => Some(Self::MorphToGhostNovaMove),
      2479 => Some(Self::MorphToGuardianMp),
      2480 => Some(Self::MorphToGuardianMpCancel),
      1978 => Some(Self::MorphToHellion),
      1979 => Some(Self::MorphToHellion),
      1998 => Some(Self::MorphToHellionTank),
      1999 => Some(Self::MorphToHellionTank),
      2923 => Some(Self::MorphToInfestedCivilian),
      2924 => Some(Self::MorphToInfestedCivilian),
      41 => Some(Self::MorphToInfestedTerran),
      40 => Some(Self::MorphToInfestedTerranInfestedTerrans),
      2333 => Some(Self::MorphToLurkerCancel),
      2332 => Some(Self::MorphToLurkerLurkerMp),
      1847 => Some(Self::MorphToMothership),
      1848 => Some(Self::MorphToMothershipCancelMothershipMorph),
      1448 => Some(Self::MorphToOverseer),
      1449 => Some(Self::MorphToOverseerCancel),
      2330 => Some(Self::MorphToRavager),
      2331 => Some(Self::MorphToRavagerCancel),
      2014 => Some(Self::MorphToSwarmHostBurrowedMp),
      2015 => Some(Self::MorphToSwarmHostBurrowedMpCancel),
      2016 => Some(Self::MorphToSwarmHostMp),
      2017 => Some(Self::MorphToSwarmHostMp),
      2771 => Some(Self::MorphToTechReactor),
      2772 => Some(Self::MorphToTechReactor),
      2709 => Some(Self::MorphToTransportOverlordCancel),
      2708 => Some(Self::MorphToTransportOverlordMorphtoOverlordTransport),
      80 => Some(Self::MorphZerglingToBaneling),
      81 => Some(Self::MorphZerglingToBaneling),
      82 => Some(Self::MorphZerglingToBaneling),
      83 => Some(Self::MorphZerglingToBaneling),
      84 => Some(Self::MorphZerglingToBaneling),
      85 => Some(Self::MorphZerglingToBaneling),
      86 => Some(Self::MorphZerglingToBaneling),
      87 => Some(Self::MorphZerglingToBaneling),
      88 => Some(Self::MorphZerglingToBaneling),
      89 => Some(Self::MorphZerglingToBaneling),
      90 => Some(Self::MorphZerglingToBaneling),
      91 => Some(Self::MorphZerglingToBaneling),
      92 => Some(Self::MorphZerglingToBaneling),
      93 => Some(Self::MorphZerglingToBaneling),
      94 => Some(Self::MorphZerglingToBaneling),
      95 => Some(Self::MorphZerglingToBaneling),
      96 => Some(Self::MorphZerglingToBaneling),
      97 => Some(Self::MorphZerglingToBaneling),
      98 => Some(Self::MorphZerglingToBaneling),
      99 => Some(Self::MorphZerglingToBaneling),
      100 => Some(Self::MorphZerglingToBaneling),
      101 => Some(Self::MorphZerglingToBaneling),
      102 => Some(Self::MorphZerglingToBaneling),
      103 => Some(Self::MorphZerglingToBaneling),
      104 => Some(Self::MorphZerglingToBaneling),
      105 => Some(Self::MorphZerglingToBaneling),
      106 => Some(Self::MorphZerglingToBaneling),
      107 => Some(Self::MorphZerglingToBaneling),
      108 => Some(Self::MorphZerglingToBaneling),
      109 => Some(Self::MorphZerglingToBaneling),
      2102 => Some(Self::MothershipCoreEnergize),
      2103 => Some(Self::MothershipCoreEnergizeCancel),
      1974 => Some(Self::MothershipCoreMassRecall),
      1975 => Some(Self::MothershipCoreMassRecall),
      2163 => Some(Self::MothershipCorePurifyNexus),
      2160 => Some(Self::MothershipCorePurifyNexusCancel),
      2161 => Some(Self::MothershipCorePurifyNexusCancel),
      2162 => Some(Self::MothershipCorePurifyNexusMothershipCoreWeapon),
      1883 => Some(Self::MothershipCoreTeleport),
      1884 => Some(Self::MothershipCoreTeleport),
      1852 => Some(Self::MothershipCoreWeapon),
      1851 => Some(Self::MothershipCoreWeaponMothershipStasis),
      2368 => Some(Self::MothershipMassRecall),
      2369 => Some(Self::MothershipMassRecall),
      1849 => Some(Self::MothershipStasis),
      1850 => Some(Self::MothershipStasisCancel),
      16 => Some(Self::Move),
      19 => Some(Self::MoveAcquireMove),
      18 => Some(Self::MoveMoveHoldPosition),
      17 => Some(Self::MoveMovePatrol),
      20 => Some(Self::MoveTurn),
      168 => Some(Self::MuleGather),
      166 => Some(Self::MuleGatherGatherMule),
      167 => Some(Self::MuleGatherReturnCargo),
      78 => Some(Self::MuleRepair),
      79 => Some(Self::MuleRepair),
      _ => None,
    }
  }
}
