
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum N {
  NanoRepair,
  NanoRepairHeal,
  NeuralParasite,
  NeuralParasiteCancel,
  NexusInvulnerability,
  NexusMassRecall,
  NexusPhaseShift,
  NexusShieldOvercharge,
  NexusShieldOverchargeOff,
  NexusShieldRecharge,
  NexusShieldRechargeOnPylon,
  NexusTrain,
  NexusTrainMothership,
  NexusTrainMothershipCore,
  NexusTrainProbe,
  NovaSnipe,
  Null,
  NydusCanalTransport,
  NydusCanalTransportNydusCanalLoad,
  NydusCanalTransportNydusCanalUnloadAll,
  NydusWormTransport,
  NydusWormTransportNydusCanalLoad,
  NydusWormTransportNydusCanalUnloadAll,
}
impl N {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      3398 => Some(Self::NanoRepair),
      3397 => Some(Self::NanoRepairHeal),
      249 => Some(Self::NeuralParasite),
      250 => Some(Self::NeuralParasiteCancel),
      1930 => Some(Self::NexusInvulnerability),
      1931 => Some(Self::NexusInvulnerability),
      3757 => Some(Self::NexusMassRecall),
      3758 => Some(Self::NexusMassRecall),
      1932 => Some(Self::NexusPhaseShift),
      1933 => Some(Self::NexusPhaseShift),
      3767 => Some(Self::NexusShieldOvercharge),
      3768 => Some(Self::NexusShieldOvercharge),
      3769 => Some(Self::NexusShieldOverchargeOff),
      3770 => Some(Self::NexusShieldOverchargeOff),
      3759 => Some(Self::NexusShieldRecharge),
      3760 => Some(Self::NexusShieldRecharge),
      3761 => Some(Self::NexusShieldRechargeOnPylon),
      3762 => Some(Self::NexusShieldRechargeOnPylon),
      1007 => Some(Self::NexusTrain),
      1008 => Some(Self::NexusTrain),
      1009 => Some(Self::NexusTrain),
      1010 => Some(Self::NexusTrain),
      1011 => Some(Self::NexusTrain),
      1012 => Some(Self::NexusTrain),
      1013 => Some(Self::NexusTrain),
      1014 => Some(Self::NexusTrain),
      1015 => Some(Self::NexusTrain),
      1016 => Some(Self::NexusTrain),
      1017 => Some(Self::NexusTrain),
      1018 => Some(Self::NexusTrain),
      1019 => Some(Self::NexusTrain),
      1020 => Some(Self::NexusTrain),
      1021 => Some(Self::NexusTrain),
      1022 => Some(Self::NexusTrain),
      1023 => Some(Self::NexusTrain),
      1024 => Some(Self::NexusTrain),
      1025 => Some(Self::NexusTrain),
      1026 => Some(Self::NexusTrain),
      1027 => Some(Self::NexusTrain),
      1028 => Some(Self::NexusTrain),
      1029 => Some(Self::NexusTrain),
      1030 => Some(Self::NexusTrain),
      1031 => Some(Self::NexusTrain),
      1032 => Some(Self::NexusTrain),
      1033 => Some(Self::NexusTrain),
      1034 => Some(Self::NexusTrain),
      1035 => Some(Self::NexusTrain),
      110 => Some(Self::NexusTrainMothership),
      111 => Some(Self::NexusTrainMothership),
      112 => Some(Self::NexusTrainMothership),
      113 => Some(Self::NexusTrainMothership),
      114 => Some(Self::NexusTrainMothership),
      115 => Some(Self::NexusTrainMothership),
      116 => Some(Self::NexusTrainMothership),
      117 => Some(Self::NexusTrainMothership),
      118 => Some(Self::NexusTrainMothership),
      119 => Some(Self::NexusTrainMothership),
      120 => Some(Self::NexusTrainMothership),
      121 => Some(Self::NexusTrainMothership),
      122 => Some(Self::NexusTrainMothership),
      123 => Some(Self::NexusTrainMothership),
      124 => Some(Self::NexusTrainMothership),
      125 => Some(Self::NexusTrainMothership),
      126 => Some(Self::NexusTrainMothership),
      127 => Some(Self::NexusTrainMothership),
      128 => Some(Self::NexusTrainMothership),
      129 => Some(Self::NexusTrainMothership),
      130 => Some(Self::NexusTrainMothership),
      131 => Some(Self::NexusTrainMothership),
      132 => Some(Self::NexusTrainMothership),
      133 => Some(Self::NexusTrainMothership),
      134 => Some(Self::NexusTrainMothership),
      135 => Some(Self::NexusTrainMothership),
      136 => Some(Self::NexusTrainMothership),
      137 => Some(Self::NexusTrainMothership),
      138 => Some(Self::NexusTrainMothership),
      139 => Some(Self::NexusTrainMothership),
      1853 => Some(Self::NexusTrainMothershipCore),
      1854 => Some(Self::NexusTrainMothershipCore),
      1855 => Some(Self::NexusTrainMothershipCore),
      1856 => Some(Self::NexusTrainMothershipCore),
      1857 => Some(Self::NexusTrainMothershipCore),
      1858 => Some(Self::NexusTrainMothershipCore),
      1859 => Some(Self::NexusTrainMothershipCore),
      1860 => Some(Self::NexusTrainMothershipCore),
      1861 => Some(Self::NexusTrainMothershipCore),
      1862 => Some(Self::NexusTrainMothershipCore),
      1863 => Some(Self::NexusTrainMothershipCore),
      1864 => Some(Self::NexusTrainMothershipCore),
      1865 => Some(Self::NexusTrainMothershipCore),
      1866 => Some(Self::NexusTrainMothershipCore),
      1867 => Some(Self::NexusTrainMothershipCore),
      1868 => Some(Self::NexusTrainMothershipCore),
      1869 => Some(Self::NexusTrainMothershipCore),
      1870 => Some(Self::NexusTrainMothershipCore),
      1871 => Some(Self::NexusTrainMothershipCore),
      1872 => Some(Self::NexusTrainMothershipCore),
      1873 => Some(Self::NexusTrainMothershipCore),
      1874 => Some(Self::NexusTrainMothershipCore),
      1875 => Some(Self::NexusTrainMothershipCore),
      1876 => Some(Self::NexusTrainMothershipCore),
      1877 => Some(Self::NexusTrainMothershipCore),
      1878 => Some(Self::NexusTrainMothershipCore),
      1879 => Some(Self::NexusTrainMothershipCore),
      1880 => Some(Self::NexusTrainMothershipCore),
      1881 => Some(Self::NexusTrainMothershipCore),
      1882 => Some(Self::NexusTrainMothershipCore),
      1006 => Some(Self::NexusTrainProbe),
      3232 => Some(Self::NovaSnipe),
      3233 => Some(Self::NovaSnipe),
      0 => Some(Self::Null),
      1439 => Some(Self::NydusCanalTransport),
      1440 => Some(Self::NydusCanalTransport),
      1441 => Some(Self::NydusCanalTransport),
      1437 => Some(Self::NydusCanalTransportNydusCanalLoad),
      1438 => Some(Self::NydusCanalTransportNydusCanalUnloadAll),
      2372 => Some(Self::NydusWormTransport),
      2373 => Some(Self::NydusWormTransport),
      2374 => Some(Self::NydusWormTransport),
      2370 => Some(Self::NydusWormTransportNydusCanalLoad),
      2371 => Some(Self::NydusWormTransportNydusCanalUnloadAll),
      _ => None,
    }
  }
}
