
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum O {
  Obliterate,
  ObserverMorphtoObserverSiege,
  ObserverSiegeMorphtoObserver,
  OdinBarrage,
  OdinBarrageCancel,
  OdinNuclearStrikeCancel,
  OdinNuclearStrikeOdinNukeCalldown,
  OdinWreckage,
  OmegaStorm,
  OracleCloakField,
  OracleCloakingFieldTargeted,
  OracleNormalMode,
  OracleNormalModeCancel,
  OraclePhaseShift,
  OracleRevelation,
  OracleRevelationMode,
  OracleRevelationModeCancel,
  OracleStasisTrap,
  OracleStasisTrapActivate,
  OracleStasisTrapActivateActivateStasisWard,
  OracleStasisTrapBuild,
  OracleStasisTrapBuildCancel,
  OracleStasisTrapBuildOracleBuildStasisTrap,
  OracleStasisTrapOracleBuildStasisTrap,
  OracleWeaponOracleWeaponOff,
  OracleWeaponOracleWeaponOn,
  OrbitalCommandLand,
  OrbitalLiftOff,
  Overcharge,
  OverlordTransport,
  OverlordTransportOverlordTransportLoad,
  OverlordTransportOverlordTransportUnload,
  OverseerMorphtoOverseerSiegeMode,
  OverseerSiegeModeMorphtoOverseer,
  OverseerSiegeModeMorphtoOverseerMorphtoOverseerNormal,
}
impl O {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2876 => Some(Self::Obliterate),
      2877 => Some(Self::Obliterate),
      3741 => Some(Self::ObserverMorphtoObserverSiege),
      3742 => Some(Self::ObserverMorphtoObserverSiege),
      3739 => Some(Self::ObserverSiegeMorphtoObserver),
      3740 => Some(Self::ObserverSiegeMorphtoObserver),
      3165 => Some(Self::OdinBarrage),
      3166 => Some(Self::OdinBarrageCancel),
      3118 => Some(Self::OdinNuclearStrikeCancel),
      3117 => Some(Self::OdinNuclearStrikeOdinNukeCalldown),
      3119 => Some(Self::OdinWreckage),
      3120 => Some(Self::OdinWreckage),
      3009 => Some(Self::OmegaStorm),
      3010 => Some(Self::OmegaStorm),
      1940 => Some(Self::OracleCloakField),
      1941 => Some(Self::OracleCloakField),
      2326 => Some(Self::OracleCloakingFieldTargeted),
      2327 => Some(Self::OracleCloakingFieldTargeted),
      2150 => Some(Self::OracleNormalMode),
      2151 => Some(Self::OracleNormalModeCancel),
      2334 => Some(Self::OraclePhaseShift),
      2335 => Some(Self::OraclePhaseShift),
      2146 => Some(Self::OracleRevelation),
      2147 => Some(Self::OracleRevelation),
      2148 => Some(Self::OracleRevelationMode),
      2149 => Some(Self::OracleRevelationModeCancel),
      2504 => Some(Self::OracleStasisTrap),
      2537 => Some(Self::OracleStasisTrapActivate),
      2536 => Some(Self::OracleStasisTrapActivateActivateStasisWard),
      2506 => Some(Self::OracleStasisTrapBuild),
      2507 => Some(Self::OracleStasisTrapBuild),
      2508 => Some(Self::OracleStasisTrapBuild),
      2509 => Some(Self::OracleStasisTrapBuild),
      2510 => Some(Self::OracleStasisTrapBuild),
      2511 => Some(Self::OracleStasisTrapBuild),
      2512 => Some(Self::OracleStasisTrapBuild),
      2513 => Some(Self::OracleStasisTrapBuild),
      2514 => Some(Self::OracleStasisTrapBuild),
      2515 => Some(Self::OracleStasisTrapBuild),
      2516 => Some(Self::OracleStasisTrapBuild),
      2517 => Some(Self::OracleStasisTrapBuild),
      2518 => Some(Self::OracleStasisTrapBuild),
      2519 => Some(Self::OracleStasisTrapBuild),
      2520 => Some(Self::OracleStasisTrapBuild),
      2521 => Some(Self::OracleStasisTrapBuild),
      2522 => Some(Self::OracleStasisTrapBuild),
      2523 => Some(Self::OracleStasisTrapBuild),
      2524 => Some(Self::OracleStasisTrapBuild),
      2525 => Some(Self::OracleStasisTrapBuild),
      2526 => Some(Self::OracleStasisTrapBuild),
      2527 => Some(Self::OracleStasisTrapBuild),
      2528 => Some(Self::OracleStasisTrapBuild),
      2529 => Some(Self::OracleStasisTrapBuild),
      2530 => Some(Self::OracleStasisTrapBuild),
      2531 => Some(Self::OracleStasisTrapBuild),
      2532 => Some(Self::OracleStasisTrapBuild),
      2533 => Some(Self::OracleStasisTrapBuild),
      2534 => Some(Self::OracleStasisTrapBuild),
      2535 => Some(Self::OracleStasisTrapBuildCancel),
      2505 => Some(Self::OracleStasisTrapBuildOracleBuildStasisTrap),
      2503 => Some(Self::OracleStasisTrapOracleBuildStasisTrap),
      2376 => Some(Self::OracleWeaponOracleWeaponOff),
      2375 => Some(Self::OracleWeaponOracleWeaponOn),
      1524 => Some(Self::OrbitalCommandLand),
      1525 => Some(Self::OrbitalCommandLand),
      1522 => Some(Self::OrbitalLiftOff),
      1523 => Some(Self::OrbitalLiftOff),
      2360 => Some(Self::Overcharge),
      2361 => Some(Self::Overcharge),
      1407 => Some(Self::OverlordTransport),
      1409 => Some(Self::OverlordTransport),
      1410 => Some(Self::OverlordTransport),
      1406 => Some(Self::OverlordTransportOverlordTransportLoad),
      1408 => Some(Self::OverlordTransportOverlordTransportUnload),
      3743 => Some(Self::OverseerMorphtoOverseerSiegeMode),
      3744 => Some(Self::OverseerMorphtoOverseerSiegeMode),
      3746 => Some(Self::OverseerSiegeModeMorphtoOverseer),
      3745 => Some(Self::OverseerSiegeModeMorphtoOverseerMorphtoOverseerNormal),
      _ => None,
    }
  }
}
