
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum P {
  ParasiticBomb,
  ParasiticBombRelayDodge,
  ParkColonistVehicle,
  PenetratingShot,
  PerditionTurretBurrow,
  PerditionTurretUnburrow,
  PhaseMineBlast,
  PhaseShift,
  PhasingMode,
  PhasingModeCancel,
  Pickup,
  PickupArcade,
  PickupEnergy100,
  PickupEnergy25,
  PickupEnergy50,
  PickupEnergyFull,
  PickupGas100,
  PickupHealth100,
  PickupHealth25,
  PickupHealth50,
  PickupHealthFull,
  PickupMinerals100,
  PickupPalletGas,
  PickupPalletMinerals,
  PickupScrapLarge,
  PickupScrapMedium,
  PickupScrapSmall,
  PlacePointDefenseDrone,
  PortCityBridgeUnitE10,
  PortCityBridgeUnitE10BridgeRetract,
  PortCityBridgeUnitE10Out,
  PortCityBridgeUnitE10OutBridgeExtend,
  PortCityBridgeUnitE12,
  PortCityBridgeUnitE12BridgeRetract,
  PortCityBridgeUnitE12Out,
  PortCityBridgeUnitE12OutBridgeExtend,
  PortCityBridgeUnitE8,
  PortCityBridgeUnitE8BridgeRetract,
  PortCityBridgeUnitE8Out,
  PortCityBridgeUnitE8OutBridgeExtend,
  PortCityBridgeUnitN10,
  PortCityBridgeUnitN10BridgeRetract,
  PortCityBridgeUnitN10Out,
  PortCityBridgeUnitN10OutBridgeExtend,
  PortCityBridgeUnitN12,
  PortCityBridgeUnitN12BridgeRetract,
  PortCityBridgeUnitN12Out,
  PortCityBridgeUnitN12OutBridgeExtend,
  PortCityBridgeUnitN8,
  PortCityBridgeUnitN8BridgeRetract,
  PortCityBridgeUnitN8Out,
  PortCityBridgeUnitN8OutBridgeExtend,
  PortCityBridgeUnitNe10,
  PortCityBridgeUnitNe10BridgeRetract,
  PortCityBridgeUnitNe10Out,
  PortCityBridgeUnitNe10OutBridgeExtend,
  PortCityBridgeUnitNe12,
  PortCityBridgeUnitNe12BridgeRetract,
  PortCityBridgeUnitNe12Out,
  PortCityBridgeUnitNe12OutBridgeExtend,
  PortCityBridgeUnitNe8,
  PortCityBridgeUnitNe8BridgeRetract,
  PortCityBridgeUnitNe8Out,
  PortCityBridgeUnitNe8OutBridgeExtend,
  PortCityBridgeUnitNw10,
  PortCityBridgeUnitNw10BridgeRetract,
  PortCityBridgeUnitNw10Out,
  PortCityBridgeUnitNw10OutBridgeExtend,
  PortCityBridgeUnitNw12,
  PortCityBridgeUnitNw12BridgeRetract,
  PortCityBridgeUnitNw12Out,
  PortCityBridgeUnitNw12OutBridgeExtend,
  PortCityBridgeUnitNw8,
  PortCityBridgeUnitNw8BridgeRetract,
  PortCityBridgeUnitNw8Out,
  PortCityBridgeUnitNw8OutBridgeExtend,
  PortCityBridgeUnitS10,
  PortCityBridgeUnitS10BridgeRetract,
  PortCityBridgeUnitS10Out,
  PortCityBridgeUnitS10OutBridgeExtend,
  PortCityBridgeUnitS12,
  PortCityBridgeUnitS12BridgeRetract,
  PortCityBridgeUnitS12Out,
  PortCityBridgeUnitS12OutBridgeExtend,
  PortCityBridgeUnitS8,
  PortCityBridgeUnitS8BridgeRetract,
  PortCityBridgeUnitS8Out,
  PortCityBridgeUnitS8OutBridgeExtend,
  PortCityBridgeUnitSe10,
  PortCityBridgeUnitSe10BridgeRetract,
  PortCityBridgeUnitSe10Out,
  PortCityBridgeUnitSe10OutBridgeExtend,
  PortCityBridgeUnitSe12,
  PortCityBridgeUnitSe12BridgeRetract,
  PortCityBridgeUnitSe12Out,
  PortCityBridgeUnitSe12OutBridgeExtend,
  PortCityBridgeUnitSe8,
  PortCityBridgeUnitSe8BridgeRetract,
  PortCityBridgeUnitSe8Out,
  PortCityBridgeUnitSe8OutBridgeExtend,
  PortCityBridgeUnitSw10,
  PortCityBridgeUnitSw10BridgeRetract,
  PortCityBridgeUnitSw10Out,
  PortCityBridgeUnitSw10OutBridgeExtend,
  PortCityBridgeUnitSw12,
  PortCityBridgeUnitSw12BridgeRetract,
  PortCityBridgeUnitSw12Out,
  PortCityBridgeUnitSw12OutBridgeExtend,
  PortCityBridgeUnitSw8,
  PortCityBridgeUnitSw8BridgeRetract,
  PortCityBridgeUnitSw8Out,
  PortCityBridgeUnitSw8OutBridgeExtend,
  PortCityBridgeUnitW10,
  PortCityBridgeUnitW10BridgeRetract,
  PortCityBridgeUnitW10Out,
  PortCityBridgeUnitW10OutBridgeExtend,
  PortCityBridgeUnitW12,
  PortCityBridgeUnitW12BridgeRetract,
  PortCityBridgeUnitW12Out,
  PortCityBridgeUnitW12OutBridgeExtend,
  PortCityBridgeUnitW8,
  PortCityBridgeUnitW8BridgeRetract,
  PortCityBridgeUnitW8Out,
  PortCityBridgeUnitW8OutBridgeExtend,
  ProbeHarvest,
  ProbeHarvestGather,
  ProbeHarvestReturnCargo,
  ProgressRally,
  ProtossBuild,
  ProtossBuildAssimilator,
  ProtossBuildCancel,
  ProtossBuildCyberneticsCore,
  ProtossBuildDarkShrine,
  ProtossBuildFleetBeacon,
  ProtossBuildForge,
  ProtossBuildGateway,
  ProtossBuildNexus,
  ProtossBuildPhotonCannon,
  ProtossBuildPylon,
  ProtossBuildRoboticsBay,
  ProtossBuildRoboticsFacility,
  ProtossBuildShieldBattery,
  ProtossBuildStargate,
  ProtossBuildTemplarArchive,
  ProtossBuildTwilightCouncil,
  ProtossBuildingQueueCancel,
  ProtossBuildingQueueCancelSlot,
  PsiStorm,
  PsionicShockwave,
  PsytrousOxidePsytrousOxideOff,
  PsytrousOxidePsytrousOxideOn,
  PulsarBeam,
  PulsarBeamRipField,
  PulsarCannon,
  PurificationNova,
  PurificationNovaMorph,
  PurificationNovaMorphBack,
  PurificationNovaTargeted,
  PurifierPlanetCracker,
  PurifierTogglePowerPurifierPowerDown,
  PurifierTogglePowerPurifierPowerUp,
  PurifyMorphPylon,
  PurifyMorphPylonBack,
  PurifyMorphPylonBackMothershipCoreWeapon,
  PurifyMorphPylonMothershipCoreWeapon,
}
impl P {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2542 => Some(Self::ParasiticBomb),
      2543 => Some(Self::ParasiticBomb),
      3791 => Some(Self::ParasiticBombRelayDodge),
      3792 => Some(Self::ParasiticBombRelayDodge),
      2903 => Some(Self::ParkColonistVehicle),
      2904 => Some(Self::ParkColonistVehicle),
      2590 => Some(Self::PenetratingShot),
      2591 => Some(Self::PenetratingShot),
      2995 => Some(Self::PerditionTurretBurrow),
      2996 => Some(Self::PerditionTurretBurrow),
      2997 => Some(Self::PerditionTurretUnburrow),
      2998 => Some(Self::PerditionTurretUnburrow),
      3169 => Some(Self::PhaseMineBlast),
      3170 => Some(Self::PhaseMineBlast),
      193 => Some(Self::PhaseShift),
      194 => Some(Self::PhaseShift),
      1528 => Some(Self::PhasingMode),
      1529 => Some(Self::PhasingModeCancel),
      3399 => Some(Self::Pickup),
      3400 => Some(Self::Pickup),
      3401 => Some(Self::PickupArcade),
      3402 => Some(Self::PickupArcade),
      3419 => Some(Self::PickupEnergy100),
      3420 => Some(Self::PickupEnergy100),
      3415 => Some(Self::PickupEnergy25),
      3416 => Some(Self::PickupEnergy25),
      3417 => Some(Self::PickupEnergy50),
      3418 => Some(Self::PickupEnergy50),
      3421 => Some(Self::PickupEnergyFull),
      3422 => Some(Self::PickupEnergyFull),
      3403 => Some(Self::PickupGas100),
      3404 => Some(Self::PickupGas100),
      3411 => Some(Self::PickupHealth100),
      3412 => Some(Self::PickupHealth100),
      3407 => Some(Self::PickupHealth25),
      3408 => Some(Self::PickupHealth25),
      3409 => Some(Self::PickupHealth50),
      3410 => Some(Self::PickupHealth50),
      3413 => Some(Self::PickupHealthFull),
      3414 => Some(Self::PickupHealthFull),
      3405 => Some(Self::PickupMinerals100),
      3406 => Some(Self::PickupMinerals100),
      2089 => Some(Self::PickupPalletGas),
      2090 => Some(Self::PickupPalletGas),
      2091 => Some(Self::PickupPalletMinerals),
      2092 => Some(Self::PickupPalletMinerals),
      2087 => Some(Self::PickupScrapLarge),
      2088 => Some(Self::PickupScrapLarge),
      2085 => Some(Self::PickupScrapMedium),
      2086 => Some(Self::PickupScrapMedium),
      2083 => Some(Self::PickupScrapSmall),
      2084 => Some(Self::PickupScrapSmall),
      144 => Some(Self::PlacePointDefenseDrone),
      145 => Some(Self::PlacePointDefenseDrone),
      2677 => Some(Self::PortCityBridgeUnitE10),
      2676 => Some(Self::PortCityBridgeUnitE10BridgeRetract),
      2675 => Some(Self::PortCityBridgeUnitE10Out),
      2674 => Some(Self::PortCityBridgeUnitE10OutBridgeExtend),
      2693 => Some(Self::PortCityBridgeUnitE12),
      2692 => Some(Self::PortCityBridgeUnitE12BridgeRetract),
      2691 => Some(Self::PortCityBridgeUnitE12Out),
      2690 => Some(Self::PortCityBridgeUnitE12OutBridgeExtend),
      2661 => Some(Self::PortCityBridgeUnitE8),
      2660 => Some(Self::PortCityBridgeUnitE8BridgeRetract),
      2659 => Some(Self::PortCityBridgeUnitE8Out),
      2658 => Some(Self::PortCityBridgeUnitE8OutBridgeExtend),
      2669 => Some(Self::PortCityBridgeUnitN10),
      2668 => Some(Self::PortCityBridgeUnitN10BridgeRetract),
      2667 => Some(Self::PortCityBridgeUnitN10Out),
      2666 => Some(Self::PortCityBridgeUnitN10OutBridgeExtend),
      2685 => Some(Self::PortCityBridgeUnitN12),
      2684 => Some(Self::PortCityBridgeUnitN12BridgeRetract),
      2683 => Some(Self::PortCityBridgeUnitN12Out),
      2682 => Some(Self::PortCityBridgeUnitN12OutBridgeExtend),
      2653 => Some(Self::PortCityBridgeUnitN8),
      2652 => Some(Self::PortCityBridgeUnitN8BridgeRetract),
      2651 => Some(Self::PortCityBridgeUnitN8Out),
      2650 => Some(Self::PortCityBridgeUnitN8OutBridgeExtend),
      2621 => Some(Self::PortCityBridgeUnitNe10),
      2620 => Some(Self::PortCityBridgeUnitNe10BridgeRetract),
      2619 => Some(Self::PortCityBridgeUnitNe10Out),
      2618 => Some(Self::PortCityBridgeUnitNe10OutBridgeExtend),
      2637 => Some(Self::PortCityBridgeUnitNe12),
      2636 => Some(Self::PortCityBridgeUnitNe12BridgeRetract),
      2635 => Some(Self::PortCityBridgeUnitNe12Out),
      2634 => Some(Self::PortCityBridgeUnitNe12OutBridgeExtend),
      2605 => Some(Self::PortCityBridgeUnitNe8),
      2604 => Some(Self::PortCityBridgeUnitNe8BridgeRetract),
      2603 => Some(Self::PortCityBridgeUnitNe8Out),
      2602 => Some(Self::PortCityBridgeUnitNe8OutBridgeExtend),
      2629 => Some(Self::PortCityBridgeUnitNw10),
      2628 => Some(Self::PortCityBridgeUnitNw10BridgeRetract),
      2627 => Some(Self::PortCityBridgeUnitNw10Out),
      2626 => Some(Self::PortCityBridgeUnitNw10OutBridgeExtend),
      2645 => Some(Self::PortCityBridgeUnitNw12),
      2644 => Some(Self::PortCityBridgeUnitNw12BridgeRetract),
      2643 => Some(Self::PortCityBridgeUnitNw12Out),
      2642 => Some(Self::PortCityBridgeUnitNw12OutBridgeExtend),
      2613 => Some(Self::PortCityBridgeUnitNw8),
      2612 => Some(Self::PortCityBridgeUnitNw8BridgeRetract),
      2611 => Some(Self::PortCityBridgeUnitNw8Out),
      2610 => Some(Self::PortCityBridgeUnitNw8OutBridgeExtend),
      2673 => Some(Self::PortCityBridgeUnitS10),
      2672 => Some(Self::PortCityBridgeUnitS10BridgeRetract),
      2671 => Some(Self::PortCityBridgeUnitS10Out),
      2670 => Some(Self::PortCityBridgeUnitS10OutBridgeExtend),
      2689 => Some(Self::PortCityBridgeUnitS12),
      2688 => Some(Self::PortCityBridgeUnitS12BridgeRetract),
      2687 => Some(Self::PortCityBridgeUnitS12Out),
      2686 => Some(Self::PortCityBridgeUnitS12OutBridgeExtend),
      2657 => Some(Self::PortCityBridgeUnitS8),
      2656 => Some(Self::PortCityBridgeUnitS8BridgeRetract),
      2655 => Some(Self::PortCityBridgeUnitS8Out),
      2654 => Some(Self::PortCityBridgeUnitS8OutBridgeExtend),
      2625 => Some(Self::PortCityBridgeUnitSe10),
      2624 => Some(Self::PortCityBridgeUnitSe10BridgeRetract),
      2623 => Some(Self::PortCityBridgeUnitSe10Out),
      2622 => Some(Self::PortCityBridgeUnitSe10OutBridgeExtend),
      2641 => Some(Self::PortCityBridgeUnitSe12),
      2640 => Some(Self::PortCityBridgeUnitSe12BridgeRetract),
      2639 => Some(Self::PortCityBridgeUnitSe12Out),
      2638 => Some(Self::PortCityBridgeUnitSe12OutBridgeExtend),
      2609 => Some(Self::PortCityBridgeUnitSe8),
      2608 => Some(Self::PortCityBridgeUnitSe8BridgeRetract),
      2607 => Some(Self::PortCityBridgeUnitSe8Out),
      2606 => Some(Self::PortCityBridgeUnitSe8OutBridgeExtend),
      2633 => Some(Self::PortCityBridgeUnitSw10),
      2632 => Some(Self::PortCityBridgeUnitSw10BridgeRetract),
      2631 => Some(Self::PortCityBridgeUnitSw10Out),
      2630 => Some(Self::PortCityBridgeUnitSw10OutBridgeExtend),
      2649 => Some(Self::PortCityBridgeUnitSw12),
      2648 => Some(Self::PortCityBridgeUnitSw12BridgeRetract),
      2647 => Some(Self::PortCityBridgeUnitSw12Out),
      2646 => Some(Self::PortCityBridgeUnitSw12OutBridgeExtend),
      2617 => Some(Self::PortCityBridgeUnitSw8),
      2616 => Some(Self::PortCityBridgeUnitSw8BridgeRetract),
      2615 => Some(Self::PortCityBridgeUnitSw8Out),
      2614 => Some(Self::PortCityBridgeUnitSw8OutBridgeExtend),
      2681 => Some(Self::PortCityBridgeUnitW10),
      2680 => Some(Self::PortCityBridgeUnitW10BridgeRetract),
      2679 => Some(Self::PortCityBridgeUnitW10Out),
      2678 => Some(Self::PortCityBridgeUnitW10OutBridgeExtend),
      2697 => Some(Self::PortCityBridgeUnitW12),
      2696 => Some(Self::PortCityBridgeUnitW12BridgeRetract),
      2695 => Some(Self::PortCityBridgeUnitW12Out),
      2694 => Some(Self::PortCityBridgeUnitW12OutBridgeExtend),
      2665 => Some(Self::PortCityBridgeUnitW8),
      2664 => Some(Self::PortCityBridgeUnitW8BridgeRetract),
      2663 => Some(Self::PortCityBridgeUnitW8Out),
      2662 => Some(Self::PortCityBridgeUnitW8OutBridgeExtend),
      300 => Some(Self::ProbeHarvest),
      298 => Some(Self::ProbeHarvestGather),
      299 => Some(Self::ProbeHarvestReturnCargo),
      199 => Some(Self::ProgressRally),
      200 => Some(Self::ProgressRally),
      201 => Some(Self::ProgressRally),
      202 => Some(Self::ProgressRally),
      888 => Some(Self::ProtossBuild),
      896 => Some(Self::ProtossBuild),
      897 => Some(Self::ProtossBuild),
      898 => Some(Self::ProtossBuild),
      899 => Some(Self::ProtossBuild),
      900 => Some(Self::ProtossBuild),
      901 => Some(Self::ProtossBuild),
      902 => Some(Self::ProtossBuild),
      903 => Some(Self::ProtossBuild),
      904 => Some(Self::ProtossBuild),
      905 => Some(Self::ProtossBuild),
      906 => Some(Self::ProtossBuild),
      907 => Some(Self::ProtossBuild),
      908 => Some(Self::ProtossBuild),
      909 => Some(Self::ProtossBuild),
      882 => Some(Self::ProtossBuildAssimilator),
      910 => Some(Self::ProtossBuildCancel),
      894 => Some(Self::ProtossBuildCyberneticsCore),
      891 => Some(Self::ProtossBuildDarkShrine),
      885 => Some(Self::ProtossBuildFleetBeacon),
      884 => Some(Self::ProtossBuildForge),
      883 => Some(Self::ProtossBuildGateway),
      880 => Some(Self::ProtossBuildNexus),
      887 => Some(Self::ProtossBuildPhotonCannon),
      881 => Some(Self::ProtossBuildPylon),
      892 => Some(Self::ProtossBuildRoboticsBay),
      893 => Some(Self::ProtossBuildRoboticsFacility),
      895 => Some(Self::ProtossBuildShieldBattery),
      889 => Some(Self::ProtossBuildStargate),
      890 => Some(Self::ProtossBuildTemplarArchive),
      886 => Some(Self::ProtossBuildTwilightCouncil),
      2075 => Some(Self::ProtossBuildingQueueCancel),
      2076 => Some(Self::ProtossBuildingQueueCancelSlot),
      1036 => Some(Self::PsiStorm),
      1037 => Some(Self::PsiStorm),
      3011 => Some(Self::PsionicShockwave),
      3012 => Some(Self::PsionicShockwave),
      3375 => Some(Self::PsytrousOxidePsytrousOxideOff),
      3374 => Some(Self::PsytrousOxidePsytrousOxideOn),
      2378 => Some(Self::PulsarBeam),
      2377 => Some(Self::PulsarBeamRipField),
      2379 => Some(Self::PulsarCannon),
      2380 => Some(Self::PulsarCannon),
      2344 => Some(Self::PurificationNova),
      2345 => Some(Self::PurificationNova),
      2546 => Some(Self::PurificationNovaMorph),
      2547 => Some(Self::PurificationNovaMorph),
      2548 => Some(Self::PurificationNovaMorphBack),
      2549 => Some(Self::PurificationNovaMorphBack),
      2346 => Some(Self::PurificationNovaTargeted),
      2347 => Some(Self::PurificationNovaTargeted),
      3238 => Some(Self::PurifierPlanetCracker),
      3239 => Some(Self::PurifierPlanetCracker),
      3167 => Some(Self::PurifierTogglePowerPurifierPowerDown),
      3168 => Some(Self::PurifierTogglePowerPurifierPowerUp),
      2717 => Some(Self::PurifyMorphPylon),
      2719 => Some(Self::PurifyMorphPylonBack),
      2718 => Some(Self::PurifyMorphPylonBackMothershipCoreWeapon),
      2716 => Some(Self::PurifyMorphPylonMothershipCoreWeapon),
      _ => None,
    }
  }
}
