
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum R {
  Rally,
  RallyCommand,
  RallyHatchery,
  RallyNexus,
  RavagerCorrosiveBile,
  RavenBuild,
  RavenBuildAutoTurret,
  RavenBuildCancel,
  RavenRepairDrone,
  RavenRepairDroneHeal,
  RavenScramblerMissile,
  RavenShredderMissile,
  RaynorC4,
  RaynorC4PlantC4Charge,
  RaynorSnipe,
  ReactorMorph,
  ReaperPlacementMorph,
  RedstoneLavaCritterBurrow,
  RedstoneLavaCritterBurrowBurrowDown,
  RedstoneLavaCritterInjuredBurrow,
  RedstoneLavaCritterInjuredBurrowBurrowDown,
  RedstoneLavaCritterInjuredUnburrow,
  RedstoneLavaCritterInjuredUnburrowBurrowUp,
  RedstoneLavaCritterUnburrow,
  RedstoneLavaCritterUnburrowBurrowUp,
  RefineryToAutomatedRefinery,
  RefineryToAutomatedRefineryRaise,
  ReleaseInterceptors,
  ReleaseMinion,
  Repair,
  RepairGeneral,
  ResearchLabTransport,
  ResearchLabTransportHutLoad,
  ResearchLabTransportHutUnloadAll,
  ResearchProtossAirArmor,
  ResearchProtossAirWeapons,
  ResearchProtossGroundArmor,
  ResearchProtossGroundWeapons,
  ResearchProtossShields,
  ResearchTerranInfantryArmor,
  ResearchTerranInfantryWeapons,
  ResearchTerranShipWeapons,
  ResearchTerranVehicleAndShipPlating,
  ResearchTerranVehicleWeapons,
  ResearchZergFlyerArmor,
  ResearchZergFlyerAttack,
  ResearchZergGroundArmor,
  ResearchZergMeleeWeapons,
  ResearchZergMissileWeapons,
  ResourceBlocker,
  ResourceStun,
  RestoreShields,
  RoachWarrenResearch,
  RoachWarrenResearchEvolveGlialRegeneration,
  RoachWarrenResearchEvolveTunnelingClaws,
  RoachWarrenResearchRoachSupply,
  RoboticsBayResearch,
  RoboticsBayResearchResearchExtendedThermalLance,
  RoboticsBayResearchResearchGraviticBooster,
  RoboticsBayResearchResearchGraviticDrive,
  RoboticsBayResearchResearchImmortalRevive,
  RoboticsFacilityTrain,
  RoboticsFacilityTrainColossus,
  RoboticsFacilityTrainImmortal,
  RoboticsFacilityTrainObserver,
  RoboticsFacilityTrainWarpPrism,
  RoboticsFacilityTrainWarpinDisruptor,
  RogueGhostCloakCloakOff,
  RogueGhostCloakCloakOnSpectre,
  Root,
}
impl R {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      195 => Some(Self::Rally),
      196 => Some(Self::Rally),
      197 => Some(Self::Rally),
      198 => Some(Self::Rally),
      203 => Some(Self::RallyCommand),
      204 => Some(Self::RallyCommand),
      205 => Some(Self::RallyCommand),
      206 => Some(Self::RallyCommand),
      211 => Some(Self::RallyHatchery),
      212 => Some(Self::RallyHatchery),
      213 => Some(Self::RallyHatchery),
      214 => Some(Self::RallyHatchery),
      207 => Some(Self::RallyNexus),
      208 => Some(Self::RallyNexus),
      209 => Some(Self::RallyNexus),
      210 => Some(Self::RallyNexus),
      2338 => Some(Self::RavagerCorrosiveBile),
      2339 => Some(Self::RavagerCorrosiveBile),
      350 => Some(Self::RavenBuild),
      351 => Some(Self::RavenBuild),
      352 => Some(Self::RavenBuild),
      353 => Some(Self::RavenBuild),
      354 => Some(Self::RavenBuild),
      355 => Some(Self::RavenBuild),
      356 => Some(Self::RavenBuild),
      357 => Some(Self::RavenBuild),
      358 => Some(Self::RavenBuild),
      359 => Some(Self::RavenBuild),
      360 => Some(Self::RavenBuild),
      361 => Some(Self::RavenBuild),
      362 => Some(Self::RavenBuild),
      363 => Some(Self::RavenBuild),
      364 => Some(Self::RavenBuild),
      365 => Some(Self::RavenBuild),
      366 => Some(Self::RavenBuild),
      367 => Some(Self::RavenBuild),
      368 => Some(Self::RavenBuild),
      369 => Some(Self::RavenBuild),
      370 => Some(Self::RavenBuild),
      371 => Some(Self::RavenBuild),
      372 => Some(Self::RavenBuild),
      373 => Some(Self::RavenBuild),
      374 => Some(Self::RavenBuild),
      375 => Some(Self::RavenBuild),
      376 => Some(Self::RavenBuild),
      377 => Some(Self::RavenBuild),
      378 => Some(Self::RavenBuild),
      349 => Some(Self::RavenBuildAutoTurret),
      379 => Some(Self::RavenBuildCancel),
      3749 => Some(Self::RavenRepairDrone),
      3750 => Some(Self::RavenRepairDrone),
      3751 => Some(Self::RavenRepairDroneHeal),
      3752 => Some(Self::RavenRepairDroneHeal),
      3747 => Some(Self::RavenScramblerMissile),
      3748 => Some(Self::RavenScramblerMissile),
      3753 => Some(Self::RavenShredderMissile),
      3754 => Some(Self::RavenShredderMissile),
      3313 => Some(Self::RaynorC4),
      3312 => Some(Self::RaynorC4PlantC4Charge),
      2936 => Some(Self::RaynorSnipe),
      2937 => Some(Self::RaynorSnipe),
      1674 => Some(Self::ReactorMorph),
      1675 => Some(Self::ReactorMorph),
      3645 => Some(Self::ReaperPlacementMorph),
      3646 => Some(Self::ReaperPlacementMorph),
      1399 => Some(Self::RedstoneLavaCritterBurrow),
      1398 => Some(Self::RedstoneLavaCritterBurrowBurrowDown),
      1401 => Some(Self::RedstoneLavaCritterInjuredBurrow),
      1400 => Some(Self::RedstoneLavaCritterInjuredBurrowBurrowDown),
      1405 => Some(Self::RedstoneLavaCritterInjuredUnburrow),
      1404 => Some(Self::RedstoneLavaCritterInjuredUnburrowBurrowUp),
      1403 => Some(Self::RedstoneLavaCritterUnburrow),
      1402 => Some(Self::RedstoneLavaCritterUnburrowBurrowUp),
      3394 => Some(Self::RefineryToAutomatedRefinery),
      3393 => Some(Self::RefineryToAutomatedRefineryRaise),
      2336 => Some(Self::ReleaseInterceptors),
      2337 => Some(Self::ReleaseInterceptors),
      2880 => Some(Self::ReleaseMinion),
      2881 => Some(Self::ReleaseMinion),
      316 => Some(Self::Repair),
      317 => Some(Self::Repair),
      3685 => Some(Self::RepairGeneral),
      3123 => Some(Self::ResearchLabTransport),
      3124 => Some(Self::ResearchLabTransport),
      3125 => Some(Self::ResearchLabTransport),
      3121 => Some(Self::ResearchLabTransportHutLoad),
      3122 => Some(Self::ResearchLabTransportHutUnloadAll),
      3692 => Some(Self::ResearchProtossAirArmor),
      3693 => Some(Self::ResearchProtossAirWeapons),
      3694 => Some(Self::ResearchProtossGroundArmor),
      3695 => Some(Self::ResearchProtossGroundWeapons),
      3696 => Some(Self::ResearchProtossShields),
      3697 => Some(Self::ResearchTerranInfantryArmor),
      3698 => Some(Self::ResearchTerranInfantryWeapons),
      3699 => Some(Self::ResearchTerranShipWeapons),
      3700 => Some(Self::ResearchTerranVehicleAndShipPlating),
      3701 => Some(Self::ResearchTerranVehicleWeapons),
      3702 => Some(Self::ResearchZergFlyerArmor),
      3703 => Some(Self::ResearchZergFlyerAttack),
      3704 => Some(Self::ResearchZergGroundArmor),
      3705 => Some(Self::ResearchZergMeleeWeapons),
      3706 => Some(Self::ResearchZergMissileWeapons),
      2002 => Some(Self::ResourceBlocker),
      2003 => Some(Self::ResourceBlocker),
      2004 => Some(Self::ResourceStun),
      2005 => Some(Self::ResourceStun),
      1980 => Some(Self::RestoreShields),
      1981 => Some(Self::RestoreShields),
      215 => Some(Self::RoachWarrenResearch),
      219 => Some(Self::RoachWarrenResearch),
      220 => Some(Self::RoachWarrenResearch),
      221 => Some(Self::RoachWarrenResearch),
      222 => Some(Self::RoachWarrenResearch),
      223 => Some(Self::RoachWarrenResearch),
      224 => Some(Self::RoachWarrenResearch),
      225 => Some(Self::RoachWarrenResearch),
      226 => Some(Self::RoachWarrenResearch),
      227 => Some(Self::RoachWarrenResearch),
      228 => Some(Self::RoachWarrenResearch),
      229 => Some(Self::RoachWarrenResearch),
      230 => Some(Self::RoachWarrenResearch),
      231 => Some(Self::RoachWarrenResearch),
      232 => Some(Self::RoachWarrenResearch),
      233 => Some(Self::RoachWarrenResearch),
      234 => Some(Self::RoachWarrenResearch),
      235 => Some(Self::RoachWarrenResearch),
      236 => Some(Self::RoachWarrenResearch),
      237 => Some(Self::RoachWarrenResearch),
      238 => Some(Self::RoachWarrenResearch),
      239 => Some(Self::RoachWarrenResearch),
      240 => Some(Self::RoachWarrenResearch),
      241 => Some(Self::RoachWarrenResearch),
      242 => Some(Self::RoachWarrenResearch),
      243 => Some(Self::RoachWarrenResearch),
      244 => Some(Self::RoachWarrenResearch),
      216 => Some(Self::RoachWarrenResearchEvolveGlialRegeneration),
      217 => Some(Self::RoachWarrenResearchEvolveTunnelingClaws),
      218 => Some(Self::RoachWarrenResearchRoachSupply),
      1092 => Some(Self::RoboticsBayResearch),
      1095 => Some(Self::RoboticsBayResearch),
      1096 => Some(Self::RoboticsBayResearch),
      1098 => Some(Self::RoboticsBayResearch),
      1100 => Some(Self::RoboticsBayResearch),
      1101 => Some(Self::RoboticsBayResearch),
      1102 => Some(Self::RoboticsBayResearch),
      1103 => Some(Self::RoboticsBayResearch),
      1104 => Some(Self::RoboticsBayResearch),
      1105 => Some(Self::RoboticsBayResearch),
      1106 => Some(Self::RoboticsBayResearch),
      1107 => Some(Self::RoboticsBayResearch),
      1108 => Some(Self::RoboticsBayResearch),
      1109 => Some(Self::RoboticsBayResearch),
      1110 => Some(Self::RoboticsBayResearch),
      1111 => Some(Self::RoboticsBayResearch),
      1112 => Some(Self::RoboticsBayResearch),
      1113 => Some(Self::RoboticsBayResearch),
      1114 => Some(Self::RoboticsBayResearch),
      1115 => Some(Self::RoboticsBayResearch),
      1116 => Some(Self::RoboticsBayResearch),
      1117 => Some(Self::RoboticsBayResearch),
      1118 => Some(Self::RoboticsBayResearch),
      1119 => Some(Self::RoboticsBayResearch),
      1120 => Some(Self::RoboticsBayResearch),
      1121 => Some(Self::RoboticsBayResearch),
      1097 => Some(Self::RoboticsBayResearchResearchExtendedThermalLance),
      1093 => Some(Self::RoboticsBayResearchResearchGraviticBooster),
      1094 => Some(Self::RoboticsBayResearchResearchGraviticDrive),
      1099 => Some(Self::RoboticsBayResearchResearchImmortalRevive),
      980 => Some(Self::RoboticsFacilityTrain),
      981 => Some(Self::RoboticsFacilityTrain),
      982 => Some(Self::RoboticsFacilityTrain),
      983 => Some(Self::RoboticsFacilityTrain),
      984 => Some(Self::RoboticsFacilityTrain),
      985 => Some(Self::RoboticsFacilityTrain),
      986 => Some(Self::RoboticsFacilityTrain),
      987 => Some(Self::RoboticsFacilityTrain),
      988 => Some(Self::RoboticsFacilityTrain),
      989 => Some(Self::RoboticsFacilityTrain),
      990 => Some(Self::RoboticsFacilityTrain),
      991 => Some(Self::RoboticsFacilityTrain),
      992 => Some(Self::RoboticsFacilityTrain),
      993 => Some(Self::RoboticsFacilityTrain),
      995 => Some(Self::RoboticsFacilityTrain),
      996 => Some(Self::RoboticsFacilityTrain),
      997 => Some(Self::RoboticsFacilityTrain),
      998 => Some(Self::RoboticsFacilityTrain),
      999 => Some(Self::RoboticsFacilityTrain),
      1000 => Some(Self::RoboticsFacilityTrain),
      1001 => Some(Self::RoboticsFacilityTrain),
      1002 => Some(Self::RoboticsFacilityTrain),
      1003 => Some(Self::RoboticsFacilityTrain),
      1004 => Some(Self::RoboticsFacilityTrain),
      1005 => Some(Self::RoboticsFacilityTrain),
      978 => Some(Self::RoboticsFacilityTrainColossus),
      979 => Some(Self::RoboticsFacilityTrainImmortal),
      977 => Some(Self::RoboticsFacilityTrainObserver),
      976 => Some(Self::RoboticsFacilityTrainWarpPrism),
      994 => Some(Self::RoboticsFacilityTrainWarpinDisruptor),
      3195 => Some(Self::RogueGhostCloakCloakOff),
      3194 => Some(Self::RogueGhostCloakCloakOnSpectre),
      3680 => Some(Self::Root),
      _ => None,
    }
  }
}
