
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum T {
  TacNukeStrikeCancel,
  TacNukeStrikeNukeCalldown,
  TalDarimVortex,
  TarsonisDoorE,
  TarsonisDoorELowered,
  TarsonisDoorN,
  TarsonisDoorNLowered,
  TarsonisDoorNe,
  TarsonisDoorNeLowered,
  TarsonisDoorNw,
  TarsonisDoorNwLowered,
  Taunt,
  TaurenOuthouseLiftoff,
  TaurenOuthouseLiftoffTaurenOuthouseFly,
  TaurenOuthouseTransport,
  TaurenOuthouseTransportLoadTaurenOuthouse,
  TaurenOuthouseTransportUnloadTaurenOuthouse,
  TaurenStimpack,
  TechLabMorph,
  TechReactorMorph,
  TempestDisruptionBlast,
  TempestDisruptionBlastCancel,
  TemplarArchivesResearch,
  TemplarArchivesResearchResearchPsiStorm,
  TempleDoorDown,
  TempleDoorDownUrdl,
  TempleDoorUp,
  TempleDoorUpUrdl,
  TemporalField,
  TemporalRift,
  TerranBuild,
  TerranBuildArmory,
  TerranBuildBarracks,
  TerranBuildBunker,
  TerranBuildCancel,
  TerranBuildCommandCenter,
  TerranBuildDrop,
  TerranBuildDropCancel,
  TerranBuildDropSupplyDepotDrop,
  TerranBuildEngineeringBay,
  TerranBuildFactory,
  TerranBuildFusionCore,
  TerranBuildGhostAcademy,
  TerranBuildMissileTurret,
  TerranBuildRefinery,
  TerranBuildSensorTower,
  TerranBuildStarport,
  TerranBuildSupplyDepot,
  TestHeroDebugMissileAbility,
  TestHeroDebugTrackingAbility,
  TestHeroDebugTrackingAbilityCancel,
  TestHeroGrab,
  TestHeroGrabGrabZergling,
  TestHeroThrow,
  TestHeroThrowThrowZergling,
  TestInteractDesignate,
  TestInventory,
  TestLearn,
  TestLeveledSpell,
  TestLeveledSpellYamatoGun,
  TestPawn,
  TestRevive,
  TestReviveScv,
  TestSell,
  TestZerg,
  TestZergCancel,
  TheMorosDevice,
  ThorApModeArmorpiercingMode,
  ThorApModeCancel,
  ThorNormalModeCancel,
  ThorNormalModeExplosiveMode,
  ThorReborn,
  ThorRebornCancel,
  ThorWreckage,
  TimeStop,
  TimeStopCancel,
  TimeWarp,
  TornadoMissile,
  TossGrenade,
  TowerCapture,
  TrainQueen,
  Transfusion,
  TransportLoad,
  TransportLoadAll,
  TransportMode,
  TransportModeCancel,
  TransportTruckTransport,
  TransportTruckTransportTransportTruckLoad,
  TransportTruckTransportTransportTruckUnloadAll,
  TransportUnloadAll,
  TransportUnloadAt,
  TransportUnloadUnit,
  TwilightCouncilResearch,
  TwilightCouncilResearchAdeptResearchPiercingUpgrade,
  TwilightCouncilResearchResearchCharge,
  TwilightCouncilResearchResearchStalkerTeleport,
  Tychus03OmegaStorm,
}
impl T {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      1623 => Some(Self::TacNukeStrikeCancel),
      1622 => Some(Self::TacNukeStrikeNukeCalldown),
      3236 => Some(Self::TalDarimVortex),
      3237 => Some(Self::TalDarimVortex),
      2270 => Some(Self::TarsonisDoorE),
      2271 => Some(Self::TarsonisDoorE),
      2272 => Some(Self::TarsonisDoorELowered),
      2273 => Some(Self::TarsonisDoorELowered),
      2262 => Some(Self::TarsonisDoorN),
      2263 => Some(Self::TarsonisDoorN),
      2264 => Some(Self::TarsonisDoorNLowered),
      2265 => Some(Self::TarsonisDoorNLowered),
      2266 => Some(Self::TarsonisDoorNe),
      2267 => Some(Self::TarsonisDoorNe),
      2268 => Some(Self::TarsonisDoorNeLowered),
      2269 => Some(Self::TarsonisDoorNeLowered),
      2274 => Some(Self::TarsonisDoorNw),
      2275 => Some(Self::TarsonisDoorNw),
      2276 => Some(Self::TarsonisDoorNwLowered),
      2277 => Some(Self::TarsonisDoorNwLowered),
      2 => Some(Self::Taunt),
      3 => Some(Self::Taunt),
      2928 => Some(Self::TaurenOuthouseLiftoff),
      2927 => Some(Self::TaurenOuthouseLiftoffTaurenOuthouseFly),
      2931 => Some(Self::TaurenOuthouseTransport),
      2932 => Some(Self::TaurenOuthouseTransport),
      2933 => Some(Self::TaurenOuthouseTransport),
      2929 => Some(Self::TaurenOuthouseTransportLoadTaurenOuthouse),
      2930 => Some(Self::TaurenOuthouseTransportUnloadTaurenOuthouse),
      3423 => Some(Self::TaurenStimpack),
      3424 => Some(Self::TaurenStimpack),
      1666 => Some(Self::TechLabMorph),
      1667 => Some(Self::TechLabMorph),
      3302 => Some(Self::TechReactorMorph),
      3303 => Some(Self::TechReactorMorph),
      2698 => Some(Self::TempestDisruptionBlast),
      2699 => Some(Self::TempestDisruptionBlastCancel),
      1122 => Some(Self::TemplarArchivesResearch),
      1123 => Some(Self::TemplarArchivesResearch),
      1124 => Some(Self::TemplarArchivesResearch),
      1125 => Some(Self::TemplarArchivesResearch),
      1127 => Some(Self::TemplarArchivesResearch),
      1128 => Some(Self::TemplarArchivesResearch),
      1129 => Some(Self::TemplarArchivesResearch),
      1130 => Some(Self::TemplarArchivesResearch),
      1131 => Some(Self::TemplarArchivesResearch),
      1132 => Some(Self::TemplarArchivesResearch),
      1133 => Some(Self::TemplarArchivesResearch),
      1134 => Some(Self::TemplarArchivesResearch),
      1135 => Some(Self::TemplarArchivesResearch),
      1136 => Some(Self::TemplarArchivesResearch),
      1137 => Some(Self::TemplarArchivesResearch),
      1138 => Some(Self::TemplarArchivesResearch),
      1139 => Some(Self::TemplarArchivesResearch),
      1140 => Some(Self::TemplarArchivesResearch),
      1141 => Some(Self::TemplarArchivesResearch),
      1142 => Some(Self::TemplarArchivesResearch),
      1143 => Some(Self::TemplarArchivesResearch),
      1144 => Some(Self::TemplarArchivesResearch),
      1145 => Some(Self::TemplarArchivesResearch),
      1146 => Some(Self::TemplarArchivesResearch),
      1147 => Some(Self::TemplarArchivesResearch),
      1148 => Some(Self::TemplarArchivesResearch),
      1149 => Some(Self::TemplarArchivesResearch),
      1150 => Some(Self::TemplarArchivesResearch),
      1151 => Some(Self::TemplarArchivesResearch),
      1126 => Some(Self::TemplarArchivesResearchResearchPsiStorm),
      3366 => Some(Self::TempleDoorDown),
      3367 => Some(Self::TempleDoorDown),
      3370 => Some(Self::TempleDoorDownUrdl),
      3371 => Some(Self::TempleDoorDownUrdl),
      3368 => Some(Self::TempleDoorUp),
      3369 => Some(Self::TempleDoorUp),
      3372 => Some(Self::TempleDoorUpUrdl),
      3373 => Some(Self::TempleDoorUpUrdl),
      2244 => Some(Self::TemporalField),
      2245 => Some(Self::TemporalField),
      259 => Some(Self::TemporalRift),
      260 => Some(Self::TemporalRift),
      325 => Some(Self::TerranBuild),
      330 => Some(Self::TerranBuild),
      332 => Some(Self::TerranBuild),
      334 => Some(Self::TerranBuild),
      335 => Some(Self::TerranBuild),
      336 => Some(Self::TerranBuild),
      337 => Some(Self::TerranBuild),
      338 => Some(Self::TerranBuild),
      339 => Some(Self::TerranBuild),
      340 => Some(Self::TerranBuild),
      341 => Some(Self::TerranBuild),
      342 => Some(Self::TerranBuild),
      343 => Some(Self::TerranBuild),
      344 => Some(Self::TerranBuild),
      345 => Some(Self::TerranBuild),
      346 => Some(Self::TerranBuild),
      347 => Some(Self::TerranBuild),
      331 => Some(Self::TerranBuildArmory),
      321 => Some(Self::TerranBuildBarracks),
      324 => Some(Self::TerranBuildBunker),
      348 => Some(Self::TerranBuildCancel),
      318 => Some(Self::TerranBuildCommandCenter),
      3087 => Some(Self::TerranBuildDrop),
      3088 => Some(Self::TerranBuildDrop),
      3089 => Some(Self::TerranBuildDrop),
      3090 => Some(Self::TerranBuildDrop),
      3091 => Some(Self::TerranBuildDrop),
      3092 => Some(Self::TerranBuildDrop),
      3093 => Some(Self::TerranBuildDrop),
      3094 => Some(Self::TerranBuildDrop),
      3095 => Some(Self::TerranBuildDrop),
      3096 => Some(Self::TerranBuildDrop),
      3097 => Some(Self::TerranBuildDrop),
      3098 => Some(Self::TerranBuildDrop),
      3099 => Some(Self::TerranBuildDrop),
      3100 => Some(Self::TerranBuildDrop),
      3101 => Some(Self::TerranBuildDrop),
      3102 => Some(Self::TerranBuildDrop),
      3103 => Some(Self::TerranBuildDrop),
      3104 => Some(Self::TerranBuildDrop),
      3105 => Some(Self::TerranBuildDrop),
      3106 => Some(Self::TerranBuildDrop),
      3107 => Some(Self::TerranBuildDrop),
      3108 => Some(Self::TerranBuildDrop),
      3109 => Some(Self::TerranBuildDrop),
      3110 => Some(Self::TerranBuildDrop),
      3111 => Some(Self::TerranBuildDrop),
      3112 => Some(Self::TerranBuildDrop),
      3113 => Some(Self::TerranBuildDrop),
      3114 => Some(Self::TerranBuildDrop),
      3115 => Some(Self::TerranBuildDrop),
      3116 => Some(Self::TerranBuildDropCancel),
      3086 => Some(Self::TerranBuildDropSupplyDepotDrop),
      322 => Some(Self::TerranBuildEngineeringBay),
      328 => Some(Self::TerranBuildFactory),
      333 => Some(Self::TerranBuildFusionCore),
      327 => Some(Self::TerranBuildGhostAcademy),
      323 => Some(Self::TerranBuildMissileTurret),
      320 => Some(Self::TerranBuildRefinery),
      326 => Some(Self::TerranBuildSensorTower),
      329 => Some(Self::TerranBuildStarport),
      319 => Some(Self::TerranBuildSupplyDepot),
      3655 => Some(Self::TestHeroDebugMissileAbility),
      3656 => Some(Self::TestHeroDebugMissileAbility),
      3657 => Some(Self::TestHeroDebugTrackingAbility),
      3658 => Some(Self::TestHeroDebugTrackingAbilityCancel),
      3652 => Some(Self::TestHeroGrab),
      3651 => Some(Self::TestHeroGrabGrabZergling),
      3654 => Some(Self::TestHeroThrow),
      3653 => Some(Self::TestHeroThrowThrowZergling),
      3514 => Some(Self::TestInteractDesignate),
      3425 => Some(Self::TestInventory),
      3426 => Some(Self::TestInventory),
      3427 => Some(Self::TestInventory),
      3428 => Some(Self::TestInventory),
      3429 => Some(Self::TestInventory),
      3430 => Some(Self::TestInventory),
      3431 => Some(Self::TestInventory),
      3432 => Some(Self::TestInventory),
      3433 => Some(Self::TestInventory),
      3547 => Some(Self::TestLearn),
      3548 => Some(Self::TestLearn),
      3549 => Some(Self::TestLearn),
      3550 => Some(Self::TestLearn),
      3551 => Some(Self::TestLearn),
      3552 => Some(Self::TestLearn),
      3553 => Some(Self::TestLearn),
      3554 => Some(Self::TestLearn),
      3555 => Some(Self::TestLearn),
      3556 => Some(Self::TestLearn),
      3557 => Some(Self::TestLearn),
      3558 => Some(Self::TestLearn),
      3559 => Some(Self::TestLearn),
      3560 => Some(Self::TestLearn),
      3561 => Some(Self::TestLearn),
      3562 => Some(Self::TestLearn),
      3563 => Some(Self::TestLearn),
      3564 => Some(Self::TestLearn),
      3565 => Some(Self::TestLearn),
      3566 => Some(Self::TestLearn),
      3568 => Some(Self::TestLeveledSpell),
      3567 => Some(Self::TestLeveledSpellYamatoGun),
      3434 => Some(Self::TestPawn),
      3435 => Some(Self::TestPawn),
      3436 => Some(Self::TestPawn),
      3437 => Some(Self::TestPawn),
      3438 => Some(Self::TestPawn),
      3439 => Some(Self::TestPawn),
      3440 => Some(Self::TestPawn),
      3441 => Some(Self::TestPawn),
      3442 => Some(Self::TestPawn),
      3443 => Some(Self::TestPawn),
      3444 => Some(Self::TestPawn),
      3445 => Some(Self::TestPawn),
      3446 => Some(Self::TestPawn),
      3447 => Some(Self::TestPawn),
      3448 => Some(Self::TestPawn),
      3449 => Some(Self::TestPawn),
      3450 => Some(Self::TestPawn),
      3451 => Some(Self::TestPawn),
      3452 => Some(Self::TestPawn),
      3453 => Some(Self::TestPawn),
      3455 => Some(Self::TestRevive),
      3456 => Some(Self::TestRevive),
      3457 => Some(Self::TestRevive),
      3458 => Some(Self::TestRevive),
      3459 => Some(Self::TestRevive),
      3460 => Some(Self::TestRevive),
      3461 => Some(Self::TestRevive),
      3462 => Some(Self::TestRevive),
      3463 => Some(Self::TestRevive),
      3464 => Some(Self::TestRevive),
      3465 => Some(Self::TestRevive),
      3466 => Some(Self::TestRevive),
      3467 => Some(Self::TestRevive),
      3468 => Some(Self::TestRevive),
      3469 => Some(Self::TestRevive),
      3470 => Some(Self::TestRevive),
      3471 => Some(Self::TestRevive),
      3472 => Some(Self::TestRevive),
      3473 => Some(Self::TestRevive),
      3475 => Some(Self::TestRevive),
      3476 => Some(Self::TestRevive),
      3477 => Some(Self::TestRevive),
      3478 => Some(Self::TestRevive),
      3479 => Some(Self::TestRevive),
      3480 => Some(Self::TestRevive),
      3481 => Some(Self::TestRevive),
      3482 => Some(Self::TestRevive),
      3483 => Some(Self::TestRevive),
      3454 => Some(Self::TestReviveScv),
      3474 => Some(Self::TestReviveScv),
      3484 => Some(Self::TestSell),
      3485 => Some(Self::TestSell),
      3486 => Some(Self::TestSell),
      3487 => Some(Self::TestSell),
      3488 => Some(Self::TestSell),
      3489 => Some(Self::TestSell),
      3490 => Some(Self::TestSell),
      3491 => Some(Self::TestSell),
      3492 => Some(Self::TestSell),
      3493 => Some(Self::TestSell),
      3494 => Some(Self::TestSell),
      3495 => Some(Self::TestSell),
      3496 => Some(Self::TestSell),
      3497 => Some(Self::TestSell),
      3498 => Some(Self::TestSell),
      3499 => Some(Self::TestSell),
      3500 => Some(Self::TestSell),
      3501 => Some(Self::TestSell),
      3502 => Some(Self::TestSell),
      3503 => Some(Self::TestSell),
      3504 => Some(Self::TestSell),
      3505 => Some(Self::TestSell),
      3506 => Some(Self::TestSell),
      3507 => Some(Self::TestSell),
      3508 => Some(Self::TestSell),
      3509 => Some(Self::TestSell),
      3510 => Some(Self::TestSell),
      3511 => Some(Self::TestSell),
      3512 => Some(Self::TestSell),
      3513 => Some(Self::TestSell),
      2079 => Some(Self::TestZerg),
      2080 => Some(Self::TestZergCancel),
      3077 => Some(Self::TheMorosDevice),
      3078 => Some(Self::TheMorosDevice),
      2362 => Some(Self::ThorApModeArmorpiercingMode),
      2363 => Some(Self::ThorApModeCancel),
      2365 => Some(Self::ThorNormalModeCancel),
      2364 => Some(Self::ThorNormalModeExplosiveMode),
      3322 => Some(Self::ThorReborn),
      3323 => Some(Self::ThorRebornCancel),
      3318 => Some(Self::ThorWreckage),
      3319 => Some(Self::ThorWreckage),
      2562 => Some(Self::TimeStop),
      2563 => Some(Self::TimeStopCancel),
      261 => Some(Self::TimeWarp),
      262 => Some(Self::TimeWarp),
      2101 => Some(Self::TornadoMissile),
      3079 => Some(Self::TossGrenade),
      3080 => Some(Self::TossGrenade),
      1820 => Some(Self::TowerCapture),
      1632 => Some(Self::TrainQueen),
      1633 => Some(Self::TrainQueen),
      1634 => Some(Self::TrainQueen),
      1635 => Some(Self::TrainQueen),
      1636 => Some(Self::TrainQueen),
      1637 => Some(Self::TrainQueen),
      1638 => Some(Self::TrainQueen),
      1639 => Some(Self::TrainQueen),
      1640 => Some(Self::TrainQueen),
      1641 => Some(Self::TrainQueen),
      1642 => Some(Self::TrainQueen),
      1643 => Some(Self::TrainQueen),
      1644 => Some(Self::TrainQueen),
      1645 => Some(Self::TrainQueen),
      1646 => Some(Self::TrainQueen),
      1647 => Some(Self::TrainQueen),
      1648 => Some(Self::TrainQueen),
      1649 => Some(Self::TrainQueen),
      1650 => Some(Self::TrainQueen),
      1651 => Some(Self::TrainQueen),
      1652 => Some(Self::TrainQueen),
      1653 => Some(Self::TrainQueen),
      1654 => Some(Self::TrainQueen),
      1655 => Some(Self::TrainQueen),
      1656 => Some(Self::TrainQueen),
      1657 => Some(Self::TrainQueen),
      1658 => Some(Self::TrainQueen),
      1659 => Some(Self::TrainQueen),
      1660 => Some(Self::TrainQueen),
      1661 => Some(Self::TrainQueen),
      1664 => Some(Self::Transfusion),
      1665 => Some(Self::Transfusion),
      3668 => Some(Self::TransportLoad),
      3663 => Some(Self::TransportLoadAll),
      1530 => Some(Self::TransportMode),
      1531 => Some(Self::TransportModeCancel),
      3175 => Some(Self::TransportTruckTransport),
      3176 => Some(Self::TransportTruckTransport),
      3177 => Some(Self::TransportTruckTransport),
      3173 => Some(Self::TransportTruckTransportTransportTruckLoad),
      3174 => Some(Self::TransportTruckTransportTransportTruckUnloadAll),
      3664 => Some(Self::TransportUnloadAll),
      3669 => Some(Self::TransportUnloadAt),
      3670 => Some(Self::TransportUnloadUnit),
      1595 => Some(Self::TwilightCouncilResearch),
      1596 => Some(Self::TwilightCouncilResearch),
      1597 => Some(Self::TwilightCouncilResearch),
      1598 => Some(Self::TwilightCouncilResearch),
      1599 => Some(Self::TwilightCouncilResearch),
      1600 => Some(Self::TwilightCouncilResearch),
      1601 => Some(Self::TwilightCouncilResearch),
      1602 => Some(Self::TwilightCouncilResearch),
      1603 => Some(Self::TwilightCouncilResearch),
      1604 => Some(Self::TwilightCouncilResearch),
      1605 => Some(Self::TwilightCouncilResearch),
      1606 => Some(Self::TwilightCouncilResearch),
      1607 => Some(Self::TwilightCouncilResearch),
      1608 => Some(Self::TwilightCouncilResearch),
      1609 => Some(Self::TwilightCouncilResearch),
      1610 => Some(Self::TwilightCouncilResearch),
      1611 => Some(Self::TwilightCouncilResearch),
      1612 => Some(Self::TwilightCouncilResearch),
      1613 => Some(Self::TwilightCouncilResearch),
      1614 => Some(Self::TwilightCouncilResearch),
      1615 => Some(Self::TwilightCouncilResearch),
      1616 => Some(Self::TwilightCouncilResearch),
      1617 => Some(Self::TwilightCouncilResearch),
      1618 => Some(Self::TwilightCouncilResearch),
      1619 => Some(Self::TwilightCouncilResearch),
      1620 => Some(Self::TwilightCouncilResearch),
      1621 => Some(Self::TwilightCouncilResearch),
      1594 => Some(Self::TwilightCouncilResearchAdeptResearchPiercingUpgrade),
      1592 => Some(Self::TwilightCouncilResearchResearchCharge),
      1593 => Some(Self::TwilightCouncilResearchResearchStalkerTeleport),
      2934 => Some(Self::Tychus03OmegaStorm),
      2935 => Some(Self::Tychus03OmegaStorm),
      _ => None,
    }
  }
}
