
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum V {
  Val03QueenOfBladesBurrow,
  Val03QueenOfBladesBurrowBurrowDown,
  Val03QueenOfBladesDeepTunnel,
  Val03QueenOfBladesUnburrow,
  Val03QueenOfBladesUnburrowBurrowUp,
  ViperConsume,
  ViperConsumeMinerals,
  ViperConsumeStructure,
  ViperParasiticBombRelay,
  VoidMpImmortalReviveDeath,
  VoidMpImmortalReviveRebuild,
  VoidRaySwarmDamageBoost,
  VoidRaySwarmDamageBoostCancel,
  VoidSeekerDock,
  VoidSeekerPhaseMineBlast,
  VoidSeekerTransport,
  VoidSeekerTransportMedivacLoad,
  VoidSeekerTransportMedivacUnloadAll,
  VoidSiphon,
  VoidSwarmHostSpawnLocust,
  VolatileBurstBuildingDisableBuildingAttack,
  VolatileBurstBuildingEnableBuildingAttack,
  VoodooShield,
  Vortex,
  VortexPurifier,
  VultureQueue3Cancel,
  VultureQueue3CancelSlot,
  VultureSpiderMineBurrow,
  VultureSpiderMineUnburrow,
  VultureSpiderMines,
}
impl V {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      3179 => Some(Self::Val03QueenOfBladesBurrow),
      3178 => Some(Self::Val03QueenOfBladesBurrowBurrowDown),
      3180 => Some(Self::Val03QueenOfBladesDeepTunnel),
      3181 => Some(Self::Val03QueenOfBladesDeepTunnel),
      3183 => Some(Self::Val03QueenOfBladesUnburrow),
      3182 => Some(Self::Val03QueenOfBladesUnburrowBurrowUp),
      2069 => Some(Self::ViperConsume),
      2070 => Some(Self::ViperConsume),
      2071 => Some(Self::ViperConsumeMinerals),
      2072 => Some(Self::ViperConsumeMinerals),
      2073 => Some(Self::ViperConsumeStructure),
      2074 => Some(Self::ViperConsumeStructure),
      3789 => Some(Self::ViperParasiticBombRelay),
      3790 => Some(Self::ViperParasiticBombRelay),
      2471 => Some(Self::VoidMpImmortalReviveDeath),
      2472 => Some(Self::VoidMpImmortalReviveDeath),
      2469 => Some(Self::VoidMpImmortalReviveRebuild),
      2470 => Some(Self::VoidMpImmortalReviveRebuild),
      2393 => Some(Self::VoidRaySwarmDamageBoost),
      2394 => Some(Self::VoidRaySwarmDamageBoost),
      3707 => Some(Self::VoidRaySwarmDamageBoostCancel),
      3708 => Some(Self::VoidRaySwarmDamageBoostCancel),
      3376 => Some(Self::VoidSeekerDock),
      3377 => Some(Self::VoidSeekerDock),
      3171 => Some(Self::VoidSeekerPhaseMineBlast),
      3172 => Some(Self::VoidSeekerPhaseMineBlast),
      3082 => Some(Self::VoidSeekerTransport),
      3084 => Some(Self::VoidSeekerTransport),
      3085 => Some(Self::VoidSeekerTransport),
      3081 => Some(Self::VoidSeekerTransportMedivacLoad),
      3083 => Some(Self::VoidSeekerTransportMedivacUnloadAll),
      2156 => Some(Self::VoidSiphon),
      2157 => Some(Self::VoidSiphon),
      2381 => Some(Self::VoidSwarmHostSpawnLocust),
      2382 => Some(Self::VoidSwarmHostSpawnLocust),
      2082 => Some(Self::VolatileBurstBuildingDisableBuildingAttack),
      2081 => Some(Self::VolatileBurstBuildingEnableBuildingAttack),
      2878 => Some(Self::VoodooShield),
      2879 => Some(Self::VoodooShield),
      1630 => Some(Self::Vortex),
      1631 => Some(Self::Vortex),
      3234 => Some(Self::VortexPurifier),
      3235 => Some(Self::VortexPurifier),
      3198 => Some(Self::VultureQueue3Cancel),
      3199 => Some(Self::VultureQueue3CancelSlot),
      3184 => Some(Self::VultureSpiderMineBurrow),
      3185 => Some(Self::VultureSpiderMineBurrow),
      3186 => Some(Self::VultureSpiderMineUnburrow),
      3187 => Some(Self::VultureSpiderMineUnburrow),
      3196 => Some(Self::VultureSpiderMines),
      3197 => Some(Self::VultureSpiderMines),
      _ => None,
    }
  }
}
