
#[cfg(feature = "arrow")]
use arrow2_convert::{ArrowDeserialize, ArrowField, ArrowSerialize};

use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "arrow",
  derive(ArrowField, ArrowSerialize, ArrowDeserialize)
)]
#[cfg_attr(feature = "arrow", arrow_field(type = "sparse"))]
pub enum X {
  XelNagaCavernsDoorE,
  XelNagaCavernsDoorEOpened,
  XelNagaCavernsDoorEOpenedXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorEXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorN,
  XelNagaCavernsDoorNOpened,
  XelNagaCavernsDoorNOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorNXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorNe,
  XelNagaCavernsDoorNeOpened,
  XelNagaCavernsDoorNeOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorNeXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorNw,
  XelNagaCavernsDoorNwOpened,
  XelNagaCavernsDoorNwOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorNwXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorS,
  XelNagaCavernsDoorSOpened,
  XelNagaCavernsDoorSOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorSXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorSe,
  XelNagaCavernsDoorSeOpened,
  XelNagaCavernsDoorSeOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorSeXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorSw,
  XelNagaCavernsDoorSwOpened,
  XelNagaCavernsDoorSwOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorSwXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsDoorW,
  XelNagaCavernsDoorWOpened,
  XelNagaCavernsDoorWOpenedXelNagaCavernsDoorDefaultOpen,
  XelNagaCavernsDoorWXelNagaCavernsDoorDefaultClose,
  XelNagaCavernsFloatingBridgeH10,
  XelNagaCavernsFloatingBridgeH10BridgeRetract,
  XelNagaCavernsFloatingBridgeH10Out,
  XelNagaCavernsFloatingBridgeH10OutBridgeExtend,
  XelNagaCavernsFloatingBridgeH12,
  XelNagaCavernsFloatingBridgeH12BridgeRetract,
  XelNagaCavernsFloatingBridgeH12Out,
  XelNagaCavernsFloatingBridgeH12OutBridgeExtend,
  XelNagaCavernsFloatingBridgeH8,
  XelNagaCavernsFloatingBridgeH8BridgeRetract,
  XelNagaCavernsFloatingBridgeH8Out,
  XelNagaCavernsFloatingBridgeH8OutBridgeExtend,
  XelNagaCavernsFloatingBridgeNe10,
  XelNagaCavernsFloatingBridgeNe10BridgeRetract,
  XelNagaCavernsFloatingBridgeNe10Out,
  XelNagaCavernsFloatingBridgeNe10OutBridgeExtend,
  XelNagaCavernsFloatingBridgeNe12,
  XelNagaCavernsFloatingBridgeNe12BridgeRetract,
  XelNagaCavernsFloatingBridgeNe12Out,
  XelNagaCavernsFloatingBridgeNe12OutBridgeExtend,
  XelNagaCavernsFloatingBridgeNe8,
  XelNagaCavernsFloatingBridgeNe8BridgeRetract,
  XelNagaCavernsFloatingBridgeNe8Out,
  XelNagaCavernsFloatingBridgeNe8OutBridgeExtend,
  XelNagaCavernsFloatingBridgeNw10,
  XelNagaCavernsFloatingBridgeNw10BridgeRetract,
  XelNagaCavernsFloatingBridgeNw10Out,
  XelNagaCavernsFloatingBridgeNw10OutBridgeExtend,
  XelNagaCavernsFloatingBridgeNw12,
  XelNagaCavernsFloatingBridgeNw12BridgeRetract,
  XelNagaCavernsFloatingBridgeNw12Out,
  XelNagaCavernsFloatingBridgeNw12OutBridgeExtend,
  XelNagaCavernsFloatingBridgeNw8,
  XelNagaCavernsFloatingBridgeNw8BridgeRetract,
  XelNagaCavernsFloatingBridgeNw8Out,
  XelNagaCavernsFloatingBridgeNw8OutBridgeExtend,
  XelNagaCavernsFloatingBridgeV10,
  XelNagaCavernsFloatingBridgeV10BridgeRetract,
  XelNagaCavernsFloatingBridgeV10Out,
  XelNagaCavernsFloatingBridgeV10OutBridgeExtend,
  XelNagaCavernsFloatingBridgeV12,
  XelNagaCavernsFloatingBridgeV12BridgeRetract,
  XelNagaCavernsFloatingBridgeV12Out,
  XelNagaCavernsFloatingBridgeV12OutBridgeExtend,
  XelNagaCavernsFloatingBridgeV8,
  XelNagaCavernsFloatingBridgeV8BridgeRetract,
  XelNagaCavernsFloatingBridgeV8Out,
  XelNagaCavernsFloatingBridgeV8OutBridgeExtend,
  XelNagaHealingShrine,
}
impl X {
    pub fn from_id(id: u16) -> Option<Self> {
      match id {
      2165 => Some(Self::XelNagaCavernsDoorE),
      2167 => Some(Self::XelNagaCavernsDoorEOpened),
      2166 => Some(Self::XelNagaCavernsDoorEOpenedXelNagaCavernsDoorDefaultClose),
      2164 => Some(Self::XelNagaCavernsDoorEXelNagaCavernsDoorDefaultClose),
      2169 => Some(Self::XelNagaCavernsDoorN),
      2175 => Some(Self::XelNagaCavernsDoorNOpened),
      2174 => Some(Self::XelNagaCavernsDoorNOpenedXelNagaCavernsDoorDefaultOpen),
      2168 => Some(Self::XelNagaCavernsDoorNXelNagaCavernsDoorDefaultClose),
      2171 => Some(Self::XelNagaCavernsDoorNe),
      2173 => Some(Self::XelNagaCavernsDoorNeOpened),
      2172 => Some(Self::XelNagaCavernsDoorNeOpenedXelNagaCavernsDoorDefaultOpen),
      2170 => Some(Self::XelNagaCavernsDoorNeXelNagaCavernsDoorDefaultClose),
      2177 => Some(Self::XelNagaCavernsDoorNw),
      2179 => Some(Self::XelNagaCavernsDoorNwOpened),
      2178 => Some(Self::XelNagaCavernsDoorNwOpenedXelNagaCavernsDoorDefaultOpen),
      2176 => Some(Self::XelNagaCavernsDoorNwXelNagaCavernsDoorDefaultClose),
      2181 => Some(Self::XelNagaCavernsDoorS),
      2187 => Some(Self::XelNagaCavernsDoorSOpened),
      2186 => Some(Self::XelNagaCavernsDoorSOpenedXelNagaCavernsDoorDefaultOpen),
      2180 => Some(Self::XelNagaCavernsDoorSXelNagaCavernsDoorDefaultClose),
      2183 => Some(Self::XelNagaCavernsDoorSe),
      2185 => Some(Self::XelNagaCavernsDoorSeOpened),
      2184 => Some(Self::XelNagaCavernsDoorSeOpenedXelNagaCavernsDoorDefaultOpen),
      2182 => Some(Self::XelNagaCavernsDoorSeXelNagaCavernsDoorDefaultClose),
      2189 => Some(Self::XelNagaCavernsDoorSw),
      2191 => Some(Self::XelNagaCavernsDoorSwOpened),
      2190 => Some(Self::XelNagaCavernsDoorSwOpenedXelNagaCavernsDoorDefaultOpen),
      2188 => Some(Self::XelNagaCavernsDoorSwXelNagaCavernsDoorDefaultClose),
      2193 => Some(Self::XelNagaCavernsDoorW),
      2195 => Some(Self::XelNagaCavernsDoorWOpened),
      2194 => Some(Self::XelNagaCavernsDoorWOpenedXelNagaCavernsDoorDefaultOpen),
      2192 => Some(Self::XelNagaCavernsDoorWXelNagaCavernsDoorDefaultClose),
      2231 => Some(Self::XelNagaCavernsFloatingBridgeH10),
      2230 => Some(Self::XelNagaCavernsFloatingBridgeH10BridgeRetract),
      2229 => Some(Self::XelNagaCavernsFloatingBridgeH10Out),
      2228 => Some(Self::XelNagaCavernsFloatingBridgeH10OutBridgeExtend),
      2239 => Some(Self::XelNagaCavernsFloatingBridgeH12),
      2238 => Some(Self::XelNagaCavernsFloatingBridgeH12BridgeRetract),
      2237 => Some(Self::XelNagaCavernsFloatingBridgeH12Out),
      2236 => Some(Self::XelNagaCavernsFloatingBridgeH12OutBridgeExtend),
      2223 => Some(Self::XelNagaCavernsFloatingBridgeH8),
      2222 => Some(Self::XelNagaCavernsFloatingBridgeH8BridgeRetract),
      2221 => Some(Self::XelNagaCavernsFloatingBridgeH8Out),
      2220 => Some(Self::XelNagaCavernsFloatingBridgeH8OutBridgeExtend),
      2207 => Some(Self::XelNagaCavernsFloatingBridgeNe10),
      2206 => Some(Self::XelNagaCavernsFloatingBridgeNe10BridgeRetract),
      2205 => Some(Self::XelNagaCavernsFloatingBridgeNe10Out),
      2204 => Some(Self::XelNagaCavernsFloatingBridgeNe10OutBridgeExtend),
      2215 => Some(Self::XelNagaCavernsFloatingBridgeNe12),
      2214 => Some(Self::XelNagaCavernsFloatingBridgeNe12BridgeRetract),
      2213 => Some(Self::XelNagaCavernsFloatingBridgeNe12Out),
      2212 => Some(Self::XelNagaCavernsFloatingBridgeNe12OutBridgeExtend),
      2199 => Some(Self::XelNagaCavernsFloatingBridgeNe8),
      2198 => Some(Self::XelNagaCavernsFloatingBridgeNe8BridgeRetract),
      2197 => Some(Self::XelNagaCavernsFloatingBridgeNe8Out),
      2196 => Some(Self::XelNagaCavernsFloatingBridgeNe8OutBridgeExtend),
      2211 => Some(Self::XelNagaCavernsFloatingBridgeNw10),
      2210 => Some(Self::XelNagaCavernsFloatingBridgeNw10BridgeRetract),
      2209 => Some(Self::XelNagaCavernsFloatingBridgeNw10Out),
      2208 => Some(Self::XelNagaCavernsFloatingBridgeNw10OutBridgeExtend),
      2219 => Some(Self::XelNagaCavernsFloatingBridgeNw12),
      2218 => Some(Self::XelNagaCavernsFloatingBridgeNw12BridgeRetract),
      2217 => Some(Self::XelNagaCavernsFloatingBridgeNw12Out),
      2216 => Some(Self::XelNagaCavernsFloatingBridgeNw12OutBridgeExtend),
      2203 => Some(Self::XelNagaCavernsFloatingBridgeNw8),
      2202 => Some(Self::XelNagaCavernsFloatingBridgeNw8BridgeRetract),
      2201 => Some(Self::XelNagaCavernsFloatingBridgeNw8Out),
      2200 => Some(Self::XelNagaCavernsFloatingBridgeNw8OutBridgeExtend),
      2235 => Some(Self::XelNagaCavernsFloatingBridgeV10),
      2234 => Some(Self::XelNagaCavernsFloatingBridgeV10BridgeRetract),
      2233 => Some(Self::XelNagaCavernsFloatingBridgeV10Out),
      2232 => Some(Self::XelNagaCavernsFloatingBridgeV10OutBridgeExtend),
      2243 => Some(Self::XelNagaCavernsFloatingBridgeV12),
      2242 => Some(Self::XelNagaCavernsFloatingBridgeV12BridgeRetract),
      2241 => Some(Self::XelNagaCavernsFloatingBridgeV12Out),
      2240 => Some(Self::XelNagaCavernsFloatingBridgeV12OutBridgeExtend),
      2227 => Some(Self::XelNagaCavernsFloatingBridgeV8),
      2226 => Some(Self::XelNagaCavernsFloatingBridgeV8BridgeRetract),
      2225 => Some(Self::XelNagaCavernsFloatingBridgeV8Out),
      2224 => Some(Self::XelNagaCavernsFloatingBridgeV8OutBridgeExtend),
      1928 => Some(Self::XelNagaHealingShrine),
      1929 => Some(Self::XelNagaHealingShrine),
      _ => None,
    }
  }
}
